### ISSUE TITLE
getDaoSession().getProjectDao()  on a null object reference

### ISSUE THREAD

**Issue by zhujiang521** [greenrobot/greenDAO#1001]
```java
 /**
     * 初始化GreenDao,直接在Application中进行初始化操作
     */
    private void initGreenDao() {
        //DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, "bhne.db");
        NewDaoMaster helper = new NewDaoMaster(this, "bhne.db",null); //升级数据库使用，数据不会丢失
        SQLiteDatabase db = helper.getWritableDatabase(); //不加密的写法
        //Database db = helper.getEncryptedWritableDb("bhne"); //数据库加密密码为"bhne"的写法
        DaoMaster daoMaster = new DaoMaster(db);
        daoSession = daoMaster.newSession();
    }

    /**
     * 获取数据库操作
     *
     * @return daoSession
     */
    public DaoSession getDaoSession() {
        return daoSession;
    }

```

**Comment by greenrobot-team** [comment]
I'm not sure how this is a greenDAO issue. Maybe set up greenDAO in a thread-safe singleton instead.

**Comment by kokobebekoko** [comment]
> ```java
>  /**
>      * 初始化GreenDao,直接在Application中进行初始化操作
>      */
>     private void initGreenDao() {
>         //DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, "bhne.db");
>         NewDaoMaster helper = new NewDaoMaster(this, "bhne.db",null); //升级数据库使用，数据不会丢失
>         SQLiteDatabase db = helper.getWritableDatabase(); //不加密的写法
>         //Database db = helper.getEncryptedWritableDb("bhne"); //数据库加密密码为"bhne"的写法
>         DaoMaster daoMaster = new DaoMaster(db);
>         daoSession = daoMaster.newSession();
>     }
> 
>     /**
>      * 获取数据库操作
>      *
>      * @return daoSession
>      */
>     public DaoSession getDaoSession() {
>         return daoSession;
>     }
> ```

老哥你这个问题解决了吗

**Comment by greenrobot-team** [comment]
@kokobebekoko The original poster has not shared any details that allow us to reproduce a greenDAO issue. If you are facing this, please create a new issue with additional details so we can reproduce this.
