### ISSUE TITLE
Parsing fails when using JDK 9 or newer

### ISSUE THREAD

**Issue by shikefei89** [greenrobot/greenDAO#1014]
evn:Mac idea jdk11 greenDao3.2.2.
It can not generate code.
It works well in windows same environment but jdk8.

there is log:
Execution failed for task ':app:greendao'.
> Found 8 problem(s) parsing "/Users/paul/Documents/Android/x-x-android/app/src/main/java/com/x/x/test/x.java". First problem:
  Pb(324) The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files (16777540 at line 1).

help me.

**Comment by greenrobot-team** [comment]
JDK 11 is not supported by greenDAO (or the Android plugin), make sure to use JDK 8.

**Comment by greenrobot-team** [comment]
`3.3.0` has been released which should fix this issue.
https://greenrobot.org/greendao/changelog/
