### ISSUE TITLE
 gradle version update to 6.4 failed

### ISSUE THREAD

**Issue by NassPage** [greenrobot/greenDAO#1041]
after updating my gradle version to 6.4 and gradle plugin version to 4.0.0 i'm getting error 
`Unable to find method 'org.gradle.api.tasks.TaskInputs.property(Ljava/lang/String;Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskInputs;'.`

but the error is not displayed if i have removed 
`apply plugin: 'org.greenrobot.greendao'` from my app projects build.gradle file

-how can i resolve this error?
-is/will greendao supporting/support newer gradle version?

and another question i have that always wanted to ask, why we use **apply plugin: 'org.greenrobot.greendao'** and not just simply use implement in dependencies

**Comment by NicodeLee** [comment]
I try update to 6.5-all.zip,this issues solved.

**Comment by NassPage** [comment]
do you have added 
`apply plugin: 'org.greenrobot.greendao'`
in your app level build.gradle file?

**Comment by NassPage** [comment]
i checked with greendao 3.3.0 and its solved
but the documentation in site is not updated and says to use 3.2.2
