### ISSUE TITLE
Please release latest benchmark report.

### ISSUE THREAD

**Issue by DevDengChao** [greenrobot/greenDAO#1073]
[Last avaliable benchmark report is released in 2016](https://greenrobot.org/android/android-orm-performance-2016/). 

https://github.com/greenrobot/android-database-performance project is still maintaining last year but no reports were released since then.

( Maybe I didn't found those newer reports )

**Comment by greenrobot-team** [comment]
No plans to do this (there also haven't been any significant changes to greenDAO where one would expect drastically different results). Feel free to run the benchmarks yourself.
