### ISSUE TITLE
Is there any plan for supporting gradle 7.0?

### ISSUE THREAD

**Issue by jepack** [greenrobot/greenDAO#1094]
Greendao generate diff DB  classes which related to the "org.greenrobot.greendao.annotation.Entity" in every Incremental compilation. It  slow down the speed of compilation seriously.  It is appeared in gradle 7.0 which used JDK 11.  Is there any plan for supporting gradle 7.0?

**Comment by greenrobot-team** [comment]
Looks like this is a duplicate of #1075
