### ISSUE TITLE
Openharmony  application

### ISSUE THREAD

**Issue by chenguangweixi** [greenrobot/greenDAO#1098]
I  am  developing  an  Openharmony  application with JavaScript langue which used your library,will your library support Openharmony platform by JavaScript language? If so,I want to contribute to the Openharmony build of this library. Expecte for your repley!

**Comment by greenrobot-team** [comment]
Thanks for the request, but I don't think we will. Our efforts are currently focused on https://github.com/objectbox/objectbox-java (and its other languages supported).
