### ISSUE TITLE
一对多的关系表映射问题

### ISSUE THREAD

**Issue by tomKitty888888** [greenrobot/greenDAO#1099]
@Entity
public class 我 {

    @Id(autoincrement = true)
    Long id;

    @ToMany(referencedJoinProperty = "masterId")
    private 钱 钱List;
}

@Entity
public class 钱 {

    @Id(autoincrement = true)
    Long id;

    Long masterId;
}
注解都有，查询不到list数据

**Comment by AncientTree** [comment]
我也遇到这个问题，toMany 的list从数据库读出来是null，请问一下你是如何解决的？

**Comment by tomKitty888888** [comment]
在两个关系表所对应的实体类中需要进行1对多的关联配置，如果已经配置好了，那么在检查在取多数据时的方法：不是直接get类中对应的list，是get关联配置的那个方法才能获取到数据，希望对你有用。




***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "greenrobot/greenDAO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月4日(星期六) 晚上7:00
***@***.***&gt;;
***@***.******@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [greenrobot/greenDAO] 一对多的关系表映射问题 (Issue #1099)





 
我也遇到这个问题，toMany 的list从数据库读出来是null，请问一下你是如何解决的？

**Comment by AncientTree** [comment]
谢谢，已经解决啦，找到问题所在了。和你说的这个情况很像，我是通过属性访问`modelOne.modelTwoLIst`，每次都是null，这是我用法错误。正确用法是`modelOne.getModelTwoList()` ，GreenDao在首次Build的时候已经给ModelOne中所有标记有`@ToMany`的属性自动生成了`getter`，这个自动生成的`getter`首次被调用时会自动读取数据库来加载填充`modelTwoLIst`。谢谢你的指导，也为后来朋友提供个参考。
