### ISSUE TITLE
disk image is malformed (Sqlite code 11 SQLITE_CORRUPT)

### ISSUE THREAD

**Issue by qidianli** [greenrobot/greenDAO#1100]
Please deal th question 
Question Description：
The database version was upgraded from 4 to 6, a database table was added, and an error was reported after the APP covered the upgrade and installed

Caused by:
android.database.sqlite.SQLiteDatabaseCorruptException:database disk image is malformed (Sqlite code 11 SQLITE_CORRUPT), (OS error - 11:Try again)
android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:692)
android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:449)
android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:413)
android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:611)
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:442)
android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:332)
com.project.common.sqlUtil.greendao.DbController.getWritableDatabase(DbController.java:90)
com.project.common.sqlUtil.greendao.DbController.<init>(DbController.java:66)
com.project.common.sqlUtil.greendao.DbController.getInstance(DbController.java:50)
com.project.common.sqlUtil.dao.InformationDao.queryAll(InformationDao.java:27)
cn.com.qlwb.qiluyidian.Main.initInformationHis(Main.java:456)
cn.com.qlwb.qiluyidian.Main.initMain(Main.java:422)

**Comment by greenrobot-team** [comment]
Thanks for reporting. However, this is nothing greenDAO specific, but rather an issue with SQLite. See e.g. https://stackoverflow.com/a/2960439/9187282.
