### ISSUE TITLE
Can I use greenDao in multiple libraries? ------ Look forward to your reply

### ISSUE THREAD

**Issue by jingqingqingxinye** [greenrobot/greenDAO#1104]
Hi，greenDao-team, I had encountered a problem that is "android.database.sqlite.SQLiteException: no such table", when use greenDao in multiple libraries . Are all Entity classes in the same library? Look forward to your reply, thanks！

**Comment by greenrobot-team** [comment]
All entity classes must be in the same module as the greenDAO dependency. E.g. you have to create a separate database (with a different name) for each module.
