### ISSUE TITLE
@ToMany Can't the associated field be a string type?

### ISSUE THREAD

**Issue by zpswz** [greenrobot/greenDAO#1117]
@ToMany(referencedJoinProperty = "p_fid")
private List<ImageBean> imageList;

p_fid type is string 

error log
Long cannot be converted to String
List<ImageBean> imageListNew = targetDao._queryDirectoryBean_ImageList(id);

The automatically generated code is queried directly with the id

**Comment by greenrobot-team** [comment]
The `referencedJoinProperty` needs to point to the `@Id` of the targeted entity. See https://greenrobot.org/greendao/documentation/relations/ for details and examples.
