### ISSUE TITLE
How to update an record with where condition?

### ISSUE THREAD

**Issue by vishalkharat123** [greenrobot/greenDAO#126]
As we can execute an "Update " statement on database with where condition, but those changes are not reflected in corresponding Dao.

**Comment by rajajawahar** [comment]
How to update a Row in a table by it value not by Id

**Comment by zhangmingxingAtGit** [comment]
How to update a Row in a table by it value not by Id?

**Comment by DaaarK** [comment]
how to update by id

**Comment by hzw1199** [comment]
How to update a Row in a table by it value not by Id?

**Comment by greenrobot-team** [comment]
Read about [how to update an entity](http://greenrobot.org/greendao/documentation/how-to-get-started/#Updating_notes) in the new docs.

To get an entity, you can [query for it](http://greenrobot.org/greendao/documentation/queries/) or get it by its key using `dao.load(key)`. Check the methods on your DAO class for additional ways to get a hold of an entity.
-ut

**Comment by jp1017** [comment]
> How to update a Row in a table by it value not by Id?

1. query
2. update
