### ISSUE TITLE
Update application with databse using greenDAO

### ISSUE THREAD

**Issue by rinlv** [greenrobot/greenDAO#137]
Hi, i'm using greenDAO to create my application database. I wonder when i update new version for my application, my database can keep old record or my database have been reset. Thanks.

**Comment by fineswap** [comment]
Take a look at this nice library for doing that:
https://github.com/noordawod/sqlite-manager

**Comment by yuweiguocn** [comment]
This library may be can help you and just need one line code:https://github.com/yuweiguocn/GreenDaoUpgradeHelper

**Comment by kpradeepkumarreddy** [comment]
I'm using GreenDao . how to trigger the onUpgrade() method after defining a class that extends  OpenHelper.
