### ISSUE TITLE
KEEP sections erased unless there's an empty line after the last closing bracket of the generated file

### ISSUE THREAD

**Issue by Nodjo** [greenrobot/greenDAO#151]
Everything is in the title. If for example the IDE's custom code formatter removes the empty line after the file's closing bracket of a generated entity class file, the next generation will erase the KEEP sections.

That one gave me a couple hours of fun.

**Comment by greenrobot-team** [comment]
No longer relevant as [greenDAO 3 does no longer support KEEP section](http://greenrobot.org/greendao/documentation/modelling-entities/#Keep_sections)s. -ut
