### ISSUE TITLE
DaoExample is not an android project in android studio 0.8.9

### ISSUE THREAD

**Issue by jast90** [greenrobot/greenDAO#155]
![geendao](https://cloud.githubusercontent.com/assets/2128771/4931630/5d2f3f1c-657c-11e4-963b-bfbaad3b6d99.png)
see the screenshot.The DaoTest is an Android project!!

**Comment by sharyuke** [comment]
you should config some with it.

**Comment by mrljdx** [comment]
what's your gradle version and AndroidStudio version ? In AndroidStudio v1.0.+ ,the gradle plugin must be 1.0.+ , just look the dependencies , it's "0.12.2" , so you should config some with it.
