### ISSUE TITLE
How can I use "GROUP BY"

### ISSUE THREAD

**Issue by LiJohnson** [greenrobot/greenDAO#164]
[AbstractDao.query](http://greendao-orm.com/javadoc/greendao/de/greenrobot/dao/AbstractDao.html) not found any more ?!

**Comment by adrian011494** [comment]
This is the solution: [http://stackoverflow.com/questions/27906592/greendao-groupby-clause](url)
`List<Taxi> list = daoSession.getDaoTaxi().queryBuilder().where(new WhereCondition.StringCondition("1 GROUP BY cant_aciento")).list();`

**Comment by LiJohnson** [comment]
👍

**Comment by AlexeyPoldeo** [comment]
With all my respect, it's silly to limit the initial SQL functionality because of ideological considerations.

**Comment by LuzianW** [comment]
>GROUP BY is SQL-ish, so stick to SQL. greenDAO is about entities, where GROUP BY is unsupported.

IMHO, if you support COUNT, it makes no sense not to support GROUP BY. They are equally "SQL-ish" and always belong together
