### ISSUE TITLE
can not compile green Dao Generator

### ISSUE THREAD

**Issue by sharyuke** [greenrobot/greenDAO#172]
if I  compile de.greenrobot:DaoGenerator:1.3.0 or de.greenrobot:DaoCore:1.3.0,i got Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2 .

but if I don't compile it ,i got class not found when running  new DaoGenerator().generateAll(schema, ".");

how to solve it?

**Comment by sharyuke** [comment]
android.jar does not contain java file java.beans.IntrospectionException, but the green dao project dependency which is package freemarker.ext.beans ,depend the file  java.beans.IntrospectionException which is included in file rt.jar. so the ide throw the error Suppressed: java.lang.ClassNotFoundException: java.beans.Introspector

**Comment by messiahluo** [comment]
DaoGenerator is a java module, you should not compile it with android sdk, just jdk should be fine.

**Comment by sharyuke** [comment]
@messiahluo yes ,i found it ,  so if i want to use greenDAO for android development , i must wait to new version release .

**Comment by messiahluo** [comment]
@sharyuke no, you should add daoGenerator as a library module and your Android project do not need to depend on it, just run generator as a java program and put the generated class in your Android project, of course add greendao core as library, then you are good to go.

**Comment by sharyuke** [comment]
I got it ,,, just run it  to Generat classes ...yes ,,,,that it!
