### ISSUE TITLE
Error On Insert

### ISSUE THREAD

**Issue by masoudfcr** [greenrobot/greenDAO#204]
i get  "PRIMARY KEY must be unique" when i insert an entity, I followed the example but still get the error

```
      db.execSQL("CREATE TABLE " + constraint + "'BOOKMARK' (" + //
             "'_id' INTEGER PRIMARY KEY," + // 0: id
             "'BOOKID' INTEGER NOT NULL ," + // 1: bookId
             "'TEXT' TEXT NOT NULL);"); // 2: text
```

and the first row insert just fine with _id=0 but after that i get "PRIMARY KEY must be unique"

```
    Bookmark bookmark = new Bookmark(BOOKID, text);
    bookmarkDataAdapter.insert(bookmark);
```

**Comment by greenrobot-team** [comment]
Outdated. Closing. Please open a new issue if this is still relevant. -ut
