### ISSUE TITLE
One to many relation not generating setter

### ISSUE THREAD

**Issue by RoqueCampos** [greenrobot/greenDAO#206]
Hi,

I have a table with a one to many relation. The data comes from a json string and is deserialized with jackson;

```
 Entity profile = schema.addEntity("Profile");
profile.setTableName("profile");
Property categoriesToProfiles= category.addLongProperty("profile_id").notNull().getProperty();
        profile.addToMany(category, categoriesToProfiles).setName("UserCategories");
```

The problem here is that when I look at the generated Profile class, the setter for "UserCategories" is not generated. Only the getUserCategories method and resetUserCategories are generated.

Because of that, the deserialization with jackson does not include the user categories, and when trying to insert the data in the table I become a "detached from session" exception.

I solved this problem with a workaround: creating a simple setter in the keep methods section. But I don't know if that is a bug...

Thanks in advance.

**Comment by adauvalter** [comment]
There' s no an Issue. The generator generate only get and reset methods. If you want to set Categories to profile, you should to iterate throw the Categories list and set the profile Id, because this relationship performs by id.

**Comment by RoqueCampos** [comment]
Yes, I understand that, but in my case, I'm using the classes generated by green dao to deserialize json objects coming from the server using the jackson library. Those objects have lists of other things inside. If the setter method for this lists is missing, then the deserialization library does not deserialize them. And that is annoying.

But I solved adding it my own setter, no problem :)

**Comment by greenrobot-team** [comment]
Closing this then. -ut
