### ISSUE TITLE
Example with Date Column

### ISSUE THREAD

**Issue by NorbertSzydlowski** [greenrobot/greenDAO#213]
I have got database from file.

What is the best way to read Date and what is the shema for this?

**Comment by greenrobot-team** [comment]
For completeness, [see the new example](https://github.com/greenrobot/greenDAO/blob/V3.2.2/examples/DaoExample/src/main/java/org/greenrobot/greendao/example/Note.java).
Outdated. Closing. Please open a new issue if this is still relevant. -ut
