### ISSUE TITLE
Build schema from existing (model) classes.

### ISSUE THREAD

**Issue by TheolZacharopoulos** [greenrobot/greenDAO#215]
Hello fellas, 
I started with **greenDao** in my latest project, the situation is that I had already made my domain model (_A composite pattern that describes my domain_) to an external jar, in order to use it in every application, including, an API server, a Desktop app, an Android app and a web app.

I decided to use greenDao in the Android app but I needed to build the schema _from scratch_, so in order to reuse my domain model that was already in a jar file, I started building a tool **SchemaBuilder** which builds a schema, _Entities_, _relations_ etc from given classes. I use java's reflection capabilities in order to extract fields from the given classes and add them as Entity properties.

It's in a very early stages of course, but I am working on it and of course anyone can make a pull request in order to improve it :)

This is the github repo: https://github.com/TheolZacharopoulos/greenDao-schema-builder

**Comment by greenrobot-team** [comment]
Outdated, greenDAO 3 now uses annotations. Closing. -ut
