### ISSUE TITLE
Property 'xxx_xxx' is not part of xxxxDao

### ISSUE THREAD

**Issue by McPo** [greenrobot/greenDAO#216]
After upgrading from 1.3 to 2.0, Ive begun to receive the following error when running Robolectric tests.

```
de.greenrobot.dao.DaoException: Property 'contact_id' is not part of com.xxxxxxx.xxxxxx.xx.xxx.MessageDao@540f328f
    at de.greenrobot.dao.query.WhereCollector.checkProperty(WhereCollector.java:88)
    at de.greenrobot.dao.query.WhereCollector.checkCondition(WhereCollector.java:73)
    at de.greenrobot.dao.query.WhereCollector.add(WhereCollector.java:40)
    at de.greenrobot.dao.query.QueryBuilder.where(QueryBuilder.java:92)
    at com.xxxxxxx.xxxxxx.xx.XxxxXxxxxxx..deleteConversation(BaseMessage.java:76)
```

Ive doubled check that 'contact_id' is defined as a property of the generated MessageDao. There doesn't appear to be anything obvious. I can't provide complete code but hopefully the following snippets will help.

```
 Entity contact = schema.addEntity("Contact");
 contact.setSuperclass("com.xxxxxxx.xxxxxx.xx.BaseContact");
 contact.addIdProperty();
 //////

 Entity message = schema.addEntity("Message");
 message.setSuperclass("com.xxxxxxx.xxxxxx.xx.BaseMessage");
 message.addIdProperty();
 //////
 Property contactMsgProperty = message.addLongProperty("contact_id").notNull().getProperty();
 /////
 message.addToOne(contact, contactMsgProperty, "contact");
 contact.addToMany(message, contactMsgProperty, "messages");
```

```
public class MessageDao extends AbstractDao<Message, Long> {

    public static final String TABLENAME = "MESSAGE";

    /**
     * Properties of entity Message.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        ////////
        public final static Property Contact_id = new Property(2, long.class, "contact_id", false, "CONTACT_ID");
        ////////
    };
    ////////
}
```

```
public class ContactDao extends AbstractDao<Contact, Long> {

    public static final String TABLENAME = "CONTACT";

    /**
     * Properties of entity Contact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        ////////
    };
    ////////
}
```

```
public static void deleteConversation(String contactId) {
    Contact contact = Contact.loadByJID(contactId);
    List<Message> messages = DbManager.getMessageDao().queryBuilder()
            .where(MessageDao.Properties.Contact_id.eq(contact.getId())).list();
    for (Message m : messages) {
        m.delete();
    }
}
```

Im aware that the deleteConversation method could easily be improved.

**Comment by McPo** [comment]
Looking into this a bit more, it appears the issue is now occurring due to comparing a Long to a long.

https://github.com/greenrobot/greenDAO/blob/9f9422c22055d4f52b442e5a0500a19871b7a207/DaoCore/src/de/greenrobot/dao/query/WhereCollector.java#L81

The contact.id is Long while message.contact_id is a long (due to the NotNull).
Normally the solution to this would be to set the contact_id to NotNull as well (Although this seems redundant, surely an id should never be null?). However in my instance contact implements an interface where the Long is a generic, and you cant pass the primitive long as a generic. So it seems like I'll have to remove NotNull from messages, which is less than ideal.

In terms of a patch, what are the thoughts of having an Id capable of being null, should it be allowed in the first place? (Not that this will help my situation)

**Comment by McPo** [comment]
The issue appears to be with regards to the equality of the Properties object.

https://github.com/greenrobot/greenDAO/blob/9f9422c22055d4f52b442e5a0500a19871b7a207/DaoCore/src/de/greenrobot/dao/query/WhereCollector.java#L82

Changing
```
for (Property property2 : properties) {
    if (property == property2) {
        found = true;
        break;
    }
}
```

To
```
for (Property property2 : properties) {
    if (property.name.equals(property2.name)) {
        found = true;
        break;
    }
}
```
Resolves the issue and all my tests pass. However it appears this code hasnt changed since 2013. https://github.com/greenrobot/greenDAO/blame/f5ec02c96df49f30a038089ae0f126caf3c701fd/DaoCore/src/de/greenrobot/dao/query/QueryBuilder.java

I initially thought the issue with equality was that message.contact_id was a primitive long, while contact.id was a Long. This was due to the use of NotNull. I thought I had ran the tests with the removed NotNull and everything passed however since then, having re run the tests they are still failing with both contact.id and message.contact_id.

**Comment by asuzanne** [comment]
Thank you for this post. I have the same problem since I upgraded from 1.3 to 2.0.

How did you correct the WhereCollector class ? Have you imported the whole project to correct the class or add the dependency with gradle and just override WhereCollector.java ? 

When I try to override it, I have a multidex error and if I enable mutidexing, I get a lot of errors when I run my project so I don't really want to enable it.

Could you add this as a pull request ?

**Comment by McPo** [comment]
So I finally got some time to get a pull request done. https://github.com/greenrobot/greenDAO/pull/344

I also figured out that it was occurring due to abusing powermock, as such the two objects were no longer the same. If your using powermock yourself @asuzanne, Id advise to rewrite the test, but the PR has been made now.

**Comment by ShrutiD** [comment]
Im getting the same exception here,
Below is my code snippet: 

  //Fetch data of the folder and its children from File table
....
..
            else if (m_nParentFolderId != 0) {
                mObjParentFolder = mObjFileDao.queryBuilder()
                        **.where(Properties.Id.eq(m_nParentFolderId))** //i get the exception here. 
                        .list().get(0);
                mListOfFiles = mObjParentFolder.getFiles();

            }

Help!

**Comment by greenrobot-team** [comment]
Outdated. Closing. Please open a new issue if this is still relevant. -ut
