### ISSUE TITLE
Incorrect code generation for custom generic/array types.

### ISSUE THREAD

**Issue by dtx12** [greenrobot/greenDAO#219]
For example with pseudocode like this
`ent.addStringProperty("genericProperty").customType("package.Property<String>", "package.PropertyConverter");`

To generated file will be added this line:
`import package.Property<String>;`
The same true for arrays.

**Comment by deviant-studio** [comment]
This is due to how it parses class names. It relies on String.lastIndexOf('.') that harms any generic type.
Btw custom types is must have feature for storing collections of strings, ints etc. So at this moment main feature is broken :)

**Comment by deviant-studio** [comment]
There is also no way to create custom converter from anything to byte[] due to impossibility pass byte[] as generic param

**Comment by deviant-studio** [comment]
sorry for splitted commit ;)

**Comment by greenrobot-team** [comment]
Outdated, greenDAO 3 no longer uses the generator. Closing. Please open a new issue if this is still relevant. -ut
