### ISSUE TITLE
The method orderAsc(Property[]) in the type ToManyBase is not applicable for the arguments (Property)

### ISSUE THREAD

**Issue by xubuhang** [greenrobot/greenDAO#235]
![qq 20150921164447](https://cloud.githubusercontent.com/assets/4189632/9988115/55b0bb1c-6080-11e5-9e8e-9c25d06c08f9.png)
![qq 20150921164545](https://cloud.githubusercontent.com/assets/4189632/9988116/55b443c2-6080-11e5-8be7-06bfcfd7d861.png)

**Comment by greenrobot-team** [comment]
Outdated. Closing. Please open a new issue if this is still relevant. -ut
