### ISSUE TITLE
Conflict with OSMBonusPack

### ISSUE THREAD

**Issue by hoseinit** [greenrobot/greenDAO#244]
Hi
I am using omdroid and osmbonuspack in my project, when I add 
compile 'de.greenrobot:greendao:2.0.0'
in my build.gradle the project faces error:
 Caused by: java.lang.ClassNotFoundException: Didn't find class "org.osmdroid.bonuspack.mapsforge.GenericMapView" on path: DexPathList

**Comment by glideAndroid** [comment]
this is an integration issue of the other library, try looking in their
guids, this is not a GreenDao issue

On Wed, Oct 14, 2015 at 1:05 PM, Hosein Hamedi <notifications@github.com>
wrote:

> Hi
> I am using omdroid and osmbonuspack in my project, when I add
> compile 'de.greenrobot:greendao:2.0.0'
> in my build.gradle the project faces error:
> Caused by: java.lang.ClassNotFoundException: Didn't find class
> "org.osmdroid.bonuspack.mapsforge.GenericMapView" on path: DexPathList
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenrobot/greenDAO/issues/244>.
>



-- 

Have a great day.

Yishai Levenglick
Android-dev team
Glide Talk Ltd.
