### ISSUE TITLE
a noob question, if anyone is kind enough

### ISSUE THREAD

**Issue by AndreiD** [greenrobot/greenDAO#246]
noob question. sorry for putting it here.
![issue](https://cloud.githubusercontent.com/assets/542665/10509403/58dfd756-7335-11e5-8ec0-3dcc1cc1989d.jpg)

I added in the gradle file.

    compile 'de.greenrobot:greendao:2.0.0'
    compile 'de.greenrobot:greendao-generator:2.0.0'

I created this Class. I click run like in the picture, but nothing is saved.

Sorry again for asking here, but I couldn't make it work from the documentation.

**Comment by sevar83** [comment]
Try with this:
```
new DaoGenerator().generateAll(schema, "../models");
```
and remove the ```setDefaultJavaPackageDao()``` line.

**Comment by AndreiD** [comment]
Thank for answering. I removed the setDefaultJavaPackageDao. 

Exception in thread "main" java.io.IOException: ../models does not exist. This check is to prevent accidental file generation into a wrong path.... tried it with ../ too but it just writes it generates them but it doesn't.

**Comment by sevar83** [comment]
Then try with:
```
new DaoGenerator().generateAll(schema, "src/main/java");
setDefaultJavaPackageDao("com.classicharmony.rscanner2.models");
```

Notice that in your screenshot you wrote "model" but your actual folder name is "models".

**Comment by AndreiD** [comment]
after some tries I managed it to work with the full path written in the "src/main/java". after that I copy manually where I want and change the packagename/imports.... 
Thanks alot sevar83 :)
