### ISSUE TITLE
Using existing Database

### ISSUE THREAD

**Issue by daybson** [greenrobot/greenDAO#265]
I'm trying to use an existing database, and I made my model to match to all tables/columns of the database. On pure SQLite I used to copy the database from /assets to data/data/appdomain/databases/mydb.db, but I can't figure out how to do this on greenDAO. 
Following this answert - http://stackoverflow.com/questions/9630288/how-to-create-database-from-assets-in-android-using-greendao-orm-library gave me some start point, but greenDAO insists  on logging a message that some of my tables already exists.
In resume: 
How do I use my previous database (already populated with data) with greenDAO?
Thanks

**Comment by mohitsehgal** [comment]
Facing same issue, no solution
