### ISSUE TITLE
Auto Generate Entities and Dao classes

### ISSUE THREAD

**Issue by slott** [greenrobot/greenDAO#271]
This is not an issue per se - more a help to others on making this awesome lib even more awesome. Also I think it would make sense to have in the lib as an example for others to use.

In our project we have the GreenDao generator class in a separate java module and there is a Gradle genSources task to build the entities and dao classes. This is done using the inputs.file and outputs.dir so that Gradle can correctly determine if its UP-TO-DATE.

From our project Gradle script we have added
preBuild.dependsOn(":GreenDao:genSources")
gradle.beforeProject {
	preBuild.dependsOn(":GreenDao:genSources")
}

And that will then re-build everything if any change is detected in the dao generator file when the project is build.

With this we do not have to add the generated entities or the dao classes to our project.

I hope this will help others as much as it has helped me and my team.

**Comment by jogrimst** [comment]
@slott Thanks for the info! In which file are you adding this configuration?

**Comment by PeeJWeeJ** [comment]
Is this still applicable in 3.x?

**Comment by greenrobot-team** [comment]
@PeeJWeeJ Thanks for pointing this out. **3.x now auto-generates DAO classes** based on entity annotations, so this should no longer apply.

The only exception is if you are using multiple schemas, which is currently not supported in 3.x. -ut
