### ISSUE TITLE
QueryBuilder with First() method for returning one object

### ISSUE THREAD

**Issue by MBehtemam** [greenrobot/greenDAO#274]
in QueryBuilder we have list() methods that return list. so if user want one object must choose form the 

       List<Category> categories = cDao.queryBuilder().list();
       Category category = categories.get(0); //for getting first item

so why not 

     Category category = cDao.queryBuilder().first();   //for getting first item.

**Comment by MBehtemam** [comment]
Oh if find it `unique()` do the same that i want.

**Comment by lgrzywac** [comment]
I think `unique()` is not good enough. In my case `list()` returns 2 or more items. Using only `unique()` throws `DaoException`, so I think the solution would be adding `limit(1)` to query builder
```java
Category category = cDao.queryBuilder().limit(1).unique();
```
