### ISSUE TITLE
Suggest new Option

### ISSUE THREAD

**Issue by AladdinHZ** [greenrobot/greenDAO#278]
Hello guys, the library is very useful. But I have issue when using "in" query builder options for list having more than 120 value, it return to many arguments !!, which enforce me to make it native SQLITE query statement.

**Comment by glideAndroid** [comment]
this is not a library issue, it's an SQLite limitation, I suggest strongly
working with offsets and breaking your queries to more reasonable sizes.

I suggest also asking this on Stackoverflow with SQLite and GreenDao tags
instead of opening an issue here

**Comment by AladdinHZ** [comment]
Ok I will thanks for help.
