### ISSUE TITLE
Unit test with greendao

### ISSUE THREAD

**Issue by vodkhang** [greenrobot/greenDAO#292]
Hi all,

I am trying to setup unit test with greendao, and I tried both the sample test and the greendao generated test class. Both of them have the same issue that the in memory database is null. I think I need to set up with Mockito framework or something but I am not sure how to move forward with that. Any advice would be appreciated

**Comment by misrakli** [comment]
If the concrete problem is to get the right ´Context´ for initializing your database layer, you can use robolectrics, it provides the ´RuntimeEnvironment.application´ property which you can use in unit tests. I am going alreaday this way and it works.

**Comment by tir38** [comment]
So there is no way to unit test greenDao without using Robolectric to supply a mock `Context`?

**Comment by greenrobot-team** [comment]
Not sure if this helps, but the example app has an [example unit test](https://github.com/greenrobot/greenDAO/blob/master/examples/DaoExample/src/androidTest/java/org/greenrobot/greendao/example/NoteTest.java). -ut
