### ISSUE TITLE
How to use it with already exists Database

### ISSUE THREAD

**Issue by iballan** [greenrobot/greenDAO#300]
I have prefilled sqlite database i move it to the sdcard in some apps, and sometimes i keep it in assets folder.

so is it possible to provide the path of the database and start using greenDAO with it ? how can it be accomplished ?

**Comment by yishai-glide** [comment]
1. this is a question for stackoverflow.com with greedao tag
2. when opening the session you need to have something like this:

```
public void openDatabase(Context context) {
  // PATH_TO_DB can be a path to assets
  SqliteOpenHelper helper = new SqliteOpenHelper(context, PATH_TO_DB);
  SqliteDatabase db = helper.getWriteableDatabase();
  DaoMaster master = new DaoMaster(db);
  DaoSession session = master.newSession();
  // etc.
}
```
