### ISSUE TITLE
at de.greenrobot.dao.internal.DaoConfig.<init>(DaoConfig.java:94)

### ISSUE THREAD

**Issue by abc20899** [greenrobot/greenDAO#305]
my app is a launcher app , it is in /system/app/ directory. it crash

de.greenrobot.dao.DaoException: Could not init DAOConfig
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at de.greenrobot.dao.internal.DaoConfig.<init>(DaoConfig.java:94)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at de.greenrobot.dao.AbstractDaoMaster.registerDaoClass(AbstractDaoMaster.java:44)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at com.lingvr.db.DaoMaster.<init>(DaoMaster.java:69)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at com.lingvr.db.DaoUtil.getDaoMaster(DaoUtil.java:25)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at com.lingvr.db.DaoUtil.getDaoSession(DaoUtil.java:39)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at com.lingvr.db.DBHelper.getInstance(DBHelper.java:37)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at com.lingvr.net.AppManager$1.run(AppManager.java:124)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at java.lang.Thread.run(Thread.java:841)
02-26 18:37:12.020: E/AndroidRuntime(6682): Caused by: java.lang.NoSuchFieldException: TABLENAME
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at java.lang.Class.getField(Class.java:724)
02-26 18:37:12.020: E/AndroidRuntime(6682): 	at de.greenrobot.dao.internal.DaoConfig.<init>(

**Comment by yishai-glide** [comment]
I just got this as well.
could this be a simple issue of obfuscation since this line relies on reflection, I fear this might be happening due to bad proguard rules but it doesn't make me understand how this happens only on some devices and builds and not on others.

source of crash:

```
    public DaoConfig(SQLiteDatabase db, Class<? extends AbstractDao<?, ?>> daoClass) {
        this.db = db;
        try {
            this.tablename = (String) daoClass.getField("TABLENAME").get(null);
            Property[] properties = reflectProperties(daoClass);
            this.properties = properties;

            allColumns = new String[properties.length];

            List<String> pkColumnList = new ArrayList<String>();
            List<String> nonPkColumnList = new ArrayList<String>();
            Property lastPkProperty = null;
            for (int i = 0; i < properties.length; i++) {
                Property property = properties[i];
                String name = property.columnName;
                allColumns[i] = name;
                if (property.primaryKey) {
                    pkColumnList.add(name);
                    lastPkProperty = property;
                } else {
                    nonPkColumnList.add(name);
                }
            }
            String[] nonPkColumnsArray = new String[nonPkColumnList.size()];
            nonPkColumns = nonPkColumnList.toArray(nonPkColumnsArray);
            String[] pkColumnsArray = new String[pkColumnList.size()];
            pkColumns = pkColumnList.toArray(pkColumnsArray);

            pkProperty = pkColumns.length == 1 ? lastPkProperty : null;
            statements = new TableStatements(db, tablename, allColumns, pkColumns);

            if (pkProperty != null) {
                Class<?> type = pkProperty.type;
                keyIsNumeric = type.equals(long.class) || type.equals(Long.class) || type.equals(int.class)
                        || type.equals(Integer.class) || type.equals(short.class) || type.equals(Short.class)
                        || type.equals(byte.class) || type.equals(Byte.class);
            } else {
                keyIsNumeric = false;
            }

        } catch (Exception e) {
            throw new DaoException("Could not init DAOConfig", e);
        }
    }

```

**Comment by yishai-glide** [comment]
#188

**Comment by greenrobot-team** [comment]
Yeap, looks very much like those are related. So tracking this in #188. -ut
