### ISSUE TITLE
Allow "order" and "where" on a toMany relation list 

### ISSUE THREAD

**Issue by marsie** [greenrobot/greenDAO#308]
Example: If i've a State -> City toMany relation. With greenDAO I can get a city list with `State.getCityList()`
It would be nice if i could add `.where` and `.order` to get a sorted, filtered list.
Or maybe you could add a function to get the QueryBuilder object. Something like `State.getCityQB().where(...).list()`

**Comment by greenrobot-team** [comment]
With greenDAO 3 you can use an `@OrderBy` annotation on a `@ToMany` property. See the [documentation about relations](http://greenrobot.org/greendao/documentation/relations/).

Outdated. Closing. Please open a new issue if this is still relevant. -ut
