### ISSUE TITLE
.List() method on QueryBuilder now returns immutable list

### ISSUE THREAD

**Issue by michel-t-86** [greenrobot/greenDAO#312]
It seems that the `List()` method on `QueryBuilder` returns an immutable list since upgrade from 2.0.0 to 2.1.0.

I used to be able to add to the List that was returned but now it throws an operation not supported.

It looks like the abstract List class is the implementation provided by google apis intead of `java.util.List;`

**Comment by ems305** [comment]
I ran into this issue as well. It looks like it was fixed in cfe1834 and released in the 2.2 version.
