### ISSUE TITLE
A garbled problem when add javaDoc in chinese

### ISSUE THREAD

**Issue by lonelyleaf** [greenrobot/greenDAO#313]
when I add entity using encoding UTF-8:
```
  Entity areaDto = schema.addEntity("AreaDto");
  areaDto.setJavaDoc("区域信息DTO");
  areaDto.addStringProperty("areaId").javaDocField("区域编号").unique();
```
the generated entity source code(also encoding utf-8) is garbled and show like this:
```
 /**
 * 鍖哄煙淇℃伅DTO
 */
public class AreaDto {

    /**
     * 鍖哄煙缂栧彿
     */
    private String areaId;
    ........
```

But when I change the encoding of generator source coding using GBK,it works all right:
```
/**
 * 区域信息DTO
 */
public class AreaDto {

    /**
     * 区域编号
     */
    private String areaId;
```

Maybe because I'm using windows in chinese and you generate code using the system default encoding??

Can you fix this bug or adding some extra support for encoding.Using multiple encoding in a single project is really an agony.

**Comment by zjq1012** [comment]
I met the same problem。

**Comment by hotstu** [comment]
just add this to your build.gradle file 

`tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}`

**Comment by lonelyleaf** [comment]
@hotstu thank you!it works!
