### ISSUE TITLE
Assets DB file

### ISSUE THREAD

**Issue by gzfgeh** [greenrobot/greenDAO#318]
Now, My app have a db file in assets, what can i do operate db file use greendao? 
thank you!

**Comment by yishai-glide** [comment]
1. this is a question for [Stackoverflow](http://stackoverflow.com/questions/tagged/greendao)
2. when creating an `SqliteOpenHelper` you need to pass a path to the DB file, just get the path for the assets file and use it

**Comment by gzfgeh** [comment]
I have see the all file ,and i Know i can get sqliteOpenHelper from the db file in the assets, but how can i use greendao to operate sqliteOpenHelper?

**Comment by gzfgeh** [comment]
I use greendao create db file A and then i copy assets db file B to overwrite A,(the db file name is same), when i use greendao operate db file, the erroe is  the table:brand"  is already exists.(the brand is the table name), how can i do?

**Comment by greenrobot-team** [comment]
Not sure what your actual state is, but you can start by overriding your `DaoMaster.OpenHelper`.

Or you can have a look at [android-sqlite-asset-helper](https://github.com/jgilfelt/android-sqlite-asset-helper) which allows to use databases you ship with the app in your assests folder.

-ut
