### ISSUE TITLE
cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // a

### ISSUE THREAD

**Issue by JWBlueLiu** [greenrobot/greenDAO#321]
cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // a
this is a mistake
cursor.getInt(offset + 1) will return 0
we don't need to judge
but
cursor.isNull(offset + 1) ? "" : cursor.getString(offset + 1), // a
may helpful

in general 
cursor.getXXX(offset + 1) is enough

**Comment by greenrobot-team** [comment]
If I understand correctly this is to differentiate between there being no value (`null`) stored for that column or actually `0`.

An example:
```
id | intvalue
--------------
0  | null
1  | 0
```
