### ISSUE TITLE
GreenDAO Generator Error Gradle 2.0.0

### ISSUE THREAD

**Issue by aaronat1** [greenrobot/greenDAO#331]
I have updated my Android Studio. Now when I run my DAOGeneator I receive this error:  Error:Gradle: A problem occurred configuring root project 'curiocity-app'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.0.0.
     Required by:
         :curiocity-app:unspecified
      > No cached version of com.android.tools.build:gradle:2.0.0 available for offline mode.

I have activated the offline mode.

Regards

**Comment by 601367322** [comment]
do not include generator

**Comment by aaronat1** [comment]
Sorry, I do not understand you. I need to run Generator modulo to create/update my dao.

**Comment by xjliao** [comment]
Edit Run/Debug Configurations and remove Option:Before launch: Make Project, Activate tool window, Make it empty. Run main method again. It will work well.

**Comment by 601367322** [comment]
My English is not good.
'curiocity-app' do not need compile project Generator module
but you can create dao files to 'curiocity-app'
like this

`new DaoGenerator().generateAll(schema, "curiocity-app/src/main/java-gen");`

**Comment by LiHanGuang** [comment]
@aaronat1 

>
No cached version of com.android.tools.build:gradle:2.0.0 available for offline mode.

**offline mode**?   change your android studio2.0's **setting**.

Hope it help you.

**Comment by aaronat1** [comment]
I have unchecked de offline mode. This is not the problem.

**Comment by aaronat1** [comment]
This is the solutiuon:

Edit Run/Debug Configurations and remove Option:Before launch: Make Project, Activate tool window, Make it empty. Run main method again. It will work well.

Thanks xjliao!!

**Comment by Bigmercu** [comment]
it's wrong in my IDE too,do you fix it? @aaronat1

**Comment by Bigmercu** [comment]
# I fix the error of my IDE

open  Setting->compiler->Command-line Options   
delete the  '--offline'

**Comment by greenrobot-team** [comment]
Guess this is fixed then and is not a greenDAO issue.
