### ISSUE TITLE
Method duplicated when already defined on //KEEP METHODS region

### ISSUE THREAD

**Issue by daybson** [greenrobot/greenDAO#332]
I have some gets/sets in my bean class "People", like `getSecurityNumber, getPhone`, etc.. This fields are encrypted before be stored on database, and decrypted when I need to show them on UI.

`txt.setText(cryptAgent.Decrypt(people.getPhone()));`

To avoid to forget to use an cript object to decrypt the information before show it, I defined the getPhone on the //KEEP FIELDS region of my People class. But when I need change something on my entity and recriate the model, greenDAO creates a new getPhone() outside `//KEEP METHODS` region, duplicating the method.

Is possible implement some fix or changing to make greenDAO look for the method on `//KEEP METHODS` before, and if it's found, do not recreate it? This could be very usefull for a large set of situations involving validations or formatation before storing/showing the information.

Thanks.

**Comment by greenrobot-team** [comment]
This should no longer be an issue with greenDAO 3.0 and the new `@Keep`annotation. Your modified methods should be properly kept then.
