### ISSUE TITLE
When I create database by helper.getWritableDatabase() Error:is   java.lang.NullPointerException

### ISSUE THREAD

**Issue by zhangyubao** [greenrobot/greenDAO#337]
public static DaoMaster getDaoMaster() {
        if (daoMaster == null) {
            DaoMaster.OpenHelper helper = new DaoMaster.DevOpenHelper(mContext, DB_NAME, null);
            daoMaster = new DaoMaster(helper.getWritableDatabase());
            //helper.getWritableDatabase() return null
        }
        return daoMaster;
    }

**Comment by zhangyubao** [comment]
it's my fault, the context is not right ! sorry !!!!

**Comment by LuckyPerry** [comment]
怎么解决的兄弟。我也遇到了，代码照着api写的，但是DaoMaster都是null
