### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException at DaoConfig.java:117

### ISSUE THREAD

**Issue by xixigeek** [greenrobot/greenDAO#338]
the code in Daoconfig.java:117 is like this
```java
       Property[] properties = new Property[propertyList.size()];

        for (Property property : propertyList) {
            if (properties[property.ordinal] != null) { //line 117
                throw new DaoException("Duplicate property ordinals");
            }
            properties[property.ordinal] = property;
        }
```

This code maybe ok In most of the time。But it dont be safe in our app which millions of users pour attention to.

Pls fix it or just add sth like this `if(property.ordinal < propertyList.size()){//...}`

I like greenDAO,I hope our users like this too~

the url is crash log preview（you can copy this into your browser & open it）
[http://img.blog.csdn.net/20160506140914085](url)

**Comment by greenrobot-team** [comment]
Did you modify the generated Dao class in some way? The auto-generated properties should be numbered starting from `0` up to the `count - 1` of all properties of a Dao.

For example:
```java
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ABCDEF_ENTITY".
*/
public class AbcdefEntityDao extends AbstractDao<AbcdefEntity, Long> {
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property A = new Property(1, Integer.class, "a", false, "A");
        public final static Property B = new Property(2, Integer.class, "b", false, "B");
        public final static Property C = new Property(3, Integer.class, "c", false, "C");
    };
...
}
```

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by onomated** [comment]
For those landing here by searching Google.  This answer on SO fixes the problem:  https://stackoverflow.com/a/56750270

**Comment by greenrobot-team** [comment]
Updated ProGuard rules are also part of the README.
https://github.com/greenrobot/greenDAO#r8-proguard
