### ISSUE TITLE
Delete By WhereCondition

### ISSUE THREAD

**Issue by chrisjenx** [greenrobot/greenDAO#34]
Addition delete by's would be a nice addition.

deleteByProperty(WhereCondition cond);
deleteByRaw(String whereCond);

We want to clear data out of the database using " WHERE fieldname < datetime('now')"

**Comment by jemshit** [comment]
Is it enough to call `detachAll()` on only `daoObject` that deleteQuery has been executed on? Instead of `daoSesson.clear()` ?

**Comment by greenrobot-team** [comment]
@jemshit If only that entity was affected that should work, it will clear the identity cache only for that entity. `daoSesson.clear()` does it for all entities. Just have a look at the (generated) code. -ut

**Comment by kpradeepkumarreddy** [comment]
Can i use the following code to delete all rows from the table

DeleteQuery<Table> tableDeleteQuery = tableDao.queryBuilder().buildDelete();
tableDeleteQuery .executeDeleteWithoutDetachingEntities();
