### ISSUE TITLE
Insert Error ContentProvider

### ISSUE THREAD

**Issue by madouik** [greenrobot/greenDAO#340]
Hello, 
I'm trying greendao-encryption with generation of contentProvider  i have error on contentProviderClass 
id = getDatabase().insert(TABLENAME, null, values);
The insert is not found

**Comment by greenrobot-team** [comment]
I assume you are using a build from the `encryption` branch? The value returned then should be [the row id or -1](https://github.com/sqlcipher/android-database-sqlcipher/blob/v3.5.1/src/net/sqlcipher/database/SQLiteStatement.java#L66-L75) if the insert failed. If you get -1 the insert failed for some reason.

Note that you might try using the [in-development greenDAO 3.0 with encryption](https://github.com/greenrobot/greenDAO/tree/v3-encryption).

-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by svetlin** [comment]
I guess what the OP meant was that `getDatabase()` returns a `Database`, not a `SQLiteDatabase` in the generated ContentProvider therefore no CRUD operations are possible.

Verified this is the case on org.greenrobot:greendao-encryption:2.2.1.

**Comment by greenrobot-team** [comment]
@svetlin Thanks, now I get it. For this case you may use `getDatabase().getRawDatabase()` and cast it appropriately (for example `SQLiteDatabase` by default). -ut

**Comment by svetlin** [comment]
This seems to probably work on 3.x. In my case of 2.x I had to manually change the generated `ContentProvider` like that:
```Java    
protected SQLiteDatabase getDatabase() {
        if (daoSession == null) {
            throw new IllegalStateException("DaoSession must be set during content provider is active");
        }
        final Database database = daoSession.getDatabase();
        return ((StandardDatabase) database).getSQLiteDatabase();
    }
}
```
Does provider generation work out-of-the-box on 3.x? Are there plans to fix the generation on 2.x?

**Comment by greenrobot-team** [comment]
@svetlin If I remember this was always experimental. Not sure we will put more work into it as simply using the greenDAO APIs is much easier. And if users need to (like for exposing data to other apps) they can write a ContentProvider themselves. -ut

**Comment by svetlin** [comment]
Agreed (and I've written custom content providers). But, unlike a provider, greenDAO does not provide IPC AFAIK? So if the app runs in more than one process, one needs to roll out a custom IPC solution to access the sole db.
Anyway, thanks for the help and info, really appreciated!
