### ISSUE TITLE
Cannot resolve symbol 'AbstractDao' in entity class in javaDoc

### ISSUE THREAD

**Issue by sosite** [greenrobot/greenDAO#347]
`delete()`, `update()` and `refresh()` methods contains javaDoc that give us unwanted editor error:
`Cannot resolve symbol 'AbstractDao'`.

I suggest adding `import de.greenrobot.dao.AbstractDao` to generated entity class or optionally replace:
```
/** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
```
to:
```
/** Convenient call for {@link de.greenrobot.dao.AbstractDao#delete(Object)}. Entity must attached to an entity context. */
```

**Comment by greenrobot-team** [comment]
[Looks like this will be fixed](https://github.com/greenrobot/greenDAO/blob/v3/DaoGenerator/src-template/standard/entity.ftl#L346-L373) in the upcoming 3.0 release. Thanks for reporting! -ut
