### ISSUE TITLE
How to search boolean column in where clause

### ISSUE THREAD

**Issue by vanjaraparas** [greenrobot/greenDAO#351]
In Greendao, how we can search for boolean column is true or false in where clause

Give me one example for the same

**Comment by greenrobot-team** [comment]
According to the [Queries documentation](http://greenrobot.org/greendao/documentation/queries/) Booleans are mapped to Integer values `0 (false)` and `1 (true)`.

So you should probably do something like:
```java
yourDao.queryBuilder()
    .where(YourDao.Properties.BooleanProperty.eq(1)) // boolean should be true
    .list();
```

-ut

**Comment by greenrobot-team** [comment]
No response. Closing.
