### ISSUE TITLE
How to do with List<String> in an Entity class when using GreenDao 3

### ISSUE THREAD

**Issue by boybeak** [greenrobot/greenDAO#363]
My Entity class as below:
```java
@Entity
public class DiscoveryItem implements Serializable {
    @Id
    public long id;
    public String name;
    public String icon;
    public String link;
    @ToMany
    public List<String> linkArgs;
    public int order;
    public boolean isShow;
    public boolean allowShare;
}
```
But error happened when compile.The error as below:
```java
Error:Execution failed for task ':app:greendao'.
> Can't add field `Variable(type=VariableType(name=java.util.List, isPrimitive=false, originalName=List<String>, typeArguments=[VariableType(name=String, isPrimitive=false, originalName=String, typeArguments=null)]), name=linkArgs)` for entity DiscoveryItem due to: Unsupported type java.util.List


```
I didn't found any solution at [GreenDAO 3](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/)

**Comment by greenrobot-team** [comment]
Have a look at the [relation annotations section](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#Relation_annotations_ToOne_ToMany_etc).

If you add the `@ToMany` annotation, you also need to add one of the three options:
- a `referencedJoinProperty`
- or `joinProperties` parameter on `@ToMany`,
- or an additional `@JoinEntity` annotation.

Look at [my comment here](https://github.com/greenrobot/greenDAO/issues/364#issuecomment-233245698) for code examples.

-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by kmkole86** [comment]
Relation toMany is useful when you have a list of your not primitive object, that you can declare like entity that have its own id etc etc etc, and make list of entities (with toMeny). By doing that greenDao makes another table in the base for you new entity with the foreign key of the base entity that contains list. When you have list of primitive type the only way to do is to make converter that converts List<Strings> into one of the primitive types that greenDao works naturally. You have to do something like this `
import org.greenrobot.greendao.converter.PropertyConverter;
import java.util.Arrays;
import java.util.List;

/**
 * DOLE SQLITE breeeeeee!!!
*i choosed to convert List<Strings> into one string
*that is going to be saved in database, and vice versa 
 */

public class GreenConverter implements PropertyConverter<List<String>, String> {
    @Override
    public List<String> convertToEntityProperty(String databaseValue) {
        if (databaseValue == null) {
            return null;
        }
        else {
            List<String> lista = Arrays.asList(databaseValue.split(","));
            return lista;
        }
    }

    @Override
    public String convertToDatabaseValue(List<String> entityProperty) {
        if(entityProperty==null){
            return null;
        }
        else{
            StringBuilder sb= new StringBuilder();
            for(String link:entityProperty){
                sb.append(link);
                sb.append(",");
            }
            return sb.toString();
        }
    }
}`

now above all the properties that are List<String> you have to put 
@Convert(converter=yourconverterclass.class, columnType = String.class)

`@Entity
public class ShipEntry {

    @Id(autoincrement = true)
    private long ship_id;
    private String name;
    private String model;
    private String manufacturer;
    private String starship_class;

    **@Convert(converter = GreenConverter.class, columnType = String.class)
    private List<String> pilots;

    @Convert(converter = GreenConverter.class, columnType = String.class)
    private List<String> films ;**

    private String created;`

you can create Converter as a inner class of entitiy, and in that case it has to be declared as static
that is the only way i have found, but the bad side is that you can not use property that you are converting into query. I hope this helps
