### ISSUE TITLE
setConstructors(false) not available in greenDAO v3

### ISSUE THREAD

**Issue by 9und70** [greenrobot/greenDAO#373]
In the Generator-Project, it was possible to skip generation of constructors.
There is no appropriate annotation.
I've one Entity with more than 254 properties that ends up in a "too many parameters"-Java-Error

**Comment by greenrobot-team** [comment]
This will be available with the `3.1.0` release. You can then add an annotation to your entity so no constructor will be generated.

```java
@Entity(generateConstructors = false)
public class Note {
}
```
