### ISSUE TITLE
 Caused by: org.greenrobot.greendao.DaoException: Entity is detached from DAO context

### ISSUE THREAD

**Issue by pngfi** [greenrobot/greenDAO#379]
I have a entity Task ,it has a to many relation (1:N) to the Entity Record
I want to transfer the entity Task by intent.
so I do like this.
```java
public class Task implements Parcelable{}

List<Task> tasks = DBManager.getInstance(getActivity()).getTaskDao().loadAll();

Intent i = new Intent(getActivity(), TaskDetailActivity.class);
               Task task = mTasks.get(position);
               i.putExtra(Constant.KEY_EXTRA_TASK,task);
               startActivity(i);
```

Then I call the getRecordList of Task ,but get the error above.
Any way to solve ?  Thans in advance.

**Comment by greenrobot-team** [comment]
Check out #4 (pass the id and query again, or ensure the dao session is re-set when deserializing). -ut
