### ISSUE TITLE
Greendao Where Query issue

### ISSUE THREAD

**Issue by vanjaraparas** [greenrobot/greenDAO#381]
How to build where query for comparing String column value with ignoring case 

OR 

How to build where query for comparing String column value convert to lowercase first

**Comment by greenrobot-team** [comment]
You may want to [fall back to a raw SQLite query](http://greenrobot.org/greendao/documentation/queries/#Raw_queries). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
