### ISSUE TITLE
GreenDAO3.0  getWritableDB() in DaoMaster.

### ISSUE THREAD

**Issue by MrLiInGitHub** [greenrobot/greenDAO#382]
I am using the GreenDAO 3.0, when i Make Project, something wrong with newDevSession() in DaoMaster class. The new function should be getWritableDatabase() but it keeps generating getWritableDb() the old one, how to solve it?

P.S. I am using greendao-encryption instead of greendao.

```java
/**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
            Database db = new DevOpenHelper(context, name).getWritableDb();
            DaoMaster daoMaster = new DaoMaster(db);
            return daoMaster.newSession();
    }
```

**Comment by greenrobot-team** [comment]
`getWritableDb()` is just a wrapper for `getWritableDatabase()` to abstract the type of the database away. Is that not what is expected?

```java
    /**
     * Like {@link #getWritableDatabase()}, but returns a greenDAO abstraction of the database.
     * The backing DB is an standard {@link SQLiteDatabase}.
     */
    public Database getWritableDb() {
        return wrap(getWritableDatabase());
    }
```
-ut

**Comment by MrLiInGitHub** [comment]
No, the truth is the code I posted before is auto-generated. And there is no getWritableDb() method, only getWritableDatabase() makes sense. So I am wondering if something wrong I have done.  If I replaced the greendao-encryption 3.0 with greendao 3.0, then everything is okay. But I want an encrypted database, so what is the solution?

P.S. I have done nothing but Make Project, after the Daos and DaoMaster are generated, there is something wrong.

**Comment by greenrobot-team** [comment]
greenDAO 3.0 has encryption support. As far as I know there is no need to use the `greendao-encryption` branch any longer. See [the example app](https://github.com/greenrobot/greenDAO/blob/master/DaoExample/src/main/java/org/greenrobot/greendao/example/App.java). -ut

**Comment by MrLiInGitHub** [comment]
Problem solved. Thanks a lot!!!
