### ISSUE TITLE
Use a String as primaryKey

### ISSUE THREAD

**Issue by ChristianLJ** [greenrobot/greenDAO#388]
In version 2.0 of GreenDao i had a table with a primary key called elementID which is a String. It was configured in the generator like this:
```java
element.addStringProperty("elementID").primaryKey();
```
When updating to GreenDao 3.1 i get the following error when building the project:
```
Error:Execution failed for task ':app:greendao'.
> Can't add field `Variable(type=VariableType(name=java.lang.String, isPrimitive=false, originalName=String, typeArguments=null), name=elementID)` for entity Element due to: Unsupported type java.lang.String
```
I have tried changing the attributes for the property like this with no change:
```java
 @Index(unique = true)
 @NotNull
 @Id
 @Unique
 private String elementID;
```
Am i doing something wrong or does GreenDao 3.1 not support Strings as primaryKeys?

**Comment by greenrobot-team** [comment]
Just noting: still only [Long is supported for primary keys](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#greenDAO_3_Entities_and_Annotations). I suppose what [was true for greenDAO 2](http://greenrobot.org/greendao/documentation/modelling-entities/#Properties_and_primary_keys) still applies to v3.

However, I could get it working with:
```java
@Entity
public class ExampleEntity {
    @Id
    private String id;
}
```

Do you maybe have an explicit `import java.lang.String;`? Try to remove it.

-ut

**Comment by ChristianLJ** [comment]
Well, the fix was quit simple. 
As suggested i removed the explicit import `import java.lang.String;`. Afterwards everything worked as expected.

**Comment by greenrobot-team** [comment]
Alright, with the next plugin update it should be possible to explicitly import Java base type wrappers and `String`. -ut
