### ISSUE TITLE
Migrating to GreenDao 3: Keep fields not annotated with @Transient

### ISSUE THREAD

**Issue by brazberry** [greenrobot/greenDAO#389]
I'm in the process of migrating from GreenDao 2 to 3. There are a few annoying incompatibilities so far. For example, GreenDao no longer allows wildcard imports and requires fully qualified names for inner classes. Now I'm starting to run into issues with all the fields in the // keep fields section being added to my schema, so I think I need to manually annotate them all with @Transient. 

Is there a more detailed transition guide that I missed? I think I followed along the process in http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations by first updating my model generator project and rerunning it and then adding the new gradle plugin and running that. However while the newly generated classes have some annotations such as @Entity, @Id, and @Generated on the constructors, they still contain the KEEP section comments. Also all the generated getters and setters are still there, but aren't annotated.

**Comment by greenrobot-team** [comment]
No, from what I can see by looking at the generator code keep sections are currently just copied 1 to 1. So yes, for now you will have to annotate with `@Transient` manually.

Thanks for reporting! -ut

**Comment by greenrobot-team** [comment]
In the next release (likely `3.2.0`) fields inside the `KEEP FIELDS` section will be annotated with `@Transient` if they are not already annotated with `@Transient`, have the `transient` or `static` modifier.

Let us know how that works out for you. -ut
