### ISSUE TITLE
Make it possible to truncate all tables with a single function call

### ISSUE THREAD

**Issue by ChristianLJ** [greenrobot/greenDAO#392]
When the user logs out of our app we want to truncate all tables in the database without deleting the tables. 

I can't find a function that makes this possible so therefore i am calling `deleteAll()` on all tables when the user logs out.
This method is trivial and can, when adding new tables or deleting existing, cause us to forget to call `deleteAll()` on the Dao.

It would be nice to have a function that truncates all tables.

**Comment by Expectro** [comment]
Hi, 

You can delete and recreate all tables:

mDaoMaster.dropAllTables(mDaoSession.getDatabase(), true);
mDaoMaster.createAllTables(mDaoSession.getDatabase(), true);

Regards

**Comment by ChristianLJ** [comment]
@Expectro: That seems to do the trick. Thank you.
