### ISSUE TITLE
cannot find "targetGenDirTest"

### ISSUE THREAD

**Issue by ferdeli** [greenrobot/greenDAO#399]
I was trying to use targetGenDirTest in my build.gradle, but got following error:
Error:Could not find method targetGenDirTest() for arguments [src/test/java"] on project ':app' of type org.gradle.api.Project.

**Comment by greenrobot-team** [comment]
Whoops, docs are wrong. Thanks! [Fixed it](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#Gradle_Plugin_Configuration).

It is called `targetGenDirTests`.

-ut
