### ISSUE TITLE
Add logging support

### ISSUE THREAD

**Issue by crazecoder** [greenrobot/greenDAO#405]
How to print the SQL statement in the logcat?

**Comment by greenrobot-team** [comment]
As far as I know there is no built-in logging support.

However, you could subclass for example `StandardDatabase` and add logging statements there. Then use your custom `Database` implementation with your own `DatabaseOpenHelper` to construct `DaoMaster`. -ut

**Comment by greenrobot-team** [comment]
This is tracked with #3. -ut
