### ISSUE TITLE
Transaction Management

### ISSUE THREAD

**Issue by qq272936993** [greenrobot/greenDAO#406]
In the source code, delete / update / insert transaction management operations have in fact a business operation may have multiple database operations, should share a transaction operating multiple databases. Whether the transaction should be completed by the user or let the user control the complex transaction switch it?

**Comment by greenrobot-team** [comment]
If I understand correctly, greenDAO is optimized to work with a single database. If you are looking to work with multiple databases you are on your own. -ut
