### ISSUE TITLE
GreenDao :the Primary Key must be long?

### ISSUE THREAD

**Issue by Bertkiing** [greenrobot/greenDAO#408]
Firstly ,I just use  the greenDao a few time ,but I have some problem which confuse me.  StackOverflow 's answer give a message:

**Current primary key (PK) restrictions: Currently, entities must have a long or Long property as their primary key. This is recommended practice for Android and SQLite. greenDAO is prepared to handle any primary key scenario in the future, but not everything is implemented completely yet. To work around this issue, you can use a long primary key and use an unique index for the intended “key” properties.**

Then I  see the issues : the String also can as a primary key,just delete the  import String.
ohhh.. Please give me  a  final answer:[
Long ,Short ,Int ,String }
ps: I know  the long may be the best ,but some time I want to use the other.

**Comment by greenrobot-team** [comment]
As the docs say just use `Long` for your primary key. Then add an additional field annotated with `@Index(unique = true)`. See [the docs](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#Indexing_annotationsIndex_and_Unique) for an example.

Also #388.
