### ISSUE TITLE
Issue: In Samsung Phones for db field issue

### ISSUE THREAD

**Issue by deepeshalways** [greenrobot/greenDAO#411]
I am facing this issue in version : org.greenrobot:greendao-encryption:2.2.2

On Samsung J5 after Db Table Changes in the DaoGenerator on the same schema(regeneration of the tables done) , after uninstalling the app installed the app again in my samsung phone  which still detects the old db which dont have the field name which i added, why so.

**Comment by greenrobot-team** [comment]
Are you on Android 6.x? If yes, your apps database file might get restored by the new [full app backup](https://developer.android.com/training/backup/autosyncapi.html).

On a side note: you should be able to use greenDAO 3.x, it has now built-in support for encryption.
-ut

**Comment by deepeshalways** [comment]
Thanks it resolved my issue
