### ISSUE TITLE
Gradle plugin src code?

### ISSUE THREAD

**Issue by Macarse** [greenrobot/greenDAO#412]
Where is the Gradle plugin source code?

**Comment by greenrobot-team** [comment]
Soon, we still are doing fixes and want to clean it up a little before we show it to anybody. 😀 -ut

**Comment by Macarse** [comment]
@greenrobot @greenrobot-team any update?

**Comment by skrzyneckik** [comment]
@greenrobot-team @greenrobot any update?

**Comment by Macarse** [comment]
```
23:56:17.181 [INFO] [system.out] greenDAO Generator
23:56:17.181 [INFO] [system.out] Copyright 2011-2016 Markus Junginger, greenrobot.de. Licensed under GPL V3.
23:56:17.181 [INFO] [system.out] This program comes with ABSOLUTELY NO WARRANTY
```

GPL...

**Comment by jaredsburrows** [comment]
@greenrobot-team Can the source code please be released? I have a few custom commits on green dao core as well as the generator that is not compatible with the plugin.

**Comment by skrzyneckik** [comment]
@jaredsburrows it doesn't look like anybody will ever answer us.

**Comment by raphaelm** [comment]
Any news here?

**Comment by raphaelm** [comment]
Please, rather release a non-polished release than not releasing it at all :( This way, I can't use greenDAO in a project.

**Comment by mtotschnig** [comment]
This is quite disappointing if you invest in using GreenDAO under the assumption of it being fully open source, and then stumble upon the gradle plugin source code not being available. I think as long as this is the case, this should be mentioned under http://greenrobot.org/greendao/documentation/faq/ .

**Comment by jaredsburrows** [comment]
@Macarse @mtotschnig Maybe it is time to switch to Android's Room: https://developer.android.com/topic/libraries/architecture/room.html.

**Comment by skrzyneckik** [comment]
@jaredsburrows I think we should wait until Room is ready - it's still in alpha phase

**Comment by jaredsburrows** [comment]
@skrzyneckik Yeah.

**Comment by brazeel** [comment]
So it's still not released yet.  :(

**Comment by enbandari** [comment]
Waiting...

**Comment by blindpirate** [comment]
Waiting forever... it's hard to troubleshoot some problems without source code..

**Comment by greenrobot-team** [comment]
The team is currently focused on https://github.com/objectbox/. It's still hard to find time for greenDAO. I hope at least the source code will be made available to make greenDAO more community-maintained. Because chances are we won't do much work on it in the foreseeable future. -ut

**Comment by fantasyRqg** [comment]
Hope the source public ASAP , we are facing `@Generated hash change` problem

**Comment by noproxy** [comment]
@greenrobot @greenrobot-team No updates for three years?  So many issues cannot fixed without gradle plugin source, such as kotlin compatible #395

**Comment by qaz5506811123** [comment]
@greenrobot @greenrobot-team Can't provide source code for so long?

**Comment by yfappest** [comment]
@greenrobot  @greenrobot-team any update?

**Comment by 4332weizi** [comment]
6 years have passed

**Comment by blundell** [comment]
Where's the source yo! :-)

**Comment by linsui** [comment]
Since greendao is not maintained anymore, could you please release the source code? :)

**Comment by Strubbl** [comment]
in 2024, what is a FOSS alternative which could be used instead of greendao?

edit: found a nice list: https://github.com/breezy-weather/breezy-weather/issues/677

**Comment by greenrobot-team** [comment]
The greenDAO plugin source code is now [available on GitHub](https://github.com/greenrobot/greenDAO-plugin)!
