### ISSUE TITLE
how can I include a map in the generator?

### ISSUE THREAD

**Issue by georgeworkhard** [greenrobot/greenDAO#417]
hello, I want to use a HashMap in the dto (e.g. private Map<String, String> map;), could u pls show me how to include this Map property in the generator?
thx in advance

**Comment by greenrobot-team** [comment]
I do not think maps are supported. Except if you [specify a converter](https://github.com/greenrobot/greenDAO/issues/366#issuecomment-233240580) to map it to one of the SQLite data types.

Or create entities for each map entry and then reference them in some map entity. -ut
