### ISSUE TITLE
update not work in 3.0

### ISSUE THREAD

**Issue by jiaruiz** [greenrobot/greenDAO#418]
I try to use two kind of method 
```java
Cycle cycle = getDaoSession().getCycleDao().queryBuilder().where(CycleDao.Properties.Id.eq(id)).unique();
cycle.setZan_id((int) zanid);
getDaoSession().getCycleDao().update(cycle);
```

or
`getDaoSession().getDatabase().execSQL("update CYCLE set ZAN_ID = " + zanid + " where ID = " + id);`

the filed `ZAN_ID` not update while i query cycle

**Comment by greenrobot-team** [comment]
Not sure what is going wrong there. Can you post your `@Entity` class?

But keep in mind that you have to re-run a query after updating entities to get the latest values. -ut

**Comment by jiaruiz** [comment]
public class Cycle implements Comparable<Cycle> {

    private long id;
    private Integer user_role_id;
    private Integer pagesize;
    private Integer role_id;
    private Integer current_id;
    private long userid;
    private Integer school_id;
    private Integer is_sync;
    private Integer status;
    private Integer push_screen;
    private Integer zan_size;
    private Integer size;
    private Integer class_id;
    private Integer startRow;
    private Integer is_top;
    private Integer replay_size;
    private String phone;
    private String time;
    private String pics;
    private String user_parent_type;
    private String name;
    private String video_frame;
    private String headUrl;
    private String client_id;
    private String video;
    private String isFootStep;
    private String isFirst;
    private String content;
    private String user_name;
    private String source;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient CycleDao myDao;

    public List<Zan> zan;

    public List<Replay> replay;
    /**
     * 0 加载网络图片
     * 1 加载本地图片
     */
    private int image_source;
    private String qn_name;
    /**
     * 1 未同步
     */
    private Integer sync;
    private int zan_id;
    private boolean zaned;

    @Override
    public boolean equals(Object o) {
        return id == ((Cycle) o).getId();
    }

    @Override
    public int hashCode() {
        return (int) id;
    }

    @Override
    public int compareTo(Cycle another) {
        return (int) (another.getId() - (getId()));
    }

    public void setZan(List<Zan> zan) {
        this.zan = zan;
    }

    public String getQn_name() {
        return qn_name;
    }

    public void setQn_name(String qn_name) {
        this.qn_name = qn_name;
    }

    public int getZan_id() {
        return zan_id;
    }

    public void setZan_id(int zan_id) {
        this.zan_id = zan_id;
    }

    public boolean isZaned() {
        return zaned;
    }

    public void setZaned(boolean zaned) {
        this.zaned = zaned;
    }

    public List<Replay> getReplay() {
        List<Replay> local = getLocalReply();
        if (replay != null && replay.size() > 0) {
            if (local != null && local.size() > 0) {
                replay.addAll(local);
                replay = new ArrayList<>(new HashSet(replay));
                Collections.sort(replay);
                return replay;
            } else {
                return local;
            }
        }
        return replay;
    }

    public void setReplay(List<Replay> replay) {
        this.replay = replay;
    }

    public int getImage_source() {
        return image_source;
    }

    public void setImage_source(int image_source) {
        this.image_source = image_source;
    }

    public Cycle() {
    }

    public Cycle(Long id) {
        this.id = id;
    }

    public Cycle(long id, Integer user_role_id, Integer pagesize, Integer role_id, Integer current_id, long userid,
                 Integer school_id, Integer is_sync, Integer status, Integer push_screen, Integer zan_size, Integer
                         size, Integer class_id, Integer startRow, Integer is_top, Integer replay_size, String phone,
                 String time, String pics, String user_parent_type, String name, String video_frame, String headUrl,
                 String client_id, String video, String isFootStep, String isFirst, String content, String user_name,
                 String source, Integer image_source, Integer sync, int zan_id) {
        this.id = id;
        this.user_role_id = user_role_id;
        this.pagesize = pagesize;
        this.role_id = role_id;
        this.current_id = current_id;
        this.userid = userid;
        this.school_id = school_id;
        this.is_sync = is_sync;
        this.status = status;
        this.push_screen = push_screen;
        this.zan_size = zan_size;
        this.size = size;
        this.class_id = class_id;
        this.startRow = startRow;
        this.is_top = is_top;
        this.replay_size = replay_size;
        this.phone = phone;
        this.time = time;
        this.pics = pics;
        this.user_parent_type = user_parent_type;
        this.name = name;
        this.video_frame = video_frame;
        this.headUrl = headUrl;
        this.client_id = client_id;
        this.video = video;
        this.isFootStep = isFootStep;
        this.isFirst = isFirst;
        this.content = content;
        this.user_name = user_name;
        this.source = source;
        this.image_source = image_source;
        this.sync = sync;
        this.zan_id = zan_id;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCycleDao() : null;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getUser_role_id() {
        return user_role_id;
    }

    public void setUser_role_id(Integer user_role_id) {
        this.user_role_id = user_role_id;
    }

    public Integer getPagesize() {
        return pagesize;
    }

    public void setPagesize(Integer pagesize) {
        this.pagesize = pagesize;
    }

    public Integer getRole_id() {
        return role_id;
    }

    public void setRole_id(Integer role_id) {
        this.role_id = role_id;
    }

    public Integer getCurrent_id() {
        return current_id;
    }

    public void setCurrent_id(Integer current_id) {
        this.current_id = current_id;
    }

    public long getUserid() {
        return userid;
    }

    public void setUserid(long userid) {
        this.userid = userid;
    }

    public Integer getSchool_id() {
        return school_id;
    }

    public void setSchool_id(Integer school_id) {
        this.school_id = school_id;
    }

    public Integer getIs_sync() {
        return is_sync;
    }

    public void setIs_sync(Integer is_sync) {
        this.is_sync = is_sync;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getPush_screen() {
        return push_screen;
    }

    public void setPush_screen(Integer push_screen) {
        this.push_screen = push_screen;
    }

    public Integer getZan_size() {
        return zan_size;
    }

    public void setZan_size(Integer zan_size) {
        this.zan_size = zan_size;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    public Integer getClass_id() {
        return class_id;
    }

    public void setClass_id(Integer class_id) {
        this.class_id = class_id;
    }

    public Integer getStartRow() {
        return startRow;
    }

    public void setStartRow(Integer startRow) {
        this.startRow = startRow;
    }

    public Integer getIs_top() {
        return is_top;
    }

    public void setIs_top(Integer is_top) {
        this.is_top = is_top;
    }

    public Integer getReplay_size() {
        return replay_size;
    }

    public void setReplay_size(Integer replay_size) {
        this.replay_size = replay_size;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getPics() {
        return pics;
    }

    public void setPics(String pics) {
        this.pics = pics;
    }

    public String getUser_parent_type() {
        return user_parent_type;
    }

    public void setUser_parent_type(String user_parent_type) {
        this.user_parent_type = user_parent_type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getVideo_frame() {
        return video_frame;
    }

    public void setVideo_frame(String video_frame) {
        this.video_frame = video_frame;
    }

    public String getHeadUrl() {
        return headUrl;
    }

    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl;
    }

    public String getClient_id() {
        return client_id;
    }

    public void setClient_id(String client_id) {
        this.client_id = client_id;
    }

    public String getVideo() {
        return video;
    }

    public void setVideo(String video) {
        this.video = video;
    }

    public String getIsFootStep() {
        return isFootStep;
    }

    public void setIsFootStep(String isFootStep) {
        this.isFootStep = isFootStep;
    }

    public String getIsFirst() {
        return isFirst;
    }

    public void setIsFirst(String isFirst) {
        this.isFirst = isFirst;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Integer getSync() {
        return sync;
    }

    public void setSync(Integer sync) {
        this.sync = sync;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not
     * persisted, make changes to the target entity.
     */
    public List<Zan> getZan() {
        List<Zan> local = getLocalZan();
        if (local != null && local.size() > 0) {
            if (zan != null && zan.size() > 0) {
                local.addAll(zan);
                zan = new ArrayList<>(new HashSet(local));
            } else {
                removeLocalZan();
                return zan;
            }
        }
        return zan;
    }

    private void removeLocalZan() {
        if (daoSession == null) {
            daoSession = DbUtils.getDaoSession();
        }
        ZanDao targetDao = daoSession.getZanDao();
        targetDao.deleteInTx(getLocalZan());
    }

    public List<Zan> getLocalZan() {
        if (daoSession == null) {
            daoSession = DbUtils.getDaoSession();
        }
        ZanDao targetDao = daoSession.getZanDao();
        return targetDao.queryBuilder().where(ZanDao.Properties.Cycle_id.eq(id)).list();
    }

    public List<Replay> getLocalReply() {
        if (daoSession == null) {
            daoSession = DbUtils.getDaoSession();
        }
        ReplayDao targetDao = daoSession.getReplayDao();
        return targetDao._queryCycle_Reply(id);
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetZan() {
        zan = null;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

}

**Comment by jiaruiz** [comment]
@greenrobot

**Comment by greenrobot-team** [comment]
OK, so the following does not work?

```java
Query<Cycle> query = getDaoSession().getCycleDao().queryBuilder().where(CycleDao.Properties.Id.eq(id)).build();
Cycle cycle = query.unique();

cycle.setZan_id((int) zanid);
getDaoSession().getCycleDao().update(cycle);

cycle = query.unique();
```
-ut

**Comment by jiaruiz** [comment]
i found the result finally.the id is modify long.while i change it LONG.it work right.~

**Comment by greenrobot-team** [comment]
Ah, ok. Thanks for reporting back! -ut
