### ISSUE TITLE
How to use foreign key for custom object

### ISSUE THREAD

**Issue by vivekwolf123** [greenrobot/greenDAO#419]
I want to use a Custom object and store it using greenDAO3. Here is my code - 

```java
@Entity
public class Books{

    @Id(autoincrement = true)
    private Long id;
    private double LATITUDE;
    private double LONGITUDE;
    private Date LASTSYNC;

    @NotNull
    private FeedbackStatus FEEDBACK;
    private long TIMESTAMP;
}
```

As you can see FEEDBACK is a custom object and I need it to store it in my DB. But how do I annotate ? There is no good documentation for using foreign key in greenDAO3 annotation.

Could you please help me in this?

**Comment by greenrobot-team** [comment]
If I understand correctly, what you want is a [`@ToOne` relation](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#Relation_annotations_ToOne_ToMany_etc) (so `FeedbackStatus` is another `@Entity`). -ut

**Comment by vivekwolf123** [comment]
FeedbackStatus is an enum with strings.

**Comment by greenrobot-team** [comment]
Alright, you might want to [use a converter then](https://github.com/greenrobot/greenDAO/issues/366#issuecomment-233240580). -ut

**Comment by vivekwolf123** [comment]
I tried using converter but it did not work. Basically, I am using GreenDAO3 annotations. 
I have a FeedbackStatus enum of Strings. As per my code above, FEEDBACK is an object of enum FeedbackStatus. I am unable to write this enum in database.

**Comment by greenrobot-team** [comment]
Make sure your converter is properly implemented and you are using the latest version of greendao (`3.1.1` as of this time). Check out the example [`NoteTypeConverter`](https://github.com/greenrobot/greenDAO/blob/V3.1.1/examples/DaoExample/src/main/java/org/greenrobot/greendao/example/NoteTypeConverter.java) which also converts an enum.

If things still do not work, what exactly is going wrong? Do you get an error message? -ut

**Comment by vivekwolf123** [comment]
Great :) Thank you :) It helped me. You can close this.
