### ISSUE TITLE
A question about the size of the database

### ISSUE THREAD

**Issue by Lesences** [greenrobot/greenDAO#431]
Hello guys !  When I am in the process of development, I want to know the size of  my database, Is there any way ?

**Comment by tilmanginzel** [comment]
Do you want to do it programmatically? Than you could try the following code snippet, taken from [stackoverflow](http://stackoverflow.com/questions/6364577/how-to-get-the-current-sqlite-database-size-or-package-size-in-android#6514474).

```java
File f = context.getDatabasePath(dbName);
long dbSize = f.length();
```

If not, you could just pull the file from the device and check it. Alternatively, you can use the [Android Device Monitor](https://developer.android.com/studio/profile/monitor.html) and navigate to the database file, without pulling it from the device.

**Comment by Lesences** [comment]
@tilmanginzel  OK,thank you very much,I will try !

**Comment by Lesences** [comment]
@tilmanginzel  
Yesterday, I see Android SQLiteDataBase source code, find an another way, the result is the same !

```java
        long pageSize = dbManager.getDb().getPageSize();
        long pageCount = DatabaseUtils.longForQuery(dbManager.getDb(), "PRAGMA page_count;", null);
```
