### ISSUE TITLE
The  Database db = helper.getEncryptedWritableDb("pwd"); is error

### ISSUE THREAD

**Issue by 18337129968** [greenrobot/greenDAO#439]
`
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-support-annotations-23.4.0_c9fae43cda2e1c04b2ab0de43a8f148b5b1a92fa-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-stetho-okhttp3-1.3.1_0b96bc8e016f2feda1f795178da73782b0cf170b-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-stetho-1.3.1_188774134423d3687d973af0cf97acae42053549-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-rxjava-1.1.8_292ae3995d1eed9d8e95f69ea1728f88ec6efa5c-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-retrofit-2.0.2_ef69ae1c75e8c0b59eb461cacb0ae52e449cf07a-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-otto-1.3.8_e9db0628aafd4857a0f5165f559642d620bd29bb-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-okio-1.6.0_c410569bd3ae660f2a7eceb3af69efc833b46b70-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-okhttp-3.2.0_e97c4d684058659f4c78fd063d89ce0d8b400297-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-net.zetetic-android-database-sqlcipher-3.5.2_c1494add8ee05e6e7af8b6288c045d35d3c521c3-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-logging-interceptor-3.2.0_8c091b18cda26f82f174b3fa9c0f816fb931a653-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-leakcanary-watcher-1.4-beta2_8930e9db82ca053aa73295905792a92261454cc2-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-leakcanary-analyzer-1.4-beta2_bc589143ab9961d400280c5df95f0866c53949a0-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-jsr305-2.0.1_69d0b6c8ffa05193b3c0ebfa1d1d218ee290f911-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-javax.inject-1_273da2ba53aedc2691b5c6c4485ebe7b12b6e634-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-io.reactivex-rxandroid-1.2.1_b688a664e9e5a723be7f927310598d82f8c2e090-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-internal_impl-23.4.0_ca107413ead81dbfb3d94abd2d0118226268df9b-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-haha-2.0.2_bf7137858285ff2850156bd9ad03ec720e349dec-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-gson-2.6.1_7cd154ea7948a4454c775db22bc00deb7ba667b3-classes.dex", dex file "/data/data/com.app.sampleandroidproject/files/instant-run/dex/slice-greendao-generator-3.1.0_c5cd7aacc841960bc03
`

My compile :

```
    compile 'org.greenrobot:greendao:3.1.1'
    compile 'org.greenrobot:greendao-generator:3.1.0'
    compile 'net.zetetic:android-database-sqlcipher:3.5.2'
```

**Comment by greenrobot-team** [comment]
My first guess this is an issue [with multidex](https://developer.android.com/studio/build/multidex.html#mdex-gradle). Do you really need it, can you disable it? -ut

**Comment by greenrobot-team** [comment]
Whoops, too fast. Instant Run does slicing, also in logs. Try to turn off Instant Run and see if the error persists. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
