### ISSUE TITLE
autoincrement not work

### ISSUE THREAD

**Issue by Gvardia** [greenrobot/greenDAO#441]
Hi, i set 
```
@Id(autoincrement = true)
private long   id;
```

And still get
```
09-09 17:53:16.785 21412-21850/works.idna.iddna E/dao.insert(week): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: WEEK._id (code 1555)
in dao.insert(week)
```

**Comment by greenrobot-team** [comment]
Try to use `Long` instead of `long`.

```
   @Id(autoincrement = true)
    private Long id;
```

And maybe do not set an 'id' before inserting (so `id == null`).
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by MrRoshan** [comment]
I meet the same issue, doesn't set id before inserting, use Long instead of long works. Can't use long property for id?

**Comment by greenrobot-team** [comment]
@MrRoshan Yes, you can use `long`. But then you have to take care of assigning IDs yourself (as the default for `long` is `0` and greenDAO does not know whether this means no ID or `ID == 0`, if you use `Long` greenDAO assuems `ID == null` means no ID). -ut

**Comment by danmuf** [comment]
I had the same problem and set type Long to ID. But now I get an error in the files which are build: 
IdeaDao ->  
@Override
public boolean hasKey(Idea entity) {
        return entity.getIdeaID() != null;
 }

I get the error: incomparable types: long and <null> 

I tried to clean and rebuild the project, but it doesn't work. Do you have an idea?

**Comment by greenrobot-team** [comment]
@danmuf Check that the return type for `entity.getIdeaID()` is `Long`. -ut

**Comment by danmuf** [comment]
I fixed this problem by deleting all the @generated methods in the classes for the db. After rebuilding the project there was no error (probably a little bug concerning changing the type  of a property?).

**Comment by sgatade** [comment]
Long works after updating Constructor/Getter & Setters. Thanks!

**Comment by abdussamad123** [comment]
> @MrRoshan Yes, you can use `long`. But then you have to take care of assigning IDs yourself (as the default for `long` is `0` and greenDAO does not know whether this means no ID or `ID == 0`; if you use `Long` greenDAO assumes `ID == null` means no ID). -ut

i'm using Long type for autoincrement id and not inserting id but still its showing UNIQUE constraint failed ,
