### ISSUE TITLE
How to create new Dao Master Class?

### ISSUE THREAD

**Issue by srinivas69** [greenrobot/greenDAO#443]
I'm new to the Green Dao ORM. I have seen many tutorials on the web for the old version of the library.
As in the new version of the library we need to generate DaoMaster class. I'm a beginner can some one show me how to create a DaoMaster class?

**Comment by greenrobot-team** [comment]
The `DaoMaster` class will be automatically generated if you use the new Gradle plugin. To get started [look at the docs](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#greenDAO_3_Gradle_Plugin). -ut
