### ISSUE TITLE
RxDao delete/deleteAll() methods work incorrectly?

### ISSUE THREAD

**Issue by opticalix** [greenrobot/greenDAO#444]
I just call deleteAll() in RxDao, but I have found entities I want to remove still in the database. 
And I also find delete() in AbstractDao and other methods(such as insert()/count()) in RxDao work well. 
I am now using greendao of version 3.1.1.

**Comment by greenrobot-team** [comment]
Did you make sure to subscribe to the result, similar to how it is done [in the example](https://github.com/greenrobot/greenDAO/blob/V3.1.1/examples/RxDaoExample/src/main/java/org/greenrobot/greendao/rxexample/MainActivity.java#L122-L130)?

`RxDao` just calls through to the regular `AbstractDao` class, but wraps everything in an `Observable`.
-ut

**Comment by opticalix** [comment]
I forgot to call subscribe()..its my fault, Thanks!

**Comment by jemshit** [comment]
Is there any method to delete all database tables?

**Comment by greenrobot-team** [comment]
@jemshit The generated `DaoMaster` has a `dropAllTables()` method. -ut

**Comment by jemshit** [comment]
@greenrobot-team i didn't get second argument of `dropAllTables(..., ifExists)`, what does that ifExists used for?

**Comment by greenrobot-team** [comment]
@jemshit By inspecting the code one can see that if `ifExists=true` the drop statement will include an `IF EXISTS` check. If `ifExists=false` and one of the tables that should be dropped does not exist, SQLite will throw an error. If `ifExists=true` that error will be suppressed.

See also [the SQLite DROP TABLE docs](https://sqlite.org/lang_droptable.html). -ut
