### ISSUE TITLE
@Entity class cannot have a property called `entity`

### ISSUE THREAD

**Issue by wcarmon** [greenrobot/greenDAO#445]
`@Entity
public class EntityWrapper {
   private Serializable entity;
  /* other fields */
  /* getter & setters */
}
`
If you have a class like the one above, you get a compilation error ... `entity is already defined in bindValues` in the generated AbstractDao subclass

The issue seems to be here: 
https://github.com/greenrobot/greenDAO/blob/master/DaoGenerator/src-template/dao.ftl#L135

Perhaps this can be solved with a less common name (eg. `entity0000001`).

**Comment by greenrobot-team** [comment]
Thanks! This is already tracked in #314. -ut
