### ISSUE TITLE
Error:Could not find org.greenrobot:greendao-generator:3.1.1

### ISSUE THREAD

**Issue by followztx** [greenrobot/greenDAO#452]
1）Error:Could not find org.greenrobot:greendao-generator:3.1.1
in android studio .
search "greendao-generator" can't find 3.1.1
![image](https://cloud.githubusercontent.com/assets/5896038/18830233/6ecdf25c-8412-11e6-845e-9272628d1442.png)

2）greendao、greendao-generator and greendao-gradle-plugin must be the same version?
or entity can't parse.

**Comment by greenrobot-team** [comment]
`greendao-generator` remains at version `3.1.0`. See #447. -ut
