### ISSUE TITLE
GROUP BY Condition Alternative

### ISSUE THREAD

**Issue by AnkurJagani** [greenrobot/greenDAO#458]
i know GROUP BY condition is not working with greenDAO.  As per here : https://github.com/greenrobot/greenDAO/issues/164

is there any alternative for GROUP BY? Solution given in above link will no work as it fires query with Where condition.

**Comment by greenrobot-team** [comment]
greenDAO returns a list of regular Java objects. You can sort/order them in any way you like [using regular Java code](https://docs.oracle.com/javase/tutorial/collections/interfaces/order.html). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
