### ISSUE TITLE
how one java class mapping multiple tables?thx

### ISSUE THREAD

**Issue by julist213** [greenrobot/greenDAO#460]

**Comment by julist213** [comment]
it's possible to dynamic create multiple table from the java class ?

**Comment by pzhangleo** [comment]
hi,i need this feather too

**Comment by greenrobot-team** [comment]
Have a look at [my comment on multiple tables per entity](https://github.com/greenrobot/greenDAO/issues/455#issuecomment-249790184). In short: greenDAO maps one entity to one table. -ut
