### ISSUE TITLE
@JoinProperty with constant value

### ISSUE THREAD

**Issue by sosite** [greenrobot/greenDAO#462]
It'll be great if you can add a possibility to define additional `value` parameter in place of `name` in `@JoinProperty` annotation:

```java
private static final CONTENT_TYPE = "PROFILE";

@ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "ownerId"),
        @JoinProperty(value = CONTENT_TYPE, referencedName = "contentType")
})
private List<Photo> gallery;
```
eventually:
```java
        @JoinProperty(value = "PROFILE", referencedName = "contentType")
```
===
For now I can hack it by using below code:
```java
private static final CONTENT_TYPE = "PROFILE";

@ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "ownerId"),
        @JoinProperty(name = "id", referencedName = "contentType")
})
private List<Photo> gallery;

@Keep
@Generated(hash = 1328895428)
public List<Photo> getGallery() {
    //...
        List<Photo> galleryNew = targetDao._queryProfile_Gallery(id, CONTENT_TYPE);
    //...
}
```

**Comment by greenrobot-team** [comment]
If I get this correctly, you want to do a join, but with a pre-determined value?

This is not how joins are supposed to work. In that case you might want to do a Where-[Query](http://greenrobot.org/greendao/documentation/queries/) to get the photos with that specific `contentType` instead. Something like:

`List<Photo> photos = photoDao.queryBuilder().where(Properties.ContentType.eq("PROFILE")).list();`

-ut
