### ISSUE TITLE
create duplicate classes when run generator ?

### ISSUE THREAD

**Issue by andishejavan** [greenrobot/greenDAO#465]
why when run generator create two time classes ?

**Comment by greenrobot-team** [comment]
Do you have a simple example project so we can reproduce this? -ut

**Comment by avew** [comment]
+1 i have same problem, this my code generator

```java
public class Main {

    public static void main(String[] args) throws Exception {
        Schema schema = new Schema(1, "com.aseprojali.logsheet.db");

        Entity users = schema.addEntity("Users");
        users.addIdProperty().primaryKey().autoincrement();
        users.addStringProperty("username").notNull().unique();
        users.addStringProperty("password").notNull();

        new DaoGenerator().generateAll(schema, "./app/src/main/java");


    }

}
```
when i run app, DaoMaster,DaoSession is duplicate

**Comment by 13126661431** [comment]
me too

**Comment by greenrobot-team** [comment]
Are you using greenDAO 3.x? If so and you also use the Gradle plugin (`apply plugin: 'org.greenrobot.greendao'): you can only use one of the two.

So either remove your generator project or remove the Gradle plugin.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by abbasalid** [comment]
@greenrobot-team  I am using on of the github project gadgetbridge as module dependency I am getting this error
Duplicate class de.greenrobot.dao.AbstractDao found in modules jetified-greendao......
