### ISSUE TITLE
how to set data to a ToMany property

### ISSUE THREAD

**Issue by eity0323** [greenrobot/greenDAO#468]
there is no setter method in entity class for ToMany property,how can i set data?If I can add a setter method by myself?

**Comment by Samzerge** [comment]
http://greenrobot.org/greendao/documentation/relations/#Resolving_and_Updating_To-Many_Relations

I think that's what you need

**Comment by eity0323** [comment]
@Samzerge that's it! thank you so much

**Comment by greenrobot-team** [comment]
Closing this then. -ut
