### ISSUE TITLE
ToMany relationships not always loading

### ISSUE THREAD

**Issue by dmascord** [greenrobot/greenDAO#469]
Hi guys,

I have an entity as follows:

``` java
@Entity
public class SuperList implements Serializable {

    private static final long serialVersionUID = -6641292855569752036L;

    @Id
    private Long id;
    @ToMany(referencedJoinProperty = "parentId")
    private List<SuperList> items;
    @ToOne(joinProperty = "parentId")
    private SuperList parent;
    private String superName;
}
```

I create this structure, save the children, save the parents, update the parent id's on the object tree, and then commit them all to the DB, so they all have appropriate id and parentId stored.

If I immediately (ie, a line of code directly after the insert/update do the following query, the same object is returned, and I can call getItems() as expected.

```
superListQuery = superListDao.queryBuilder().where(SuperListDao.Properties.UniqueId.isNull()).where(SuperListDao.Properties.ServerId.isNull()).where(SuperListDao.Properties.ParentId.isNull()).build();
                            List<SuperList> superListItemsTmp = superListQuery.list();
```

This returns fine, but obviously just returns the exact same object from the cache, rather than building from the sql data.

If I try and do this at a later stage (ie, after stopping/starting the app), the object tree is not recreated, but the parentId and Id fields are all correctly set, but the ToMany and the ToOne relationships don't populate the objects.

`superListDao.loadAll()` shows all of the individual objects, with their proper data, but not joined.

`superListItemTmp = superListDao.loadDeep(superListItemTmp.getId());` also just returns the object, but without any data structure.

I am replicating an Entity which exists on a remote webservice, so can't really change the object structure.

Any ideas or help will be much appreciated.

Cheers,

Damien

**Comment by greenrobot-team** [comment]
Have a look at the [Relations](http://greenrobot.org/greendao/documentation/relations/) docs: to-one and to-many relations are resolved lazily, on accessing them.

`loadDeep()` only works on to-one relations and only resolves the relation for the current entity, not recursively if I remember.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
