### ISSUE TITLE
Error: Could not find method greendao() for arguments on project 

### ISSUE THREAD

**Issue by bkhezry** [greenrobot/greenDAO#471]
I add libraries in app build.gradle:

 ```
compile 'org.greenrobot:greendao-generator:3.2.0'
compile 'org.greenrobot:greendao:3.2.0'
```
and appy plugin in app build.gradle

`apply plugin: 'org.greenrobot.greendao'`

in root build.gradle add those class path:

```
classpath 'org.greenrobot:greendao-gradle-plugin:3.2.0
classpath 'com.android.tools.build:gradle:2.2.1'
```

after add 
```
greendao {
    schemaVersion 1
}
```
return this error:

`Error: Could not find method greendao() for arguments on project ':app' of type org.gradle.api.Project.`

what can I do for solve this problem?

**Comment by jp1017** [comment]
>classpath 'org.greenrobot:greendao-gradle-plugin:3.1.0'

**Comment by greenrobot-team** [comment]
Try to add the `apply plugin: 'org.greenrobot.greendao'` apply statement right after the Android plugin.

Does this error happen right after you sync the project? Or when? -ut

**Comment by bkhezry** [comment]
@greenrobot-team 
app build.gradle:
![app_gradle](https://cloud.githubusercontent.com/assets/91809/19437099/a5be03b4-9480-11e6-82ef-7ef5522f1fc8.PNG)

root build.gradle:
![root_gradle](https://cloud.githubusercontent.com/assets/91809/19437102/aae7c500-9480-11e6-9773-6a62682205f9.PNG)
yes, I happen in sync progress.

**Comment by bkhezry** [comment]
@greenrobot-team 
I add `apply plugin: 'org.greenrobot.greendao'` after Android plugin and error fixed.
please add this trick in README file.

**Comment by greenrobot-team** [comment]
Also note: you have to apply a Gradle plugin before you can use its functionality in your build config (see your first screenshot where you apply it after already using the `greendao` config closure).
-ut

**Comment by gitzsl** [comment]
![image](https://cloud.githubusercontent.com/assets/19160342/20957603/d7520dd4-bc8b-11e6-8470-2c206604fc07.png)
What is the meaning of this sentence？

**Comment by greenrobot-team** [comment]
@gitzsl This is no longer relevant. Just make sure to use the latest version of the Android and greenDAO Gradle Plugin. See [the introduction guide](http://greenrobot.org/greendao/documentation/introduction/).
