### ISSUE TITLE
A little suggestion to improve Dao.update method 

### ISSUE THREAD

**Issue by GoodnessJesus** [greenrobot/greenDAO#472]
Currently, if I want to update a row or multi rows in a database that satisfied specific selection, I have to query entities first, then modify properties, update database with those entities at last. 

For example
```java
Orders entity = dao.load(id);
if (entity != null) {
    entity.setFileName(newPath); 
    dao.update(entity);
}
```
I don't think this is convinent as SQLiteDatabase.update method--do an update operation in just one single statement. So, a new update method with selection and the latest property values as arguments is welcomed.

**Comment by greenrobot-team** [comment]
Working with objects is [the whole point of greenDAO](http://greenrobot.org/greendao/documentation/introduction/) (and any other object-relational mapping tool).

Feel free to use raw SQL to update your entities, you can get the database instance from `DaoMaster.getDatabase()`. -ut
