### ISSUE TITLE
why the data changed when I have not using update?

### ISSUE THREAD

**Issue by Yetland** [greenrobot/greenDAO#474]
I select all my data from database and  do some edit , but when i edit the data without using database , the data changed a lot.

``` java
private List<User> mAllUserList;
mAllUserListBefore = mUserDB.selectAll();
for (int i = 0; i < mAllUserList.size(); i++) {
    User user = mAllUserList.get(i);
    if (!user.getIsParent() && user.getParentID() - parentIdBefore == 0) {
        mAllUserList.remove(user);
        user.setParentID(parentIdAfter);
        mAllUserList.add(i, user);
    }
}
```

**Comment by greenrobot-team** [comment]
I really do not understand the issue, also your code snippet seems to do nothing? Please give a complete example, preferably a small example project.

(Note: this might be a bot.) -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
