### ISSUE TITLE
Boolean field with null value not matches with .neq(true)

### ISSUE THREAD

**Issue by DOFandersolsen** [greenrobot/greenDAO#475]
Hi!
Thanks for a great product 😃 

I had a bug today, where a Boolean field had a value of null (as I had forgotten to set the value to false during creation and saving to database)

When I queried with the code below, I would not get any result back.
```
QueryBuilder<Observation> qb = dao.queryBuilder();
        qb.where(
                ObservationDao.Properties.CollectionId.eq(mId),
                ObservationDao.Properties.Deleted.notEq(true)
        );
        qb.orderDesc(ObservationDao.Properties.Id);

        List<Observation> observations = qb.list();
```

I later changed the Boolean Property to be not-nullable in my DaoGenerator, and that made the field be false by default and the above query returned the correct observations again.

Is this a greenDAO issue or maybe with SQLite itself ?

**Comment by greenrobot-team** [comment]
greenDAO uses the SQLite `<>` operator for `.notEq()` which does not handle null values.

You can instead query for `.eq(false)` and `.isNull()`.

Or you could do a raw query and use `IS NOT` which does handle null values the way you want. See [the SQLite docs about this](https://www.sqlite.org/lang_expr.html).
-ut
