### ISSUE TITLE
Union Primary Key

### ISSUE THREAD

**Issue by GreatGarlic** [greenrobot/greenDAO#476]
Though I know Android/SqlLite recommended entities must have a long or Long property as their primary key.But Also there is demand Need to be Union Primary Key.

**Comment by greenrobot-team** [comment]
I refer you to #1 and #26. Also, you can [work around the limitations using indexes](http://greenrobot.org/greendao/documentation/modelling-entities/#Primary_key_restrictions). -ut

**Comment by GreatGarlic** [comment]
Thanks!
