### ISSUE TITLE
under app/build/source/greendao the dao field generated and also the src file the dao generated

### ISSUE THREAD

**Issue by andrewindayang** [greenrobot/greenDAO#479]
Hi, when i run the generator, the Dao file created in 2 places and all Daosession and daomaster generated in 2 place which is under app/build/source/greendao and then generated on app/src/main/java/exampleProject/com/exampleProject/dao/ Is there any solution for that?

**Comment by greenrobot-team** [comment]
You can only use either the generator or the Gradle plugin. You can **not use both**.

See the guide about [upgrading to greenDAO 3 from version 2](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/) for explanations.
-ut

**Comment by andrewindayang** [comment]
All good on my side. Thank you so much for your reply.
