### ISSUE TITLE
insert or update in onDestroy method of Activity doesn't work

### ISSUE THREAD

**Issue by MycroftWong** [greenrobot/greenDAO#480]
I want to save data when process is terminated, and I found that Service's onDestroy isn't executed, but Activity's onDestroy can be executed on my Nexus 6P android 7.0 . So I save data in onDestory of Activity, but GreenDAO doesn't save data. When I restart my app, there's no data.
```java
sDao.updateInTx(sDownloadItems);
// or
sDao.insert(item);
```
How can I solve this? tks

**Comment by greenrobot-team** [comment]
For reference, have a look at [the Android activity lifecycle](https://developer.android.com/guide/components/activities.html#Lifecycle) and why `onDestroy()` might not be always called.
