### ISSUE TITLE
Trying to insert records with many-to-many relation

### ISSUE THREAD

**Issue by iballan** [greenrobot/greenDAO#484]
Failed to insert records with many-to-many relations 

Example:

Mood class:

```
@Entity
public class Mood {
    @Id
    private Long id;

    @ToMany
    @JoinEntity(
            entity = JoinMoodNote.class,
            sourceProperty = "moodId",
            targetProperty = "moodNoteId"
    )
    private List<MoodNote> notes = new ArrayList<>();
}
```

MoodNote class:

```
@Entity
public class MoodNote {
    @Id
    private Long id;
    private String content;
}
```

JoinMoodNote class:

```
@Entity
public class JoinMoodNote {
    @Id private Long id;
    private Long moodId;
    private Long moodNoteId;
}
```

now i have list of Mood which contains list of MoodNote, when i try to insert Mood list to database it should automatically insert also the list of MoodNote:

`
moodDao.insertTx(moods);
`

But It only insert the Mood and nothing happening to MoodNote 

Is is a bug in the library or this kind of inserts is not supported ?

**Comment by greenrobot-team** [comment]
Have a look at [the documentation for To-Many relations](http://greenrobot.org/greendao/documentation/relations/#Resolving_and_Updating_To-Many_Relations). -ut

**Comment by 4goodapp** [comment]
The many to many part in [To-Many](http://greenrobot.org/greendao/documentation/relations/#Resolving_and_Updating_To-Many_Relations) is not well detailed I think. Do you guys have an working example using many to many?

**Comment by iballan** [comment]
@greenrobot I checked the example of Order and Products.
Lets talk about the same example of @JoinEntity :

lets say I have Product that have List<Orders>, I have also the JoinProductsWithOrders class to represent many to many.

The problem happens when I get list of products from the webservice:

```List<Product> products;```
here every product have a list of Orders (One order can be included in one or more product as well)

When I try to insert products all at once to the database like this

productDao.insertOrReplace(products);

Here only the products information will be saved to the database, The list of orders is not saved to Order table.

**Comment by greenrobot-team** [comment]
Read the part about [Resolving and Updating To-Many Relations](http://greenrobot.org/greendao/documentation/relations/#Resolving_and_Updating_To-Many_Relations). You have to insert those yourself. -ut
