### ISSUE TITLE
Bi-Directional M:N Relations

### ISSUE THREAD

**Issue by 4goodapp** [greenrobot/greenDAO#489]
In your [doc Relations page ](http://greenrobot.org/greendao/documentation/relations/#Bi-Directional_1N_Relations), in the **_Bi-Directional 1:N Relations_** You said we can navigate 1:N relations in both directions, but what about an M:N relation? 
So how do we access access both models from either side?

**Comment by greenrobot-team** [comment]
I suppose you would have to add a `@ToMany @JoinEntity(...)` annotation in both entities? See the point about `@JoinEntity` [under Modelling To-Many Relations](http://greenrobot.org/greendao/documentation/relations/#Modelling_To-Many_Relations). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by 4goodapp** [comment]
Well I tried that, it didn't work.... I give up.
Went to Realm, and everything work flawlessly.
