### ISSUE TITLE
How to Create ToOne or ToMany by GreenDao

### ISSUE THREAD

**Issue by liusilong** [greenrobot/greenDAO#491]
Hello,I was just starting to see Greendao,and I read the document “Relations”。In Example , not found project about it，so，I would like to ask if there is an example of this，Thinks。

**Comment by greenrobot-team** [comment]
There are examples [on the Relations page](http://greenrobot.org/greendao/documentation/relations/).

You can also check out [the annotation test entities](https://github.com/greenrobot/greenDAO/tree/V3.2.0/tests/DaoTestEntityAnnotation/src/main/java/org/greenrobot/greendao/test/entityannotation), they use relations. -ut

**Comment by liusilong** [comment]
@greenrobot-team ，Hello，Thank you for answering my question.now I have a new problem is that when I want to Fuzzy query,as follows：
`qb.where(GoodsKindDao.Properties.Name.like("%" + "beer" + "%")).list();`
but it's dose't work.How to do fuzzy query use GreenDao3.2,thinks.

**Comment by greenrobot-team** [comment]
See [this explanation](https://www.tutorialspoint.com/sqlite/sqlite_like_clause.htm) for details about the `LIKE` operator, which greenDAO uses for `.like()`. Are you sure that there are entities in your database that match this query? -ut
