### ISSUE TITLE
Feature: queryBuilder with RxJava

### ISSUE THREAD

**Issue by rusmichal** [greenrobot/greenDAO#495]
Is it possible to implement more operation for RxDao? For example, query builder with Rx.

**Comment by greenrobot-team** [comment]
This works already right now, [see the example](https://github.com/greenrobot/greenDAO/blob/V3.2.0/examples/RxDaoExample/src/main/java/org/greenrobot/greendao/rxexample/MainActivity.java#L46). -ut

**Comment by rusmichal** [comment]
Thx!!!!
