### ISSUE TITLE
DaoSession.clear() for single DAO

### ISSUE THREAD

**Issue by yx19861211** [greenrobot/greenDAO#500]
DaoSession.clear() is all clear.
I hope appoint clear, not all clear.

**Comment by greenrobot-team** [comment]
To rephrase: it should be possible to clear only the cached objects for a single DAO, not just all of them, like `DaoSession.clear()` does.

Possibly expose `daoConfig.clearIdentityScope();` through the DAO object? -ut

**Comment by greenrobot-team** [comment]
Ah, what you want can already be done: `noteDao.detachAll()` clears the identity scope for a single DAO. -ut
