### ISSUE TITLE
When updating to version 3.2.0 i cannot use String as @Id

### ISSUE THREAD

**Issue by ChristianLJ** [greenrobot/greenDAO#503]
In version 3.1.1 i am using the following which works perfectly.
```java
@Id
private String recordID;
```
In version 3.20 this seems to generate the error:
```
Error:Execution failed for task ':appxxx:greendao'.
> Found 1 problem(s) parsing ...\CollectionItem.java". First problem:
Pb(877) Cannot switch on a value of type String. Only convertible int values, strings or enum variables are permitted (16778093 at line 459
Run gradle with --info for more details
```

Is there anything i can do to fix this?

**Comment by greenrobot-team** [comment]
Is there a `switch(stringValue)` statement in your entity class `CollectionItem`? If yes, a temporary workaround is to use conditionals isntead. -ut

**Comment by ChristianLJ** [comment]
I have the following function in my CollectionItem class:

´´´java
 private HashMap<String, List<String>> assembleGenreAndStyles(Context context) {
        HashMap<String, List<String>> cache = new HashMap<>();

        String[] genres = context.getResources().getStringArray(R.array.genres);

        for (String genre : genres) {
            try {
                switch (genre) {
                    case "Non-Music":
                        cache.put(genre, Arrays.asList(context.getResources().getStringArray(context.getResources().getIdentifier("genreNonMusic", "array", context.getPackageName()))));
                        break;
                    case "Children's":
                        cache.put(genre, Arrays.asList(context.getResources().getStringArray(context.getResources().getIdentifier("genreChildren", "array", context.getPackageName()))));
                        break;
                    case "Hip Hop":
                        cache.put(genre, Arrays.asList(context.getResources().getStringArray(context.getResources().getIdentifier("genreHipHop", "array", context.getPackageName()))));
                        break;
                    case "Folk, World, & Country":
                        cache.put(genre, Arrays.asList(context.getResources().getStringArray(context.getResources().getIdentifier("genreFolkWorldCountry", "array", context.getPackageName()))));
                        break;
                    case "Funk / Soul":
                        cache.put(genre, Arrays.asList(context.getResources().getStringArray(context.getResources().getIdentifier("genreFunkSoul", "array", context.getPackageName()))));
                        break;
                    case "Stage and Screen":
                        cache.put(genre, Arrays.asList(context.getResources().getStringArray(context.getResources().getIdentifier("genreStageScreen", "array", context.getPackageName()))));
                        break;
                    case "Brass and Military":
                        cache.put(genre, Arrays.asList(context.getResources().getStringArray(context.getResources().getIdentifier("genreBrassMilitary", "array", context.getPackageName()))));
                        break;
                    default:
                        cache.put(genre, Arrays.asList(context.getResources().getStringArray(context.getResources().getIdentifier("genre" + genre, "array", context.getPackageName()))));
                        break;
                }
            } catch (Exception ex) {
                Log.e("OnVinyl", "Genre: " + genre);
            }
        }
        return cache;
    }
´´´
What you are saying is that i should use if()elseif()... instead of the switch?

**Comment by greenrobot-team** [comment]
This is a quick workaround. The issue in the greenDAO Gradle plugin will be fixed with the next update. -ut
