### ISSUE TITLE
How to store protocol buffer directly using greenDAO 3

### ISSUE THREAD

**Issue by tankjj** [greenrobot/greenDAO#505]
Hi,

I'm trying to use greenDAO 3 to store protocol buffer bytes directly into database, but I find little document about it. Can anyone give some examples or documents to me? Thanks a lot in advance.

**Comment by greenrobot-team** [comment]
You can define a protobuf class with the `protobuf` flag on your `@Entity` annotation, like `@Entity(protbuf = SomeProto.class)`.

But honestly it would be simpler to keep the protobuf and entity separate: copy the values from your protobuf object to a new entity object, then store that. -ut
