### ISSUE TITLE
Testing / Unit testing

### ISSUE THREAD

**Issue by JNissi** [greenrobot/greenDAO#507]
The links in the faq Testing / Unit testing section are dead. http://greenrobot.org/greendao/documentation/technical-faq/#Testing_Unit_Testing

How am I supposed to use the mocked in-memory-database for testing?

**Comment by greenrobot-team** [comment]
Thanks, I fixed the links. Keep in mind that you can always [browse the source code](https://github.com/greenrobot/greenDAO) right here on GitHub. -ut
