### ISSUE TITLE
Seed Database generation

### ISSUE THREAD

**Issue by deberle** [greenrobot/greenDAO#508]
I haven't found any documentation or other hints regarding creation of a seed DB. 
I would like to ship my app with a pre-generated DB. How do I create that seed DB? I'd like to create it as a script task in within my deployment tools. 
Can I write a command line app that contains greenDAO? 
I have also posted on [StackOverflow](http://stackoverflow.com/q/40608437/921573).

**Comment by greenrobot-team** [comment]
You can pass any SQLite database file when creating greenDAO's `DaoMaster`. Looking on StackOverflow [this has come up before](http://stackoverflow.com/questions/9630288/how-to-create-database-from-assets-in-android-using-greendao-orm-library). -ut
