### ISSUE TITLE
java.lang.UnsupportedOperationException: Unsupported for entities with a non-null key

### ISSUE THREAD

**Issue by TomerBrosh** [greenrobot/greenDAO#511]
Can you explain me why do I get an exception when my generated Dao class is calling 

```
 @Override
    public boolean hasKey(SomeEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }
```

and SomeEntity doesnt have a @NotNull annotaion. 

```
java.lang.UnsupportedOperationException: Unsupported for entities with a non-null key
                                                                         at package.SomeEntityDao.hasKey(SomeEntityDao.java:204)
                                                                         at package.SomeEntityDao.hasKey(SomeEntityDao.java:22)
                                                                         at org.greenrobot.greendao.AbstractDao.save(AbstractDao.java:394)
```

**Comment by greenrobot-team** [comment]
Your entity likely has an `@Id` of a primitive Java type, like `@Id long key;`.

To enable `hasKey()` you need to use a nullable type, like `@Id Long key;`.

-ut

**Comment by siavashabdoli** [comment]
@greenrobot-team we don't create hasKey green dao generate this and throw exception! I need to use long not Long but greendao automatically generate has key! How we can disable it?

**Comment by HaoPz** [comment]
@siavashabdoli  hello, I also encountered the same problem, did your problem solve?

**Comment by siavashabdoli** [comment]
@HaoPz just using a wrapper for that! I convert my data to that type in seters! seems that you have to do it with non-primitive Java type
