### ISSUE TITLE
NoClassDefFoundError:DatabaseOpenHelper$EncryptedHelper

### ISSUE THREAD

**Issue by JustinRoom** [greenrobot/greenDAO#512]
java.lang.NoClassDefFoundError: org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper
                                                     at org.greenrobot.greendao.database.DatabaseOpenHelper.checkEncryptedHelper(DatabaseOpenHelper.java:121)
                                                     at org.greenrobot.greendao.database.DatabaseOpenHelper.getEncryptedWritableDb(DatabaseOpenHelper.java:133)

**Comment by greenrobot-team** [comment]
This is likely an issue with your ProGuard configuration. See #430. -ut

**Comment by freddy24** [comment]
actually, I add those code in ProGuard configuration. but it doesn't work. I just run debug version.

**Comment by greenrobot-team** [comment]
Are you using database encryption? Make sure to [add the SQLcipher dependency](http://greenrobot.org/greendao/documentation/database-encryption/#Setting_up_Database_Encryption). -ut

**Comment by pmathur01** [comment]
I am seeing the same error as well: Unable to resolve superclass of Lorg/greenrobot/greendao/database/DatabaseOpenHelper$EncryptedHelper; (346). In my case I am using sqlitecrypt instead. I added the dependency for sqlitecrypt and got the writable database as follows: 


public class DbHelper extends DaoMaster.OpenHelper {

    private  final Context context;
    private  final String name;
    private final int version;
    private SqlitCriptEncryptedHelper encryptedHelper;



    public DbHelper(Context context, String name,int version) {
        super(context, name);
        this.context = context;
        this.name = name;
        this.version = version;
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        onCreate(wrap(db));
    }


    @Override
    public SQLiteDatabase getWritableDatabase() {
        return super.getWritableDatabase();
    }

 

 public Database getSqliteEncryptedWritableDb(String password) {

     SqlitCriptEncryptedHelper encryptedHelper = checkEncryptedHelper();
        return encryptedHelper.wrap(encryptedHelper.getWritableDatabase(password));

    }

    /**
     * Use this to initialize an encrypted SQLCipher database.
     *
     * @see #onCreate(Database)
     * @see #onUpgrade(Database, int, int)
     */
    public Database getEncryptedReadableDb(String password) {
        SqlitCriptEncryptedHelper encryptedHelper = checkEncryptedHelper();
        return encryptedHelper.wrap(encryptedHelper.getReadableDatabase(password));
    }


    private SqlitCriptEncryptedHelper checkEncryptedHelper(){
        if (encryptedHelper == null) {
            encryptedHelper =  new SqlitCriptEncryptedHelper(context, name, version, true);
        }
        return encryptedHelper;
    }

 private class SqlitCriptEncryptedHelper extends SQLiteOpenHelper {
        public SqlitCriptEncryptedHelper(Context context, String name, int version, boolean loadLibs) {
            super(context, name, null, version);
            if (loadLibs) {
                com.sqlitecrypt.database.SQLiteDatabase.loadLibs(context);
            }
        }


        @Override
        public void onCreate(com.sqlitecrypt.database.SQLiteDatabase db) {
            DbHelper.this.onCreate(wrap(db));
        }

        @Override
        public void onUpgrade(com.sqlitecrypt.database.SQLiteDatabase db, int oldVersion, int newVersion) {
            DbHelper.this.onUpgrade(wrap(db), oldVersion, newVersion);
        }

        @Override
        public void onOpen(com.sqlitecrypt.database.SQLiteDatabase db) {
            DbHelper.this.onOpen(wrap(db));
        }

        protected Database wrap(com.sqlitecrypt.database.SQLiteDatabase sqLiteDatabase) {
            return new SqlCriptEncryptedDatabase(sqLiteDatabase);
        }
    }
}
