### ISSUE TITLE
compilation error for plugin 3.2.1

### ISSUE THREAD

**Issue by aksmks** [greenrobot/greenDAO#513]
I am getting this error when compiling with the 3.2.1 plugin version. Last working plugin version was 3.1.1 
Error:Execution failed for task ':app:greendao'.
> org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>([Lorg/eclipse/jdt/internal/compiler/batch/FileSystem$Classpath;[Ljava/lang/String;Z)V

Android studio version 2.1.2

![screen shot 2016-11-21 at 3 22 44 pm](https://cloud.githubusercontent.com/assets/3596338/20478046/78719fc6-affe-11e6-940f-bc635b94d282.png)

**Comment by greenrobot-team** [comment]
Thanks for reporting! Can you show us the full log (the red lines) from Gradle Console in Android Studio? -ut

**Comment by aksmks** [comment]
these are the only messages which i get.
![screen shot 2016-11-22 at 12 50 51 pm](https://cloud.githubusercontent.com/assets/3596338/20514529/70511f74-b0b2-11e6-87c9-1dea9f678c91.png)

**Comment by huayicheng2015** [comment]
#442

**Comment by greenrobot-team** [comment]
Can you try to include the Gradle plugin in the same `build.config` file as the Android Gradle Plugin? So it looks like:

```
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.1'
    }
```

Also make sure to use version 2.2.0 or higher of the Android Gradle plugin.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
