### ISSUE TITLE
QueryBuilder#like method ignores white space

### ISSUE THREAD

**Issue by titanseason** [greenrobot/greenDAO#514]
For example:
I hava keys like this:
abc
abd
ab e
ac
when I use `queryBuilder().where(Dao.Properties.Key.like("ab %"))` (a white space between '_ab_' and '_%_'), the results is: `abc ` `abd ` `ab e`, but the correct result is: `ab e`

**Comment by greenrobot-team** [comment]
greenDAO just passes your condition on to the Android SQLite interface using a `LIKE ?` condition with the args `ab %`. I am not sure what is going wrong there, but it should not be greenDAO's fault.

 -ut

**Comment by titanseason** [comment]
Yes, it's my fault~
