### ISSUE TITLE
How to update row.

### ISSUE THREAD

**Issue by AdityaLabhade** [greenrobot/greenDAO#515]
How to update specific row by id in my greendao database
I am trying with this code - 

```
 long update_id = Long.parseLong(et_id.getText().toString().trim());
DBBook book = DBBookDao.load(update_id);
book .setName(et_name.getText().toString().trim());
bookDao.update(update_book);
```

**Comment by greenrobot-team** [comment]
Looks like the last line should be `bookDao.update(book);`, no? -ut

**Comment by AdityaLabhade** [comment]
Yes, Last line was bookDao.update(book);
There was not a issue, I had found issue from other side.
Thank you greenDao team....
