### ISSUE TITLE
Unable to Encrypted Database

### ISSUE THREAD

**Issue by AdityaLabhade** [greenrobot/greenDAO#516]
I am unable to create encrypted database using sqlcipher.
I am trying to this way -

 DevOpenHelper helper = new DevOpenHelper(this, "book-db-encrypted.db", null);
 Database db = helper.getEncryptedWritableDb("my_key");
 daoSession = new DaoMaster(db).newSession();

But here i got errors : 
1) Can not resolve symbole 'Database'
2) Can not resolve method 'getEncryptedWritableDb'

In my app level dependency 

```
dependencies {

     compile 'com.android.support:appcompat-v7:25.+'

    compile 'net.zetetic:android-database-sqlcipher:3.5.4@aar'
    
    compile 'de.greenrobot:greendao:2.1.0'
}
```

**Comment by greenrobot-team** [comment]
Are you using ProGuard? Make sure to [update your rules](http://greenrobot.org/greendao/documentation/technical-faq/). Are you using multidex? Try to disable it. -ut

**Comment by greenrobot-team** [comment]
You can also check out [our example project](https://github.com/greenrobot/greenDAO/tree/master/examples/DaoExample) which uses database encryption. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
