### ISSUE TITLE
How to use SUM and DISTINCT 

### ISSUE THREAD

**Issue by sandeshnaroju** [greenrobot/greenDAO#518]
Hi,
I have posted my question in StackOverflow(http://stackoverflow.com/questions/40635412/how-to-use-sum-and-dinstinct-with-greendao-querybuilder), but no one replied. May I know how to use SUM and DISTINCT with an example for each?

**Comment by greenrobot-team** [comment]
In your case I suggest doing [a raw query](http://greenrobot.org/greendao/documentation/queries/#Raw_queries) as `QueryBuilder` does not support `SUM`. -ut
