### ISSUE TITLE
多线程操作同一个数据库，有做处理吗？

### ISSUE THREAD

**Issue by MrGang1992** [greenrobot/greenDAO#523]
在多线程并发处理同一个数据库表的时候，有做并发处理吗？？

**Comment by greenrobot-team** [comment]
greenDAO can be used from multiple threads. Though you have to be aware that [query results may be cached](http://greenrobot.org/greendao/documentation/sessions/). Have a look at [the documentation and the usage of `.forCurrentThread()`](http://greenrobot.org/greendao/documentation/queries/#Executing_queries_in_multiple_threads) which can help you. -ut
