### ISSUE TITLE
 greenDAO  Unsupported type  LocalDateTime

### ISSUE THREAD

**Issue by xybCoder** [greenrobot/greenDAO#527]
Error:Execution failed for task ':app:greendao'.
> Can't add field `Variable(type=VariableType(name=org.joda.time.LocalDateTime, isPrimitive=false, originalName=LocalDateTime, typeArguments=null), name=lastLoginAt)` for entity UserInfo due to: Unsupported type org.joda.time.LocalDateTime

**Comment by greenrobot-team** [comment]
Have a look at the documentation about [using custom types](http://greenrobot.org/greendao/documentation/custom-types/). -ut
