### ISSUE TITLE
ToOne use problem

### ISSUE THREAD

**Issue by zhangle1** [greenrobot/greenDAO#529]
I have a userInfo class,
My class A is associated with a userInfo
My B class would like to associate a Class A that has been associated with that userInfo,
I tried for a long time, can not succeed.

**Comment by greenrobot-team** [comment]
I am not sure how I can help other than point you at [the Relations documentation](http://greenrobot.org/greendao/documentation/relations/). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
