### ISSUE TITLE
org.greenrobot.greendao.DaoException: com.dreamdesigner.remembernote.database.NoteDao@9f32c5d (Note) does not have a single-column primary key

### ISSUE THREAD

**Issue by YanYanLun** [greenrobot/greenDAO#531]
org.greenrobot.greendao.DaoException: com.dreamdesigner.remembernote.database.NoteDao@9f32c5d (Note) does not have a single-column primary key，what can I do，Please？

**Comment by greenrobot-team** [comment]
You can only have one property annotated with `@Id`. If you need additional key-like properties, you can use an index. See the [current primary key restrictions](http://greenrobot.org/greendao/documentation/modelling-entities/#Primary_key_restrictions). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
