### ISSUE TITLE
Previous Data Missing when update v2 -> v3

### ISSUE THREAD

**Issue by HenryChao24** [greenrobot/greenDAO#537]
I have custom my own OpenHelper,such as:
`CustomOpenHelper helper = new CustomOpenHelper(mContext, DB_NAME, null);`

Now,I do nothing in my Helper:
`@Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
    // nothing to do now
}`

The db schemaVersion didn't change yet.

help me, thanks

**Comment by greenrobot-team** [comment]
Did you make sure to define your schema version in your `build.gradle` file?

For example if you did define your schema like:
`new Schema(42, "de.greenrobot.daoexample");`

It should now read in your `build.gradle`:
```
greendao {
    schemaVersion 42
}
```
-ut

**Comment by HenryChao24** [comment]
problem resolved,thanks
