### ISSUE TITLE
Switching git branch does not recreate generated entities. Greendao Annotations.

### ISSUE THREAD

**Issue by volic** [greenrobot/greenDAO#538]
If I switching from git branch with grendao entities v1 to another branches with different versions generated code does not recreate GreenDAO entities and GreenDAO classes after making project. It leads to compilation error with absent or presence old classes or some wrong classes could be included to the next build. To fix this issue I have to rebuild all project. It takes a lot of time and could lead to hidden errors. I used Android studio 2.2.3 and greendao 3.1.0

**Comment by greenrobot-team** [comment]
That is expected (rebuild when entity classes are added/removed) if you use generated code. I am not aware of a workaround or way to fix this. -ut
