### ISSUE TITLE
One to many relation with default referencedJoinProperty is not working

### ISSUE THREAD

**Issue by MohanRaj22** [greenrobot/greenDAO#540]
To start with , I'm completely new to GreenDao.
I've a class that has a List with another class type.
When I try to annotate my List object with   `  @ToMany(referencedJoinProperty = "")` I'm getting following error.

Error:Execution failed for task ':app:greendao'.
> Can't process ClassA: Can't create 1-M relation on classBList. Either referencedJoinProperty, joinProperties or @JoinEntity must be used to describe the relation

And For your information I don't have any foreign key  sort of relation here.
I just follow this structure because it complements My web service JSON response.

**Comment by MohanRaj22** [comment]
Hi ,

I found Green Dao as best replacement for the good old SQLite.

But now I'm struggling to create relations between my model classes.

I've a model that will be inserted at first.

Then I've another model which deals with different contest altogether .

I want to map few 2nd models to 1st model. And  save it into third model. In third model I've default toOne relation to model 1 and toMany relation to model 2(Actually there is no foreign key relation here). 

Am I missed out anything Or The model structure I've won't fit into GreenDao ?

**Comment by MohanRaj22** [comment]
I've made changes in my model as of follow ,

//1st class
class User{
@Id
String mobileNumber;
}

//2nd class
class Vehicle{
@Id
String vehicleNumber;
}

//3rd class
class Mapping{
@Id
String mobileNumber;

@ToMany(referencedJoinProperty = "mobileNumber")
List<MappedVehicle> mappedVehicles;

}

I've introduced MappedVehicle class where I store mobileNumber and VehicleDetails.

//Intermediate class with ToOne empty parameter.
class MappedVehicle{
@Id
String mobileNumber;

@ToOne()
Vehicle vehicle;
}

But still I'm getting error when retrieving data from the list like : java.lang.NullPointerException: Entity may not be null

**Comment by greenrobot-team** [comment]
Have a look at the [relations documentation](http://greenrobot.org/greendao/documentation/relations/) for a detailed explanation and examples. -ut
