### ISSUE TITLE
Using the Content Provider, LoaderManager, and a RecyclerView (CursorRecyclerAdapter)

### ISSUE THREAD

**Issue by Isanderthul** [greenrobot/greenDAO#542]
Hi Guys,

First off I would like to say thanks: Even though the content provider is considered experimental, it is still usable. As you tell everyone it is a feature you are working on https://github.com/greenrobot/greenDAO/issues/111. 

I am currently trying it out, and I though I would give some feedback.

First off you posed the question 
> how many entities should a ContentProvider handle?

I am using the two content providers for two entities. I did this due to not wanting to modify the generated content provider code too much (I am using 'de.greenrobot:greendao-generator:2.1.0'). 

You also asked 
> how should we customize the URI?

I am customizing the uri as 
    public static final String AUTHORITY = "<package>.db.gen.provider.DBTelemetryDataContentProvider";
    public static final String BASE_PATH = "DBTelemetryData";

In my manifest.xml I am using two different authorities, due to http://stackoverflow.com/questions/11975215/how-to-address-multiple-content-providers, 
```

<provider
            android:name="db.gen.DBTelemetryDataContentProvider"
            android:authorities="<package>.db.gen.provider.DBTelemetryDataContentProvider"/>

<provider
            android:name="db.gen.DBTripContentProvider"
            android:authorities="<package>.db.gen.provider.DBTripContentProvider"/>

```
I hope that you consider working on the Content Provider in your next milestone. It is a very useful feature!

**Comment by Isanderthul** [comment]
@masonTool The way I enable the contentProvider generated code is in the schema to have
```
private static Entity addTripEntity(Schema schema) {
        Entity tripEntity = schema.addEntity("DBTrip");
        tripEntity.addIdProperty();
        tripEntity.addContentProvider();
...
```

**Comment by greenrobot-team** [comment]
This is tracked with #111 as mentioned. -ut
