### ISSUE TITLE
Contibutor guide - how to test changes of DaoGenerator module

### ISSUE THREAD

**Issue by skrzyneckik** [greenrobot/greenDAO#544]
If greendao gradle plugin isn't available (#412), how can I test changes to DaoGenerator? As an example, I found an issue with dao-deep.ftl and I think it's easy fix, but I have no idea how to test it (#543) after all. The whole project looks open source but how main feature (code generator) can be used is hidden and doesn't allow any contributions for those who doesn't know how use it.

**Comment by greenrobot-team** [comment]
You can create entities [using the generator](http://greenrobot.org/greendao/documentation/generator/) itself. -ut
