### ISSUE TITLE
Unsupported type **.HistoryPositionEntity[]

### ISSUE THREAD

**Issue by jp1017** [greenrobot/greenDAO#545]
Using greenDAO 3.2.0, 

My Entity:

```
@Entity
public class HistoryPositionEntity implements Parcelable {
	@Id
	private Long id;

	private double latitude;
	private double longitude;
	private HistoryPositionEntity[] mEntities;
}
```

compile error:

```
Can't add property 'Variable(type=VariableType(name=dao.entity.HistoryPositionEntity[], 
isPrimitive=false, originalName=HistoryPositionEntity[], typeArguments=null), name=mEntities)'
 to entity HistoryPositionEntity due to: Unsupported type dao.entity.HistoryPositionEntity[]
```

How to resolve it, Any idea?

**Comment by greenrobot-team** [comment]
First of all, try `List<HistoryPositionEntity>`.

Second, if you want your entity to have references to other entites of its type, you need to add [a relation annotation](http://greenrobot.org/greendao/documentation/relations/#Example_Modelling_Tree_Relations).
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by jp1017** [comment]
Now, I use @Transient to ignore this param.
