### ISSUE TITLE
Pb(400)  The type  must implement the inherited abstract method Comparable<Scoreable>.compareTo(Scoreable) 

### ISSUE THREAD

**Issue by jiachenning** [greenrobot/greenDAO#546]
Meet a error when want to config an entity, but I have implement the Comparable.

gradle setting: `org.greenrobot:greendao-gradle-plugin:3.2.1` `org.greenrobot:greendao:3.2.0`
command: ` ./gradlew build --info`
source code:  [the code has upload to the gist](https://gist.github.com/jiachenning/ccf3b2c8ebc2fc478e39a045d691f244)
error info: 
    
    ....
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:310: Pb(50) CarManager cannot be resolved.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:313: Pb(2) ConnectingLineTaizhouTaxi cannot be resolved to a type.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:316: Pb(50) CarManager cannot be resolved.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:324: Pb(50) CarManager cannot be resolved.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:325: Pb(50) CarManager cannot be resolved.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:386: Pb(120) The method getStation() from the type ConnectingLine refers to the missing type ZeonicBusStation.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:388: Pb(50) Timber cannot be resolved.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:390: Pb(120) The method getStation() from the type ConnectingLine refers to the missing type ZeonicBusStation.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:408: Pb(120) The method getStation() from the type ConnectingLine refers to the missing type ZeonicBusStation.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:411: Pb(120) The method getRealTimeBuses() from the type ConnectingLine refers to the missing type RealTimeBus.
    [Verbose] Ignoring parser problem in /p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java:412: Pb(120) The method getBusLineInfo() from the type ConnectingLine refers to the missing type BusLineInfo.
    Found 1 problem(s) parsing "/p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java":
    #1 @28: Pb(400) The type ConnectingLine must implement the inherited abstract method Comparable<Scoreable>.compareTo(Scoreable) (ID: 67109264; error: true)
    :app:greendao FAILED
    :app:greendao (Thread[main,5,main]) completed. Took 0.635 secs.

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':app:greendao'.
    > Found 1 problem(s) parsing "/p/w/d/app/src/main/java/com/zeonic/icity/entity/ConnectingLine.java". First problem:
      Pb(400) The type ConnectingLine must implement the inherited abstract method Comparable<Scoreable>.compareTo(Scoreable) (67109264 at line 28).
      Run gradle with --info for more details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

    BUILD FAILED

Could any one help me?

**Comment by jiachenning** [comment]
Or can the greendao ignore the implement check?

**Comment by greenrobot-team** [comment]
The greenDAO Gradle plugin will have to be updated to ignore this error (is fixed in the internal version). I could not think of a workaround for now. -ut
