### ISSUE TITLE
prepopulated database in assets folder

### ISSUE THREAD

**Issue by AndroidDesigner** [greenrobot/greenDAO#547]
I want to copy assets database tables to the DAO database in database-folder.
for example:
suppose I have created three empty tables [ "table1" , "table2" and "table3" ] in DAO database.
and I have one filled table ["table2"] in assets folder.
columns and properties of the both "table2"are same exactly.
now I want to overwrite data from table2 in assets to the table2 in DAO database.
how can I do it?

**Comment by greenrobot-team** [comment]
You should create a separate `DaoMaster` and pass a separate `OpenHelper` implementation that uses the database in your assets folder. Then just retrieve the stored entities and insert them using the  `DaoMaster/DaoSession` which uses your regular database.

See the [How to get started](http://greenrobot.org/greendao/documentation/how-to-get-started/#Setting_up_the_database) page for more info. -ut
