### ISSUE TITLE
why not support  parameterized type  PropertyConverter in 3.x?

### ISSUE THREAD

**Issue by kswOok** [greenrobot/greenDAO#548]
My custom type  use the PropertyConverter that 
 ```java
 public class ObjConvertByteArray<T> implements PropertyConverter<T, byte[]> {
    @Override
    public T convertToEntityProperty(byte[] databaseValue) {
        try {
            return (T) SerializationUtils.deserialize(databaseValue);
        } catch (Exception e) {
            return null;
        }
    }

    @Override
    public byte[] convertToDatabaseValue(T entityProperty) {

        try {
            return SerializationUtils.serialize(entityProperty);
        } catch (Exception e) {
            return null;
        }
    }
}
```

2.X is ok ,but not support in 3.x ,
here 
```java 
@Convert(converter = ObjConvertByteArray<UserBean>.class, columnType = byte[].class)
    public UserBean user;
```

![image](https://cloud.githubusercontent.com/assets/8502528/21559359/fc870df0-ce85-11e6-9443-2c8cebda6a46.png)

**Comment by greenrobot-team** [comment]
The `@Convert` annotation `converter` argument only takes class references, so in your case only `converter = ObjConvertByteArray.class` is possible. This means that yes, parameterized converters are not supported. You should define a converter for each custom type. -ut
