### ISSUE TITLE
Database not deleting issue on 3.2.0

### ISSUE THREAD

**Issue by pnjolapara** [greenrobot/greenDAO#549]
I am using green DAO version 3.2.0
On specific Samsung -SM-G920v device facing one issue on uninstalling the app and reinstall app its not clearing database.
on reinstalling app its not creating new database, Somewhere its taking reference of old created database and returning old database on new installation.

**Comment by greenrobot-team** [comment]
Your database [might be backed up and restored by Android](https://developer.android.com/guide/topics/data/autobackup.html). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by pnjolapara** [comment]
Let me check this i had not used any Auto Backup or any backup code.
