### ISSUE TITLE
greendao-gradle-plugin license is GPL3 although documentation on the website shows Apache2 for Greendao

### ISSUE THREAD

**Issue by ramib85** [greenrobot/greenDAO#550]
Hi,

I noticed that the gradle plugin uses a different license than Greendao, it is licensed under GPL3 according to the pom file that is published with it.
The other Greendao jars are licensed with Apache2 and the website FAQ specifies Apache2 in the license section.

Is there a difference in these artifacts that requires a different license than the main project ?
I'm considering using it in a corporate project but I'm concerned with the GPL3 license of the plugin.

**Comment by greenrobot-team** [comment]
As the greenDAO **Gradle plugin code is not shipped with your application**, you should be fine regarding licensing: only the Apache 2.0 license applies then.

Only the `org.greenrobot:greendao` artifact is shipped with your app, the plugin is only used to generate code. -ut
