### ISSUE TITLE
Entity name of Sql key word may cause some trouble

### ISSUE THREAD

**Issue by wangzhuangzhuang** [greenrobot/greenDAO#551]
for example:
`Order(enitity)---to one ---Money(entity)`

A exception will throw if you use `orderDao.loadDeep();`
Exception:
`SQLiteException: near "ORDER": syntax error (code 1).....`

You can't find the wrong place in the first sight with this exception.if you change "Order" to "Orders",every thing works fine.Maybe it is better to add entity class name check while generating code with gradle plugin.

**Comment by greenrobot-team** [comment]
If you have stored your entities in a **table named differently from your entity** (so entity is called `Order`, but you called the table `ORDERS`): **set the table name in your entity annotation**.

For example: `@Entity(nameInDb = "ORDERS")`.

(I checked and the generated code for `loadDeep()` is updated correctly after running _Build_ > _Make Project_ (see the generated `OrderDao.getSelectDeep()` method).)
-ut
