### ISSUE TITLE
When can be compatible rxjava2.0

### ISSUE THREAD

**Issue by tangmingscau** [greenrobot/greenDAO#554]
now i use rxjava2.0,if i open the proguard,it will error

**Comment by greenrobot-team** [comment]
See #520. -ut

**Comment by funyoung** [comment]
I forked it and changed DaoCore and RxDaoExaple module with rxjava2. The according changes within test module involve great effort, and I am not sure whether I could compete it or not. If you prefer to have a try, go and take a look at https://github.com/AndroidClasses/greenDAO/tree/rxjava2-dev, any comments and suggestions are welcome.
