### ISSUE TITLE
Duplicate Entry for GreenDAO class while running test project.

### ISSUE THREAD

**Issue by pankajnarula** [greenrobot/greenDAO#558]
I get the following exception while running a sample test for my project 

"com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/abc/def/entities/CredentialEntityDao$Properties.class"

Can you please help me resolve this issue ?

**Comment by greenrobot-team** [comment]
Make sure you do not include your entity classes twice in your dependencies.

Then try to rebuild your project (**Build** > **Rebuild project**).
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
