### ISSUE TITLE
Android getActivity, getContext, getView in fragment is undefined

### ISSUE THREAD

**Issue by xvjianzhe** [greenrobot/greenDAO#562]
[stackoverflow Android getActivity, getContext, getView in fragment is undefined](http://stackoverflow.com/questions/41267308/android-getactivity-getcontext-getview-in-fragment-is-undefined)

**Comment by greenrobot-team** [comment]
Have you defined your entities inside of `WelcomeFragment`? Try to define them each in their own class. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by jmmarko** [comment]
I have the same problem. I do not understand, what do you mean by "define your entities inside of Fragment"? If they are imported?

**Comment by jmmarko** [comment]
I just found out that in my case the problem was that I had "import org.greenrobot.greendao.annotation.ToMany;" under imports. It was never used in the code, but it was a reason for "getActivity() undefined" error. So I guess in your case the problem is NotNull annotation.
