### ISSUE TITLE
setParameter(...) on CountQuery not chainable

### ISSUE THREAD

**Issue by Backfighter** [greenrobot/greenDAO#563]
The `setParameter(...)` method which `CountQuery` gains from the derivation of `AbstractQuery` can't be used with a `CountQuery` for the following reason. The `AbstractQuery` class is not visible to the API user. Since the user can't see the `AbstractQuery` class returned by a call to `setParameter(...)` he can't call its methods.
Is this indented or not?

**Comment by greenrobot-team** [comment]
Hm, looks like chaining is not supported, yes. As a workaround you can assign the query object to a variable like:
```java
CountQuery<Note> noteCountQuery =  noteDao.queryBuilder().buildCount();
noteCountQuery.setParameter(0, true);
long count = noteCountQuery.count();
```
Uwe
