### ISSUE TITLE
gradle-plugin:3.2.1 work error with com.android.tools.build:gradle:2.1.2

### ISSUE THREAD

**Issue by weidongjian** [greenrobot/greenDAO#565]
**gradle-plugin:3.2.0 is work well**

this is my gradle 
```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.1'
    }
}
```

Error:Unable to find method 'com.android.build.gradle.api.BaseVariant.getJavaCompiler()Lorg/gradle/api/Task;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by greenrobot-team** [comment]
Try to update your Android plugin to `com.android.tools.build:gradle:2.2.3`. -ut

**Comment by weidongjian** [comment]
my project is huge, update gradle plugin is a lot of work, now i use gradle-plugin:3.2.0 instead

**Comment by weidongjian** [comment]
my company other project also face the same problem, when update greendao from 2 to 3

**Comment by greenrobot-team** [comment]
The greenDAO Gradle plugin version `3.2.1` requires at least version `2.2.0` of the Android Gradle plugin due to a version conflict of the used JDT version.

We plan to change how the greenDAO plugin is packaged to allow it to be used with any version of the Android Gradle plugin. But this is not ready, yet.
-ut

**Comment by greenrobot-team** [comment]
Another workaround is to ensure the plugin is added as a dependency at the same level (best: in your root `\build.gradle` file) as the Android plugin. Then only apply the plugin in your actual app module (like `app\build.gradle`).

👉 **See [the updated instructions how to add the plugin](http://greenrobot.org/greendao/documentation/introduction/).** 👈

**Comment by greenrobot-team** [comment]
This should be possible as of version `3.2.2` as it hides the JDT version used by the greenDAO plugin. -ut

**Comment by Lukyanov03851** [comment]
I tried this with different versions but nothing working for me:
Error: Connection timed out: connect

**Comment by greenrobot-team** [comment]
@Lukyanov03851 Can you verify your `build.gradle` files are configured like given [in the instructions](http://greenrobot.org/greendao/documentation/introduction/). -ut
