### ISSUE TITLE
getReadableDatabase when using getEncryptedWritableDb bug

### ISSUE THREAD

**Issue by mushketer888** [greenrobot/greenDAO#572]
Version: 3.2.0
Very strange..
In org.greenrobot.greendao.database.DatabaseOpenHelper class which extends SQLiteOpenHelper

there are two functions:
getEncryptedWritableDb(String password) 
and
getEncryptedWritableDb(char[] password)

but in getEncryptedWritableDb(String password) it gets encryptedHelper.getReadableDatabase
but in getEncryptedWritableDb(char[] password) version it gets encryptedHelper.getWritableDatabase

Cant understand what is the trick? or is it bug?

```
public Database getEncryptedWritableDb(String password) {
        EncryptedHelper encryptedHelper = checkEncryptedHelper();
        return encryptedHelper.wrap(encryptedHelper.getReadableDatabase(password));
    }
 public Database getEncryptedWritableDb(char[] password) {
        EncryptedHelper encryptedHelper = checkEncryptedHelper();
        return encryptedHelper.wrap(encryptedHelper.getWritableDatabase(password));
    }

```

**Comment by greenrobot-team** [comment]
That is a bug, thanks for spotting! [The affected line](https://github.com/greenrobot/greenDAO/blob/V3.2.0/DaoCore/src/main/java/org/greenrobot/greendao/database/DatabaseOpenHelper.java#L134). -ut
