### ISSUE TITLE
with insert app crashes, how to use GreenDao?

### ISSUE THREAD

**Issue by EVALIJANI** [greenrobot/greenDAO#574]
public class RegisterOrEditActivity extends AppCompatActivity {

    private myProgramDao myDao;
    private EditText PersonName;
    private EditText LastName;
    private EditText Email;
    private EditText Tel;
    private EditText Username;
    private EditText Password;
    private CheckBox Admin;
    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_register_or_edit);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        PersonName = (EditText) findViewById(R.id.nameEdit);
        LastName = (EditText) findViewById(R.id.lastnameEdit);
        Email = (EditText) findViewById(R.id.emailEdit);
        Tel = (EditText) findViewById(R.id.telEdit);
        Username = (EditText) findViewById(R.id.usernameEdit);
        Password = (EditText) findViewById(R.id.passwordEdit);
        Admin = (CheckBox) findViewById(R.id.checkedAdmin);
        findViewById(R.id.buttonRegister).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                myProgram myPro = new myProgram();
                //myPro.setId(1L);
                myPro.getId();
                myDao.getKey(myPro);
                myPro.setPersonName(PersonName.getText().toString());
                myPro.setLastName(LastName.getText().toString());
                myPro.setEmail(Email.getText().toString());
                myPro.setTel(Tel.getText().toString());
                myPro.setUserName(Username.getText().toString());
                myPro.setPassword(Password.getText().toString());
                myPro.setRole(Admin.isChecked());
                myDao.insertOrReplace(myPro);

                //DaoSession daoSession = ((DB) getApplication()).getDaoSession();
                //myDao = daoSession.getMyProgramDao();
                //daoSession.getMyProgramDao().insertInTx(myPro);
                setResult(RESULT_OK);
                finish();
            }
        });

        //DaoSession daoSession = ((DB) getApplication()).getDaoSession();
        //myDao = daoSession.getMyProgramDao();

     /*   FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab_register);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                *//*Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();*//*
            }
        });*/

    }

}

/////////////////////////////////////////////////////////////

apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"
    defaultConfig {
        applicationId "eric.usersapp"
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            java.srcDirs = ['src/main/java','src/main/java-gen','../dao/classes']
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:recyclerview-v7:24.2.1'
    compile 'com.oguzdev:CircularFloatingActionMenu:1.0.2'
    compile 'org.greenrobot:greendao:3.2.0'
    compile 'com.android.support:design:24.2.1'
    testCompile 'junit:junit:4.12'
}

//////////////////////////////////////////////////////////////////////////////////////////////

apply plugin: 'java'

outputDatabase = 'classes/'

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.greenrobot:greendao-generator:3.2.0'
}
task createDirs {
    def dir = file(outputDatabase)
    dir.mkdirs()
}

sourceCompatibility = "1.7"
targetCompatibility = "1.7"

////////////////////////////////////////////////////////////// and the generator

package com.example;

import org.greenrobot.greendao.generator.DaoGenerator;
import org.greenrobot.greendao.generator.Entity;
import org.greenrobot.greendao.generator.Schema;

public class MyDaoGenerator {
    public static void main(String[] args) throws Exception {
        Schema schema = new Schema(1,"eric.myapp.db");
        Entity myprogram = schema.addEntity("myProgram");
        myprogram.addIdProperty().autoincrement().primaryKey().unique();
        myprogram.addStringProperty("PersonName");
        myprogram.addStringProperty("LastName");
        myprogram.addStringProperty("Email").unique();
        myprogram.addStringProperty("Tel");
        myprogram.addStringProperty("UserName").unique();
        myprogram.addStringProperty("Password");
        myprogram.addBooleanProperty("Role");

        DaoGenerator daoGenerator = new DaoGenerator();

        daoGenerator.generateAll(schema, "./app/src/main/java");
    }
}

**Comment by greenrobot-team** [comment]
There is [extensive documentation](http://greenrobot.org/greendao/documentation/) and an [example app](https://github.com/greenrobot/greenDAO/tree/master/examples/DaoExample). Start with [How to get started](http://greenrobot.org/greendao/documentation/how-to-get-started/). -ut
