### ISSUE TITLE
Could not find class

### ISSUE THREAD

**Issue by e-hai** [greenrobot/greenDAO#575]
I get the Error:
```Could not find class 'org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper', referenced from method org.greenrobot.greendao.database.DatabaseOpenHelper.checkEncryptedHelper```

configure from:
http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/

**Comment by RaymanMartin** [comment]
the same problem

**Comment by greenrobot-team** [comment]
Are you using ProGuard? See the required rules in [the Technical FAQ](http://greenrobot.org/greendao/documentation/technical-faq/). 

If you are using [database encryption](http://greenrobot.org/greendao/documentation/database-encryption/), make sure to include SQLcipher as a dependency. -ut
