### ISSUE TITLE
How can I upgrade the database?

### ISSUE THREAD

**Issue by liuxgchi** [greenrobot/greenDAO#582]
as the data change ,I want to upgrade the database,bug I can not find the api or easy solution to upgrade the database,please help me ,thanks a lot!

**Comment by cydenghua** [comment]
up

**Comment by marcelofernandes29** [comment]
Same here. I have try to do DaoMaster.deleteAll() and then DaoMaster.createAll(), but then the database becomes locked and i cannot access it or insert any entity. 
The only solution so far for me is to change the Database name, after deleting all the entities. But it is boring coming up with different names everytime i have to change de Entities.
A solution whould be very appreciated.

**Comment by zhangmaoyong34** [comment]
increate schemaVersion .

**Comment by marcelofernandes29** [comment]
What do you mean by that? Can you elaborate ?

**Comment by cydenghua** [comment]
rewrite OpenHelper and rewrite method onUpgrade, then rewrite application class oncreate:

@Override
public void onCreate() {
    super.onCreate();
    DaoMaster.DevOpenHelper helper = new YOURHELP...............................................................
    Database db = ENCRYPTED ? helper.getEncryptedWritableDb("super-secret") : helper.getWritableDb();
    daoSession = new DaoMaster(db).newSession();
}

**Comment by greenrobot-team** [comment]
After making changes to your entities, increase the `schemaVersion` number as described in [Modelling entities](http://greenrobot.org/greendao/documentation/modelling-entities/#Schema). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by marcelofernandes29** [comment]
I'm sorry i forget to reply. Thank you that fixed my problem.
