### ISSUE TITLE
Do not generate code for relationship fields @ToOne & @ToMany:

### ISSUE THREAD

**Issue by kosiara** [greenrobot/greenDAO#583]
I'm using Entity's _generateConstructors = false, generateGettersSetters = false_
to stop GreenDao from generating constructors, getters and setters.

However, it still adds generated methods for relationship fields annotated with @ToOne etc.

How can I **stop it from doing that**?

```
@Entity(
        generateConstructors = false,
        generateGettersSetters = false
)
public class Book {

    @Id
    private Long id;

    @ToOne
    private Note note;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Generated
    public Note getNote() {
        return note;
    }

    @Generated
    public void setNote(Note note) {
        this.note = note;
    }
}
```

**Comment by greenrobot-team** [comment]
To resolve relations, those getters and setters require some additional code. Without it greenDAO relations do not work correctly. So they are created regardless of the `generateGettersSetters` setting. -ut
