### ISSUE TITLE
Field validation

### ISSUE THREAD

**Issue by allemattio** [greenrobot/greenDAO#584]
Hi, 
I'm looking for a way(Annotation, pre save/update listener) to validate some fields of my entities.
Is there a way in GreenDao to do this?

Wouldn't it be cool to have this feature?

**Comment by greenrobot-team** [comment]
I think the way to go here is by adding validation in the setters/getters of your entity classes. Does that not work for you? -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
