### ISSUE TITLE
change SCHEMA_VERSION

### ISSUE THREAD

**Issue by gautamshrm3** [greenrobot/greenDAO#585]
How to change SCHEMA_VERSION of the database. 
and how to remove  dropAllTables(DB, true); function from onUpgrade

**Comment by zhangmaoyong34** [comment]
greendao {
    schemaVersion 2
    daoPackage 'com.android.daolib.ttt'
}
modify schemaVersion in build.gradle file.

**Comment by gautamshrm3** [comment]
Thanks

and what about 
remove dropAllTables(DB, true); function from onUpgrade

**Comment by zhangmaoyong34** [comment]
rewrite OpenHelper and rewrite method onUpgrade

**Comment by cydenghua** [comment]
rewrite OpenHelper and rewrite method onUpgrade， then rewrite class application oncreate:

**Comment by cydenghua** [comment]
rewrite OpenHelper and rewrite method onUpgrade， then rewrite your application class oncreate with your OpenHelper.

**Comment by cydenghua** [comment]
rewrite OpenHelper and rewrite method onUpgrade, then rewrite application class oncreate:

**Comment by cydenghua** [comment]
rewrite OpenHelper and rewrite method onUpgrade, then rewrite application class oncreate:
 
    @Override
    public void onCreate() {
        super.onCreate();
        DaoMaster.DevOpenHelper helper = new YOURHELP...............................................................
        Database db = ENCRYPTED ? helper.getEncryptedWritableDb("super-secret") : helper.getWritableDb();
        daoSession = new DaoMaster(db).newSession();
    }

**Comment by greenrobot-team** [comment]
Looks like everything was solved. Thanks @zhangmaoyong34. -ut
