### ISSUE TITLE
Having more than DaoSession connected to 2 different databases in 1 App

### ISSUE THREAD

**Issue by iballan** [greenrobot/greenDAO#588]
I have 2 databases one of them created when the app opened and one of them is provided with the assests 

How can we differentiate the schemas in the gradle and the daoSession generated by GreenDao ?

**Comment by greenrobot-team** [comment]
greenDAO currently only supports connecting to one database at a time.

You may find [my comment about using a database from assets](https://github.com/greenrobot/greenDAO/issues/318#issuecomment-230267913) interesting though. -ut

**Comment by iballan** [comment]
@greenrobot-team  I was able to connect the greenDao to Assets, but i couldnt for more than 1 database since the auto generated DaoSession did not. I got the answer thank you.
Will you support such feature in the near future ?

**Comment by greenrobot-team** [comment]
I can't speak for @greenrobot, but as this is an edge case I would not count on it. -ut
