### ISSUE TITLE
How to module and seperate some code of a Project from GreenDao database without exporting the DB itself?

### ISSUE THREAD

**Issue by EVALIJANI** [greenrobot/greenDAO#589]
Hi,
How to module and seperate some code of a Project from GreenDao without exporting the DB itself?
I mean i wanna use some code in to other projects but the code depends on GreenDao, UserDao, User, DaoSession, DaoMaster.

for example use `List<Entity>` list,
instead of `List<User>` list,

I wanna seperate and make new module

thx

**Comment by greenrobot-team** [comment]
This is a Java programming problem. Sorry, we can not help here. Check with the Java and Android community. -ut
