### ISSUE TITLE
how to clean one or more table? Is not delete table.

### ISSUE THREAD

**Issue by MoonlightSW** [greenrobot/greenDAO#590]
_(:зゝ∠)_，I can't find method about this.

**Comment by MoonlightSW** [comment]
Sorry, I find it . deleteAll() method.

**Comment by zhangmaoyong34** [comment]
clean one or more table. this is upgrade. 
rewrite OpenHelper and rewrite onUpgrade method.
and add code delete table in method onUpgrade
