### ISSUE TITLE
Can we use trigger and how

### ISSUE THREAD

**Issue by gautamshrm3** [greenrobot/greenDAO#591]
Hi Team,

Can we use trigger and how.

Please give the example

**Comment by greenrobot-team** [comment]
greenDAO uses a [plain SQLite database](http://greenrobot.org/greendao/documentation/how-to-get-started/#Setting_up_the_database). To use triggers you have to do a regular [raw SQL query on your database](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#execSQL(java.lang.String)). greenDAO can not help you there. -ut
