### ISSUE TITLE
How can I query by criteria using rx?

### ISSUE THREAD

**Issue by whyrookie** [greenrobot/greenDAO#594]
In the example for Rx I don't see any code  to query by RxDao, I try to use "__InternalRx()"  to get RxQuery with "where()" to query by criteria , it's working for me, is that right?Thanks.

**Comment by lamuTree** [comment]
I can not found any way to query by RxDao and how I can use "__InternalRx()" in detail?

**Comment by greenrobot-team** [comment]
How about [this line in the example](https://github.com/greenrobot/greenDAO/blob/V3.2.0/examples/RxDaoExample/src/main/java/org/greenrobot/greendao/rxexample/MainActivity.java#L46):
`notesQuery = daoSession.getNoteDao().queryBuilder().orderAsc(NoteDao.Properties.Text).rx();`

`.queryBuilder()` returns [a regular QueryBuilder](http://greenrobot.org/greendao/documentation/queries/).
-ut
