### ISSUE TITLE
QueryBuilder -> eager loading of relations?

### ISSUE THREAD

**Issue by Seikilos** [greenrobot/greenDAO#595]
This must be something very obvious but I am unable to grasp how greendao's QueryBuilder handles eager loading of relations.

I have an object (Main), that has a @ToOne relationship set up for some other object (Sub).

```
@Entity
public class Main
{
    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String Name;

    private long itemId;

    @NotNull
    @ToOne(joinProperty = "itemId")
    private Sub item;
}

@Entity
public class Sub
{
    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String SubName;
}
```

How can I retrieve a list of Main objects where each Main object has it's associated Sub object already resolved?

Here is some repro code, I set up some entries and the interesting part is the last bit, where I perform the actual query:

```
// minor set up -----------------------------------------------
DaoMaster.OpenHelper helper = new DaoMaster.DevOpenHelper(this, "dummy", null);
SQLiteDatabase db = helper.getWritableDatabase();
DaoMaster daoMaster = new DaoMaster(db);

DaoSession daoSession = daoMaster.newSession();

SubDao subDao = daoSession.getSubDao();

Sub sub = new Sub(null, "Sub");
subDao.deleteAll();
subDao.insertInTx(sub);

MainDao mainDao = daoSession.getMainDao();
mainDao.deleteAll();
mainDao.insertInTx(new Main(null, "Main1", sub.getId()), new Main(null, "Main2", sub.getId()));

daoSession.clear();

// end minor set up ----------------------------------------------- 

QueryBuilder.LOG_SQL = true;
QueryBuilder.LOG_VALUES = true;
// Query it
{
    QueryBuilder<Main> mainQuery = mainDao.queryBuilder();

    mainQuery.join(MainDao.Properties.ItemId, Sub.class, SubDao.Properties.Id);

    List<Main> list = mainQuery.list();

    // THIS IS OK, but both objects have their item Property set to null
    Assert.assertEquals(2, list.size());

}
```

The debug output of the query has the correct join syntax, but it does not fetch anything from Sub in the selected columns:

>     D/greenDAO: Built SQL for query: SELECT T."_id",T."NAME",T."ITEM_ID" FROM "MAIN" T JOIN SUB J1 ON T."ITEM_ID"=J1."_id"

If I break at the very last line and inspect the objects I see that the items have been not yet resolved. Calling GetItem() resolves those objects but I explicitly want eager loading to avoid fetching all those objects with single requests.

Can GreenDAO do this?

**Comment by greenrobot-team** [comment]
Have a look at the [Modelling To-One Relations](http://greenrobot.org/greendao/documentation/relations/#Modelling_To-One_Relations) part of the Relations documentation. Specifically the note about eagerly loading to-one relations. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by Seikilos** [comment]
I did not receive a comment until today. Sorry.
The sample code above I've written already contains a ToOne relation. It does not allow me to query lists of objects deep, only one object with their associated relation, which is very inefficient when I need to query 1000 objects with their relations.

**Comment by greenrobot-team** [comment]
@Seikilos [As I said](https://github.com/greenrobot/greenDAO/issues/595#issuecomment-287693310), that is how greenDAO [to-one relations](http://greenrobot.org/greendao/documentation/relations/#Modelling_To-One_Relations) currently work. -ut
