### ISSUE TITLE
@ToMany doesn't work

### ISSUE THREAD

**Issue by wanyt** [greenrobot/greenDAO#596]
I create the entity:
@Entity
public class ModuleWatchBarTags implements NoProguard {
    private int code;
    private String message;

    @Id
    private long id;

    @ToMany(joinProperties = {
            @JoinProperty(name = "id", referencedName = "tag")
    })
    private List<EntityHomeTag> list;
}

and the EntityHomeTag like this:

@Entity
public class EntityHomeTag {
    @Id
    private long id;

    private long tag;
    private long pkSid;
    private String tagId;
    private String tagName;
}

This is the code when I storage data:

    public void storage(ModuleWatchBarTags moduleWatchBarTags) {
        
        ModuleWatchBarTagsDao cacheDao = dbSession.getModuleWatchBarTagsDao();

        cacheDao.insertOrReplace(moduleWatchBarTags);

        Query<ModuleWatchBarTags> limit = cacheDao.queryBuilder().build();

        List<ModuleWatchBarTags> list = limit.list();

        //                                                                                             null  or  1
        Logger.d("cache size>>" + list.size() + "<<tag size>>" + list.get(0).getList().size());

    }

The result is not correct. Can you help me? I trapped for two days.

**Comment by wanyt** [comment]
I hope you can provides some example about @ToOne and @ToMany.

**Comment by greenrobot-team** [comment]
I suppose you already saw the **add new related entities** part in [Resolving and Updating To-Many Relations](http://greenrobot.org/greendao/documentation/relations/#Resolving_and_Updating_To-Many_Relations). -ut
