### ISSUE TITLE
AbstractDao.updateInTx() doesn't rethrow exceptions

### ISSUE THREAD

**Issue by di72nn** [greenrobot/greenDAO#599]
The `updateInTx(Iterable<T> entities)` method doesn't throw any exception even if the update operation failed (at least in some cases).

Steps to reproduce:
Try to update an entity which should violate a `UNIQUE` constraint.

Expected result:
Transaction is rolled back. An exception is thrown.

Actual result:
Transaction is rolled back. **Method returns fine, no exceptions thrown.**

What happens inside the method:
An SQLException is caught and stored:
```
        } catch (RuntimeException e) {
            txEx = e;
        } finally {
            try {
                db.endTransaction();
            } catch (RuntimeException e) {
                if (txEx != null) {
                    DaoLog.w("Could not end transaction (rethrowing initial exception)", e);
                    throw txEx;
                } else {
                    throw e;
                }
            }
        }
```
But the exception is not re-thrown unless another exception is thrown by `db.endTransaction();` (does not happen in this case). `txEx` is lost as a result.

**Comment by greenrobot-team** [comment]
The commit that introduced this is `bebb042 Rethrow initial exception in updateInTx if endTransaction also throws`.

And yes, this will hide any exception if `db.endTransaction()` does not throw as well. -ut
