### ISSUE TITLE
About update database

### ISSUE THREAD

**Issue by kylin17** [greenrobot/greenDAO#60]
I browse the greenDAO source code, and found ths:
@Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
Is that any way to upgrade database without dropping all tables? I just need to add a table (sometimes maybe add some columns in a table) and keep old data.

**Comment by yuweiguocn** [comment]
This library may be can help you and just need one line code:https://github.com/yuweiguocn/GreenDaoUpgradeHelper
