### ISSUE TITLE
need char support

### ISSUE THREAD

**Issue by jiachenning** [greenrobot/greenDAO#600]
SUMMARY: meet issue when want to save char-type field to sqlite via greendao.

I had a char-type field "searchKey", so picked a packaged class "Character", and Character was not supported by GeenDao, then made a  convert "CharIntConverter", try to save as a Int.
Greendao think the Character should be an inner class, but in fact it is java.lang.Character

Error log

    Error:Execution failed for task ':app:greendao'.
    Inner class mypackage.entity.ZeonicCity.Character in ZeonicCity has to be static. Only static classes are supported if converters or custom types (@Convert) are defined as inner classes.

WANT: save the char type field, or make the char-to-int converter works

Source code: [the code has upload to the gist](https://gist.github.com/jiachenning/4f1afd4e903cf60c6fd4c0a9f8ea3585)

some env:

- org.greenrobot:greendao-gradle-plugin:3.2.1
- java 8
- android api 23

**Comment by greenrobot-team** [comment]
You currently can not map classes outside of the entity (like `java.lang.Character`) to [a supported type](http://greenrobot.org/greendao/documentation/custom-types/). It has to be a static class inside the entity.

As a workaround I suggest you simply use a String, or one of the [other supported types](http://greenrobot.org/greendao/documentation/custom-types/).
-ut

**Comment by greenrobot-team** [comment]
Whoops: it might be possible if you move your `CharIntConverter` into its own class. -ut

**Comment by jiachenning** [comment]
Thanks for your response. At last I use `@Transient` to treat the field ^^
