### ISSUE TITLE
should i declare a method for writing in db as synchronized?

### ISSUE THREAD

**Issue by j386621930** [greenrobot/greenDAO#604]
I have declared a method in my wrapper class for GreenDAO.

```
private boolean handleAddNewScreenInfo (List<ScreenInfo> screenInfoList) {
       ...
        ScreenInfoDBDao siDBDao = mDaoSession.getScreenInfoDBDao();
        for (ScreenInfo si : screenInfoList) {
            ScreenInfoDB siDB = encapsulateScreenInfoDBDaoItem(si);
            siDBDao.insertOrReplace(siDB);
        }
        ...
    }
```

should I declare this method as synchronized?

BTW, should I explicitly close my GreenDao sessions and DaoMaster when my application is closed?

thanks.

**Comment by greenrobot-team** [comment]
No, SQLite and therefore greenDAO is thread-safe. You only have to [be careful with queries](http://greenrobot.org/greendao/documentation/queries/#Executing_queries_in_multiple_threads) and be aware that [greenDAO caches entities](http://greenrobot.org/greendao/documentation/sessions/).

When your app is closed (by the user or Android), Android will clean up for you.

Note: There is a [basic example app](https://github.com/greenrobot/greenDAO/tree/master/examples/DaoExample) to help get you started.
-ut
