### ISSUE TITLE
关于支持多数据库

### ISSUE THREAD

**Issue by dachuwangHanKai** [greenrobot/greenDAO#605]
现在greenDao支持建立并操作两个数据库吗？

**Comment by greenrobot-team** [comment]
greenDAO works with only the one database you pass it [when creating the `DaoMaster` class](http://greenrobot.org/greendao/documentation/how-to-get-started/#Setting_up_the_database). -ut

**Comment by qbeenslee** [comment]
@dachuwangHanKai you can create new db in another module
