### ISSUE TITLE
GreenDao use existing database instead of creating one

### ISSUE THREAD

**Issue by trantronghien** [greenrobot/greenDAO#606]
I tried using GreenDao to connect the data copied from the assets folder but I get the following error.

03-09 22:47:58.269: E/SQLiteLog(3144): (1) table "FAVORITE" already exists

**Comment by greenrobot-team** [comment]
See my comment for info [about using a database from assets](https://github.com/greenrobot/greenDAO/issues/318#issuecomment-230267913). If a table already exists check the copy step and ensure it does not try to create new tables (greenDAO already does this for you). -ut
