### ISSUE TITLE
android studio 出现 org.eclipse.jdt.internal.compiler.impl.CompilerOp

### ISSUE THREAD

**Issue by zhengsh** [greenrobot/greenDAO#607]
这样配置的

**Comment by zhengsh** [comment]
apply plugin: 'com.android.application'
apply plugin: 'org.greenrobot.greendao'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.greenrobot:greendao-gradle-plugin:3.0.0'
    }
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.cqvie.greendao"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'

    compile 'org.greenrobot:greendao:3.2.0'

    testCompile 'junit:junit:4.12'
}

greendao {
    schemaVersion 1
    daoPackage 'com.cqvie.greendao.gen'
    targetGenDir 'src/main/java'
}

**Comment by zhengsh** [comment]
![Uploading image.png…]()
![aa](https://cloud.githubusercontent.com/assets/9409599/23787670/0e1f1b34-05ae-11e7-8962-ab145e43cd82.png)

**Comment by greenrobot-team** [comment]
Move this:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.greenrobot:greendao-gradle-plugin:3.0.0'
    }
}
```
to your root `\build.gradle` file where `classpath 'com.android.tools.build:gradle:2.2.3'` is defined.
(This is #498.) -ut
