### ISSUE TITLE
UNIQUE constraint on multiple columns

### ISSUE THREAD

**Issue by DanChaltiel** [greenrobot/greenDAO#608]
I want to make the combination (column1, column2, column3) UNIQUE.

I saw some posts about this on stackoverflow but they all seem outdated : [link](http://stackoverflow.com/questions/22070281/greendao-support-for-unique-constraint-on-multiple-columns/42803606#42803606), [link](https://groups.google.com/forum/#!msg/greendao/nL1GP35k9Pc/ygpA66lhUxwJ) or [link](http://stackoverflow.com/questions/32676748/how-to-create-combination-unique-key-constrain-in-greendao).

If I write `	@Index(unique = true)
	private String column1, column2, column3;`, 
it makes all 3 column uniques, not the combination.

Some links take me to an `Index` instance, but I couldn't find it (the only `Index `I can import is abstract).

How can I achieve this ?

**Comment by DanChaltiel** [comment]
OK, i figured it out, sorry for the inconvenience...
```
@Entity(
	indexes = {value = "column1,column2,column3", unique = true)}
)
```

**Comment by greenrobot-team** [comment]
Yeap, this is somewhat sneakily [documented with the `@Entity` annotation](http://greenrobot.org/greendao/documentation/modelling-entities/#The_Entity_Annotation).
-ut
