### ISSUE TITLE
Nested objects in airplane mode

### ISSUE THREAD

**Issue by giuseppefranco** [greenrobot/greenDAO#612]
Hi everybody,
after a network call (retrofit) i write my custom object in the database, then I read from database. Like this everything works.
If I kill the app, I enable the airplane mode and I start the app, the reading from the db is called but I don't have access on the nested objects that are null.

**Comment by greenrobot-team** [comment]
greenDAO does not truly support "nested" objects. These just mirror SQL relations (to-one and to-many), [read the documentation on how to use, resolve and update them](http://greenrobot.org/greendao/documentation/relations/). Hopefully that clears things up. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
