### ISSUE TITLE
Update the table part of the value of the field

### ISSUE THREAD

**Issue by htyxz8802** [greenrobot/greenDAO#615]
I'd like to update the table part of the value of the field, how to do ? I don't want to go to more entities of each attribute.

**Comment by greenrobot-team** [comment]
Sorry, I do not understand. Can you provide an example? -ut

**Comment by htyxz8802** [comment]
Sorry, I don't know how to describe it, but i have already solved.

**Comment by greenrobot-team** [comment]
Good, closing then. -ut
