### ISSUE TITLE
integrate sqlcipher with greenDAO 

### ISSUE THREAD

**Issue by unosbaghaie** [greenrobot/greenDAO#617]
I want to integrate Greendao and Sqlcipher in android studio to have an encrypted db
which I added these to my app/build.gradle

```
compile 'org.greenrobot:greendao:3.2.0' 
compile 'org.greenrobot:greendao-generator:3.2.0' 
compile 'net.zetetic:android-database-sqlcipher:3.5.6@aar'
```

And using this code to integrate it with Greendao ?

```
File path = new File(Environment.getExternalStorageDirectory(), "path/DBNamedb"); 
path.getParentFile().mkdirs(); 
DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(context, path.getAbsolutePath() , null); 
Database db = helper.getEncryptedWritableDb("password"); 
return new DaoMaster(db).newSession();
```

Am I right ?
Or I need to do something more ?

**Comment by greenrobot-team** [comment]
Comparing this with [the example](https://github.com/greenrobot/greenDAO/blob/master/examples/DaoExample/src/main/java/org/greenrobot/greendao/example/App.java), yes, that should be it. -ut
