### ISSUE TITLE
orderAsc is not working on strings containing numbers 

### ISSUE THREAD

**Issue by DanChaltiel** [greenrobot/greenDAO#618]
For some reasons, my entity must have numbers inside a String column.

I want to order them but the sorting is made only with the String constraint, so I get this : 0, 1, 10, 11, 12 etc...

There could be an option saying "my string contains numbers" in the `orderAsc()` and `orderDesc()` methods which could parse numbers and sort with them counting.

**Comment by gaoxuan** [comment]
If you use sqlite, you will get the same result. Maybe you could convert the column data to int before sort it.

**Comment by greenrobot-team** [comment]
As @gaoxuan said, this is a limitation of SQLite and how it collates strings. The viable solution is to change the property type to `Integer`. 

A workaround might also be a [raw SQL query and casting the column to an integer](http://stackoverflow.com/a/11489098) using `dao.queryRaw()`. Not sure if this works, though.
-ut

**Comment by DanChaltiel** [comment]
I finally converted my column to an integer, works like a charm
