### ISSUE TITLE
Entity table name is not being escaped in query which creates indices

### ISSUE THREAD

**Issue by Miha-x64** [greenrobot/greenDAO#622]
Hello. With this entity
```java
@Entity(
        nameInDb = "group",
//                  ^ keyword
        indexes = { @Index(value = "someColumn, otherColumn", unique = true) }
)
```

in its DAO's `createTable` method the second query will be 
```java
// Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + 
                "IDX_group_SOME_COLUMN_OTHER_COLUMN ON group" +
                //                                     ^ keyword
                " (\"SOME_COLUMN\" ASC,\"OTHER_COLUMN\" ASC);");
```
Which will lead to exception on startup. Worked around by renaming table (`nameInDb = "grp"`).

**Comment by greenrobot-team** [comment]
We should probably fix this, thanks! [According to SQLite docs](https://www.sqlite.org/lang_createtable.html):

> Table names that begin with "sqlite_" are reserved for internal use. It is an error to attempt to create a table with a name that starts with "sqlite_".

Any table name is allowed, but the above. -ut
