### ISSUE TITLE
Package name changes for DaoSession + DaoMaster on every new entity.

### ISSUE THREAD

**Issue by Codeglee** [greenrobot/greenDAO#627]
As described, every time I add a new entity the DaoMaster + DaoSession get generated in a package name rooted by the new entity.
Is this configurable? I couldn't find it in the docs.
Updating every single import to get my project to build again is a pain.

For example it was previously _com.myapp.communication.DaoSession_ and having added Booking it's moved to _myapp.booking.DaoSession_

![screen shot 2017-03-28 at 08 54 57](https://cloud.githubusercontent.com/assets/3482165/24394641/a62a549a-1394-11e7-80cf-e707b3de6656.png)

**Comment by Codeglee** [comment]
Clearly wasn't looking hard enough.

```
greendao {
    daoPackage 'com.mydestinationforgeneration'
}
```

**Comment by greenrobot-team** [comment]
For reference, this is in the [Schema section in Modelling entitities](http://greenrobot.org/greendao/documentation/modelling-entities/#Schema). -ut
