### ISSUE TITLE
Could not find method greendao() for arguments  .

### ISSUE THREAD

**Issue by a472385519** [greenrobot/greenDAO#628]
```
model {
    android {
        compileSdkVersion = 25
        buildToolsVersion = "25.0.1"

        defaultConfig.with {
            applicationId = "com.xxx.xxx"
            minSdkVersion.apiLevel = 15
            targetSdkVersion.apiLevel = 25
            versionCode = 1
            versionName = "1.0"
        }
        greendao {
            schemaVersion 1
            //daoPackage 'com.greendao.gen'
            //targetGenDir 'src/main/java'
        }
    }
}
```

**Comment by a472385519** [comment]
Why use the classpath 'com. Android. View the build: gradle - experimental: 0.9.0'Are not compatible

**Comment by greenrobot-team** [comment]
You should add the `greendao` closure outside of `android`, [see the documentation](http://greenrobot.org/greendao/documentation/modelling-entities/#Schema). -ut

**Comment by a472385519** [comment]
The greendao closure outside of android ,also can't run

**Comment by jp1017** [comment]
@a472385519 add greendao plugin in root build.gradle. see README, ok?

**Comment by a472385519** [comment]
![image](https://cloud.githubusercontent.com/assets/15272667/24734831/2b56d7dc-1ab2-11e7-8a2d-17d46937ecde.png)

**Comment by a472385519** [comment]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by a472385519** [comment]
![image](https://cloud.githubusercontent.com/assets/15272667/24735154/117513cc-1ab4-11e7-8b56-112e8b5c9cc6.png)
![image](https://cloud.githubusercontent.com/assets/15272667/24735234/80ccfba4-1ab4-11e7-9ed2-527d54a1e7a8.png)
![image](https://cloud.githubusercontent.com/assets/15272667/24735241/8b599550-1ab4-11e7-8160-7cb5ab7e0d78.png)
@jp1017

**Comment by a472385519** [comment]
@greenrobot-team This is not compatible

**Comment by a472385519** [comment]
@greenrobot-team

**Comment by greenrobot-team** [comment]
@a472385519 Apply the correct Android plugin: `apply plugin: 'com.android.application'`. You are using `apply plugin: 'com.android.model.application' which greenDAO does not support. -ut
