### ISSUE TITLE
There are no cascading deletes in greenDAO？

### ISSUE THREAD

**Issue by f630088281** [greenrobot/greenDAO#629]
Yes or No?

**Comment by Gorcyn** [comment]
No.

**Comment by f630088281** [comment]
How to cascading deletes?

**Comment by Gorcyn** [comment]
Given a user having a one-to-many relation to some addresses.
You have to manually delete entities one by one :
```Java
for (Address address : user.getAddresses()) {
    session.getAddressDao().delete(address);
}
session.getUserDao().delete(user);
```

You would rather override your `UserDAO.delete` method:
```Java
@Override
public void delete(User user) {
    for (Address address : user.getAddresses()) {
        this.session.getAddressDao().delete(address);
    }
    super.delete(user);
}
```

**Comment by f630088281** [comment]
OK   THX

**Comment by f630088281** [comment]
ToOne is not one-to-one  relation? and ToMany is not one-to-many ?
But ToOne and ToMany can made o2o , o2m and m2m  relation?

**Comment by greenrobot-team** [comment]
Answered original question, so closing.

@f630088281 Look at [the relations documentation](http://greenrobot.org/greendao/documentation/relations/) for examples. -ut

**Comment by jemshit** [comment]
What is point of ORM without cascade delete :(
