### ISSUE TITLE
Didn't find class "net.sqlcipher.database.SQLiteOpenHelper"

### ISSUE THREAD

**Issue by tututututututu** [greenrobot/greenDAO#631]
i just 
`TDaoMaster helper = new TDaoMaster(context.getApplicationContext(), path.getAbsolutePath(), null);
        Database db = helper.getWritableDb();`
i needn't Encrypte

**Comment by greenrobot-team** [comment]
You should be able to ignore this warning if you do not use database encryption. See [my comment on this](https://github.com/greenrobot/greenDAO/issues/602#issuecomment-287687252). -ut

**Comment by ddekanski** [comment]
This is a lengthy error message that is just alarming to anyone who hasn't gone through the path of adding the GreenDao themselves. False alarms are bad. Is there a way to avoid it?
