### ISSUE TITLE
Implementation Tests with GreenDao

### ISSUE THREAD

**Issue by bschnack** [greenrobot/greenDAO#636]
Hello,

We are trying to run some implementation tests with GreenDao. It appears to work just fine for two of the tests, but anymore than 2 tests and it starts to fail with the error:
> java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Illegal connection pointer 575. Current pointers for thread Thread[pool-10-thread-1,5,main] [1223]

The other weird thing is that is succeeds writing and reading to the database, but only when we try to clear out the database does it fail. The code looks like:
```
Collection<AbstractDao<?, ?>> daos = mDaoSession.getAllDaos();
            try {
                for (AbstractDao dao : daos) {
                    dao.deleteAll();
                }
            } catch (SQLiteException e) {
                AppAssert.fail("Failed to clear database", e, AppAssert.ASSERT_LEVEL_NORMAL);
            }
```

Is there special things we might need to dispose of after our tests that is causing this not to work? We do not keep the session as a singleton and the tests do create a new session every time.

**Comment by greenrobot-team** [comment]
You can [check out the example test](https://github.com/greenrobot/greenDAO/blob/master/examples/DaoExample/src/androidTest/java/org/greenrobot/greendao/example/NoteTest.java) and its super classes, notably [AbstractDaoTest](https://github.com/greenrobot/greenDAO/blob/master/DaoCore/src/main/java/org/greenrobot/greendao/test/AbstractDaoTest.java) and [DbTest](https://github.com/greenrobot/greenDAO/blob/master/DaoCore/src/main/java/org/greenrobot/greendao/test/DbTest.java). -ut

**Comment by bschnack** [comment]
Sorry, by implementation tests I meant implementation with our service. This results in us storing stuff in GreenDao to ensure that our data gets put into our database as expected and the various events get called correctly. It looks like DbTest is using another implementation to access the DB as opposed to:
`        DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, getDatabaseName(), null);
        SQLiteDatabase db = helper.getWritableDatabase();
        DaoMaster daoMaster = new DaoMaster(db);
        mDaoSession = daoMaster.newSession();`

But I tried extending DbTest and I am still hitting the same issue of the cursor eventually pointing to the wrong thread. This could be a problem with Robolectric but I was just wondering if I was missing anything here. The internet tells me that I need to kill any singletons I might have but I do not have any unless in the background you are treating sessions and stuff as a singleton.

Thanks for the quick response!

**Comment by greenrobot-team** [comment]
This was also [reported to Roboelectric](https://github.com/robolectric/robolectric/issues/3004) with the level of detail I would have expected... That Roboelectric detail would have helped.

There is a [discussion about this in Roboelectric issues](https://github.com/robolectric/robolectric/issues/1890) which has possible solutions including for greenDAO.
-ut
