### ISSUE TITLE
retrofit+greendao

### ISSUE THREAD

**Issue by JenyaKirmiza** [greenrobot/greenDAO#637]
How can i use the same model in retrofit and greendao considering that i have complex object with a lot of other objects and lists inside. Is there an elegant way to do it?

**Comment by greenrobot-team** [comment]
[This has been discussed before](http://lmgtfy.com/?q=greendao+retrofit). Also have a look at the [Relations documentation](http://greenrobot.org/greendao/documentation/relations/). -ut
