### ISSUE TITLE
Error:Execution failed for task ':app:greendao'. > org/eclipse/jdt/core/JavaCore

### ISSUE THREAD

**Issue by Witype** [greenrobot/greenDAO#638]
Error:Execution failed for task ':app:greendao'.
> org/eclipse/jdt/core/JavaCore

with
compile 'org.greenrobot:greendao:3.2.0'
classpath 'org.greenrobot:greendao-gradle-plugin:3.2.1'

how to fix it,

**Comment by greenrobot-team** [comment]
@Witype Try to update to the latest version `3.2.2`, have a look at [how to add greenDAO to your project](https://github.com/greenrobot/greenDAO#add-greendao-to-your-project) as well. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
