### ISSUE TITLE
how to count a table specify condition in a rx way

### ISSUE THREAD

**Issue by weituotian** [greenrobot/greenDAO#640]
`select count(*) from article where column='news' `
i want to do that , and in a rx way!

but 
```java
        articleDao.queryBuilder()
                .where(ArticleDao.Properties.Column.eq(name))
                .buildCount();
```

after buildCount method, why it can not using  rx and more!!!

how to deal with it?

**Comment by greenrobot-team** [comment]
RxJava is currently limited to [RxQuery](https://github.com/greenrobot/greenDAO/blob/master/DaoCore/src/main/java/org/greenrobot/greendao/rx/RxQuery.java) (what is returned by calling `rx()`). However, calling `buildCount()` creates a `CountQuery`.

I suppose one workaround would be to call `rx().list().count()`.
 -ut

**Comment by weituotian** [comment]
@greenrobot-team 
ok!
i think you can impove that way act!
if you have any improvment , please make a news!!!
