### ISSUE TITLE
help me , it cannot generates classes like DaoMaster, DaoSession and DAOs.

### ISSUE THREAD

**Issue by Jan9th** [greenrobot/greenDAO#642]
I follow Wiki to do the following:

// In my project  build.gradle file:
buildscript {
    repositories {
      // step 1 : add my repository
        mavenCentral() 
    }
    dependencies {
    // step 2 : add the plugin
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
    }
}
 
// In my modle  build.gradle file:
// step 3 : apply plugin
apply plugin: 'org.greenrobot.greendao' 

dependencies {
    //step 4 : add library
    compile 'org.greenrobot:greendao:3.2.2' 
}

but there is nothing happy, What did I ignore? thx advance.

**Comment by NanjoW** [comment]
You have to actually annotate your models with The @Entity Tags. GreenDao. Parses your models and generates the classes based on those. if you do that the files should show up.

**Comment by Jan9th** [comment]
thx ,it works.
