### ISSUE TITLE
Only static classes are supported if converters or custom types (@Convert) are defined as inner classes.

### ISSUE THREAD

**Issue by deviant-studio** [greenrobot/greenDAO#643]
plugin v3.2.2
```
* What went wrong:
Execution failed for task ':app:greendao'.
> Inner class ds.dbtests.db.greendao.UserGreenDao.OrderSerializer in UserGreenDao has to be static. Only static classes are supported if converters or custom types (@Convert) are defined as inner classes.
```
My `OrderSerializer` is a standalone class, so i don't get what is wrong. This code had been compiled ok with 3.0.0 plugin

The converter itself written in Kotlin. Maybe this is the case

**Comment by greenrobot-team** [comment]
Based on the error message `OrderSerializer` is an inline class. It should be defined as `static` to work with greenDAO. Have a look at the [documentation for Custom Types](http://greenrobot.org/greendao/documentation/custom-types/) for an example.

As for Kotlin: the greenDAO Gradle plugin only understands Java, so yes, that might confuse it.
-ut

**Comment by deviant-studio** [comment]
as i said, this is not an inline class. this is standalone class. but greendao generator treat it like internal

**Comment by greenrobot-team** [comment]
@deviant-studio Well, I suppose you should write your converter in Java then. As I said, Kotlin is not officially supported. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
