### ISSUE TITLE
could not init DAOConfig

### ISSUE THREAD

**Issue by D1191860939** [greenrobot/greenDAO#644]
"could not init DAOConfig"，I know it‘s proguard problem. So I try the proguard-rules below.
```
-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
    public static java.lang.String TABLENAME;
}
-keep class **$Properties
```

But it doesn't work for me.What should I do?Help!

**Comment by greenrobot-team** [comment]
Have a look at my comment in #338. Try to **Build > Rebuild project** in Android Studio.
-ut

**Comment by D1191860939** [comment]
I add the proguard-rules below.
-keep class xxx.dao.**{*;} 
It works for me.

**Comment by D1191860939** [comment]
I add the proguard-rules below.
-keep class xxx.dao.**{*;}(xxx is the packageName where I put the DAO class file.)
It works for me.

**Comment by greenrobot-team** [comment]
Alright, closing then. -ut

**Comment by mayuresh21** [comment]
Guys Below code is worked for me. they have given this code in there documentation.


### greenDAO 3
-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
public static java.lang.String TABLENAME;
}
-keep class **$Properties

# If you do not use SQLCipher:
-dontwarn org.greenrobot.greendao.database.**
# If you do not use RxJava:
-dontwarn rx.**

### greenDAO 2
-keepclassmembers class * extends de.greenrobot.dao.AbstractDao {
public static java.lang.String TABLENAME;
}
-keep class **$Properties
