### ISSUE TITLE
Support update for entities without primary key

### ISSUE THREAD

**Issue by vlivanov** [greenrobot/greenDAO#645]
Suppose I have en entity with compound primary key.

I am fine with using @Index with unique=true.

My problem is that I can't do daoSession.update() for that kind of entity because of " does not have a single-column primary key" assert.

The ways to resolve are the following:

1. Write my own update statement with rawQuery() - which actually eliminates the sense of greenDao usage
2. Add @CompositeKey annotation inside greenDao to address such issues
3. Add Query parameter to update() function or better provide buildUpdate() to QueryBuilder

**Comment by greenrobot-team** [comment]
greenDAO is [restricted to a single primary key of type `Long`](http://greenrobot.org/greendao/documentation/modelling-entities/#Primary_key_restrictions). If you require multiple unique properties ("keys") you can as you suggested annotate them with `@Index(unique = true)` (see the example in the link before). In that case using `dao.update()` should work just fine.
-ut

**Comment by vlivanov** [comment]
dao.update() doesn't work if we don't use any primary key at all, which is quite common. I do understand you want us to use a Long primary key as well, but that can not be done if you deal with already existent database. So Index doesn't help here. Please, reconsider the issue.

**Comment by mecoFarid** [comment]
dao.delete() gives same exception, if no primary key used.

**Comment by greenrobot-team** [comment]
In relational databases you always need a primary key (if you do not specify one, one will be created for you behind the scenes). [Here is a good explanation](http://stackoverflow.com/a/840182).

To work with greenDAO you just have to explicitly specify the primary key. This requirement is unlikely to change. -ut

**Comment by vlivanov** [comment]
Guys, I totally understand all the best practices and so on. But here is the point missed: not all of us work with the database scheme we are willing to work with. There is a word 'legacy'. Of course, it's totally up to you to require the db to have single primary key, thus making greendao very hard to use for legacy projects. So, basically it sounds like refactor your db first. Them come use greendao.

**Comment by greenrobot-team** [comment]
Maybe I'll rephrase: independent of greenDAO, with a SQLite database there always has to be a primary key. If you do not manually define one, the database will transparently do it for you. So there is little difference if you have to manually declare the primary key for greenDAO and then ignore it.

You can add your actual "key" properties and define a unique index over them and let the database assign an id by leaving it `null`. Then query/update your entities only based on your key properties, ignoring the database-specific id.

```java
@Entity
public class User {
    @Id private Long id; // internal unique ID for SQLite, do not care about this one
    @Index(unique = true) private String compositeKey1;
    @Index(unique = true) private String compositeKey2;
}
```
-ut

**Comment by greenrobot-team** [comment]
Sorry, small mistake: an index over multiple properties is created with the `@Entity` annotation. So actually the example should be:

```java
@Entity(indexes = {
    @Index(value = "compositeKey1, compositeKey2 DESC", unique = true)
})
public class User {
    @Id private Long id; // internal unique ID for SQLite, do not care about this one
    private String compositeKey1;
    private String compositeKey2;
}
```
-ut
