### ISSUE TITLE
Exception when @Entity used in Object with Serializable implementation.

### ISSUE THREAD

**Issue by mecoFarid** [greenrobot/greenDAO#646]
Trying to implement 
```
@Entity
public class StockFilterItem implements Serializable{
    private int category;

    public StockFilterItem(int category){
        this.category = category;
    }
    public int getCategory() {
        return category;
    }

    public void setCategory(int category) {
        this.category = category;
    }
}
```

But it produces error:

> Error:Execution failed for task ':app:greendao'.
> Found 1 problem(s) parsing "C:\Users\UserName\Desktop\Android\ProjectName\app\src\main\java\com\companyname\appname\model\dao\StockFilterItem.java". First problem:
Pb(96) The serializable class StockFilterItem does not declare a static final serialVersionUID field of type long (536871008 at line 13).
Run gradle with --info for more details.

**Comment by greenrobot-team** [comment]
`Serializable` classes should have a `serialVersionUID` property: 
> [...] However, it is strongly recommended that all serializable classes explicitly declare serialVersionUID values [...]

See the [`Serializable` documentation](https://docs.oracle.com/javase/8/docs/api/java/io/Serializable.html). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
