### ISSUE TITLE
Is there any way like the truncate method in MySQL?

### ISSUE THREAD

**Issue by guoqb1218** [greenrobot/greenDAO#647]

**Comment by greenrobot-team** [comment]
You should be able to use `dao.deleteAll();` which executes a `DELETE` in the background. As of SQLite 3.6.5 this [apparently works similar to `TRUNCATE` from MySQL](http://stackoverflow.com/a/14402146). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
