### ISSUE TITLE
Updating single column in a row by primary key id

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [greenrobot/greenDAO#648]
```
class Book{
   @Id(autoincrement = true)     Long id;
   @Index(unique=true)   String bookId;
   String title;
  String author;
}
Book book = new Book()
book.setBookId("1234");
book.setTitle("Java");
book.setAuthor("pradeep");

dao.insert(book);
```

For updating only title , i'm doing the following

```
List<Book> oldBooks = Bookdao.queryBuilder().where(new WhereCondition.StringCondition(bookId = "1234")).list(); 

Book book = new Book();
book.setId(oldBooks.get(0).getId());    // setting primary key
book.setTitle("Android");    
Bookdao.update(book);     // for update i have given primary key and title, remaining fields are null.
```

Greendao should update only one column with the set primary key. But it is actually overwriting all the columns. In the above example, Author and bookId fields are set to null after update.

For updating a single column if i have to pass values for all the columns, then what is the point of update, it is as good as insert on existing primary key ?

**Comment by greenrobot-team** [comment]
The query API works differently. Based on [the Queries documentation](http://greenrobot.org/greendao/documentation/queries/) your query should look like:

`List<Book> oldBooks = Bookdao.queryBuilder().where(Properties.BookId.eq("1234")).list();`
-ut

**Comment by kpradeepkumarreddy** [comment]
The following two queries are the same. Both of them will work.

List<Book> oldBooks = Bookdao.queryBuilder().where(BookDao.Properties.BookId.eq("1234")).list();
List<Book> oldBooks = Bookdao.queryBuilder().where(new WhereCondition.StringCondition(bookId = "1234")).list(); 

=> BookDao.Properties.BookId.eq("1234") will return the WhereCondition object, Instead of that in the second query i'm creating the WhereCondition object with new.

=> But my question was for updating a few columns of a row in the table, i have to set all the fields in the Book object. In the above example, Book has two fields "title" and "author". I want to update only title or author.

book.setTitle("pradeep");
bookDao.update(book); 

if i do the above code, then author column in table will be set to null, instead of retaining the existing value.

**Comment by greenrobot-team** [comment]
Sorry, I misread. After you insert an entity you will have to get/query it, then change its values, then update it. If any property is null it will be set to null.

You can use `insertOrReplace()` as [you suggested here](https://github.com/greenrobot/greenDAO/issues/32#issuecomment-293816429) which will delete an existing entity/row if a unique or primary key constraint occurs before inserting yours. However, this also requires setting all existing values.

-ut

**Comment by greenrobot-team** [comment]
No response. Closing.- ut
