### ISSUE TITLE
this library so difficult to use

### ISSUE THREAD

**Issue by tvvbbb** [greenrobot/greenDAO#652]
I don't know why constructor with @Generated will unable to delete. I found it not easy to use this libray.Only way to resolve it ,using another library.

**Comment by greenrobot-team** [comment]
You may want to have a look at the [example and documentation](http://greenrobot.org/greendao/documentation/). For an explanation of `@Generated` specifically see [Modelling entities](http://greenrobot.org/greendao/documentation/modelling-entities/#Modifying_generated_code). -ut

**Comment by tvvbbb** [comment]
I see it,but I still think is hard to use this library .It is too complex,too many annotation.I hope objectbox will resolve it.
