### ISSUE TITLE
SQLiteConnectionPool: : The connection pool for database 

### ISSUE THREAD

**Issue by fangyangdegezi88** [greenrobot/greenDAO#654]
SQLiteConnectionPool: The connection pool for database '/data/user/0/xxx/databases/xxx.db' has been unable to grant a connection to thread 732 (pool-2-thread-1) with flags 0x1 for 90.00201 seconds.
                                                                              Connections: 0 active, 1 idle, 0 available.

**Comment by greenrobot-team** [comment]
Is this possibly related to https://github.com/greenrobot/greenDAO/issues/636#issuecomment-291767811? -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
