### ISSUE TITLE
GreenDAO v.3 & above, Annotations, Android Content Provider generating

### ISSUE THREAD

**Issue by ultraon** [greenrobot/greenDAO#656]
Hello, could you please explain how can i generate content provider based on annotations of the GreenDAO v.3 without Generator project?

**Comment by greenrobot-team** [comment]
Sorry, content provider generation was experimental and is no longer supported with greenDAO 3. However, this should not stop you from writing the content provider on your own. Or just use greenDAO directly without a content provider. -ut

**Comment by greenrobot-team** [comment]
For reference, this feature is tracked in #111.
