### ISSUE TITLE
Fully specified @Transient annotation name is not working

### ISSUE THREAD

**Issue by Bringoff** [greenrobot/greenDAO#657]
I have started to use GreenDAO in project when Parceler presents. Both Parceler and GreenDAO have annotation @Transient. So I decided to use GreenDAO with its full name like `@org.greenrobot.greendao.annotation.Transient` in order to distinguish them. But when I annotate field `recurringItemInstance` in `Item` class this way I've got build error: 

`Error:Execution failed for task ':hitask:greendao'.`
`Can't add property 'Variable(type=VariableType(name=data.model.item.ItemInstance, isPrimitive=false, originalName=ItemInstance, typeArguments=null), name=recurringItemInstance)' to entity Item due to: Unsupported type data.model.item.ItemInstance`

When I changed annotation style to static import and short name code generated correctly. That class also contained fully specified `@org.parceler.Transient` annotation on one getter.

**Comment by greenrobot-team** [comment]
Thanks for catching this! As a workaround you might try using the `transient` modifier keyword instead of the `@Transient` annotation.

Such as `transient ItemInstance recurringItemInstance;`.

-ut

**Comment by greenrobot-team** [comment]
`3.3.0` has been released which should fix this issue.
https://greenrobot.org/greendao/changelog/
