### ISSUE TITLE
Make greenDAO consider primitive long id with value 0 as not stored to database

### ISSUE THREAD

**Issue by Bringoff** [greenrobot/greenDAO#659]
I have an entity with primitive long id (which of course implicitly has default 0 value in Java) and trying to call `insertOrUpdate` multiple times, only one entity is stored into database with id 0, which means that after every call old record with this id was replaced with new. If call `insert` method I get error `PRIMARY KEY must be unique`. My question is how make greenDAO consider `0` as default value and make new id generation operation. Because with object `Long` it works as expected but I have a lot of code which uses 0 value as "not stored yet".

**Comment by greenrobot-team** [comment]
Changing this behavior now has the potential to break a lot of existing code. If you need to use `long` you need to ensure yourself that you insert with a valid id. -ut
