### ISSUE TITLE
Missing "apply plugin: maven"

### ISSUE THREAD

**Issue by noordawod** [greenrobot/greenDAO#664]
I use a fork of your library and incorporating it into my project from a local source tree. 

I had to add `apply plugin: maven` following [this line](https://github.com/greenrobot/greenDAO/blob/master/greendao-api/build.gradle#L1) in order to make my program compile. If you notice down this same file, you have a call to `mavenDeployer` and that will be unknown unless maven plugin is applied.

**Comment by greenrobot-team** [comment]
The maven plugin is [applied from the root `build.gradle` config](https://github.com/greenrobot/greenDAO/blob/master/build.gradle#L31-L32). Thanks though! -ut

**Comment by noordawod** [comment]
Ahh, right :) I'll try to replicate this behavior, thanks @greenrobot-team!
