### ISSUE TITLE
queryBuilder.limit returning first records from table

### ISSUE THREAD

**Issue by slickorange** [greenrobot/greenDAO#666]
If I do 
```
myDao(.this).queryBuilder()
                .limit(30)
                .list();
```
I get the first 30 records in the table... Is this how limit is supposed to work?
How do I get the latest 30 records in the table?

**Comment by greenrobot-team** [comment]
Yes, [this is how limit works](http://greenrobot.org/greendao/documentation/queries/#Limit_Offset_and_Pagination). To get the last few entries you may try to order your results differently (possibly by id). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
