### ISSUE TITLE
Duplicate name for ToOne

### ISSUE THREAD

**Issue by ArthurReinhart** [greenrobot/greenDAO#671]
Im trying to learn using greenDAO, followed some tutorials, and finally know how to generate a database with the generator, but found an issue trying to make two relations to the same table, i'm trying to do a string mapping

I have a table 'data' with some values and a table 'datamap' which i want 2 foreign keys to data , source_id and dest_id but i get the Duplicate name for ToOne error while trying to compile.

        Schema schema = new Schema(1, "com.learning.test.db");

        Entity data_entity = schema.addEntity("data");
        data_entity.addIdProperty();
        data_entity.addBooleanProperty("active");
        data_entity.addStringProperty("name");

        Entity datamap_entity = schema.addEntity("datamap");
        datamap_entity.addIdProperty();

        Property data_src = datamap_entity.addLongProperty("data_src_id").getProperty();
        datamap_entity.addToOne(data_entity,data_src);

        // Error in this relation
        Property data_dest = datamap_entity.addLongProperty("data_dest_id").getProperty();
        datamap_entity.addToOne(data_entity,data_dest);

**Comment by greenrobot-team** [comment]
If you [have multiple ToOne relations you have to name them](http://greenrobot.org/greendao/documentation/generator/#To-One_relations_11). -ut

**Comment by ArthurReinhart** [comment]
Ok, so now is working fine, thank you.

I have replaced datamap_entity.addToOne(data_entity,data_dest);
`datamap_entity.addToOne(data_entity,data_dest);`
With:
`datamap_entity.addToOne(data_entity,data_dest,"data_dest");`
