### ISSUE TITLE
not found 

### ISSUE THREAD

**Issue by kangdawei** [greenrobot/greenDAO#673]
in RxDao not found

import rx.Observable;
import rx.Scheduler;

//my gradle
compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
compile 'io.reactivex.rxjava2:rxjava:2.0.9'
compile 'org.greenrobot:greendao:3.2.0'

is rxandroid version ?

**Comment by greenrobot-team** [comment]
@kangdawei Have a look at [the example project](https://github.com/greenrobot/greenDAO/blob/master/examples/RxDaoExample/build.gradle). greenDAO only supports RxJava 1. -ut
