### ISSUE TITLE
Before I save thedata ,

### ISSUE THREAD

**Issue by MoonlightSW** [greenrobot/greenDAO#677]
I have a class ,like this :
```
   public class Bean {
    List<List<Integer>> peaks;
    List<Double> dataArray;
    List<Double> dataSourceArray;
   }
```

and there are many data , so I want to transform list to string before save to the database,

and when I read from database ,I need transform string to list,

what should i do?

**Comment by greenrobot-team** [comment]
This can probably be solved [using custom types](http://greenrobot.org/greendao/documentation/custom-types/). Though it would mean having to replace the `List<>` types with for example a custom type/wrapper that contains that list. Something like:

```
   public class Bean {
    Peaks peaks;
    DataArray dataArray;
    DataArray dataSourceArray;
   }
```
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
