### ISSUE TITLE
where to find an example of database upgrade

### ISSUE THREAD

**Issue by mattjma** [greenrobot/greenDAO#679]
Is there an example of official greenDao upgrade？ It is hard to find a kind of than example, most found are old version. And i find out that the upgrade of greenDao is heavy

**Comment by greenrobot-team** [comment]
This is not really specific to greenDAO, but rather SQLite on Android. You upgrade your database by overriding `onUpgrade()` in your SQLiteOpenHelper. I found [an example here](https://thebhwgroup.com/blog/how-android-sqlite-onupgrade). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
