### ISSUE TITLE
Error:NullPointerException

### ISSUE THREAD

**Issue by angersad** [greenrobot/greenDAO#680]
I build the project.but tell me NullPointerException:

```
public class ChatDbManager extends BaseManager<ChatMessageBean,Long> {
    @Override
    public AbstractDao<ChatMessageBean, Long> getAbstractDao() {
        return daoSession.getChatMessageBeanDao();
    }
}

return daoSession.getChatMessageBeanDao(); 


Caused by: java.lang.NullPointerException
at com.example.zjy.myimui.manager.ChatDbManager.getAbstractDao(ChatDbManager.java:12)
at com.example.zjy.myimui.manager.BaseManager.getPages(BaseManager.java:260)
at com.example.zjy.myimui.MainActivity.initEvent(MainActivity.java:203)
at com.example.zjy.myimui.MainActivity.onCreate(MainActivity.java:142)
```

**Comment by angersad** [comment]
line 12 is Error line

**Comment by angersad** [comment]
The Error line is return daoSession.getChatMessageBeanDao();

**Comment by greenrobot-team** [comment]
Well then I would suggest that your `daoSession` variable is `null`? Try [debugging your code in Android Studio](https://developer.android.com/studio/debug/index.html). -ut

**Comment by angersad** [comment]
but I use ctrl+click could into the DaoSession class

**Comment by greenrobot-team** [comment]
@angersad Just because the class is there at compile time/in your IDE does not mean there has to be an instance at runtime/when the app is running. Closing as this is a development issue, not a greenDAO issue. -ut
