### ISSUE TITLE
ToMany no effect

### ISSUE THREAD

**Issue by tvvbbb** [greenrobot/greenDAO#682]
I add ToMany like this
`    @ToMany(referencedJoinProperty = "projectId")`
`    private List<DrugInfo> medicines;`

DrugInfo.class  like this
`private long dosageId;`

I have insert medicines,but why I call ProjectEntitiyDao.loadAll(),medicines is null.

**Comment by greenrobot-team** [comment]
Read the [To-Many documentation](http://greenrobot.org/greendao/documentation/relations/#Modelling_To-Many_Relations), including the section afterwards about **Resolving and Updating To-Many Relations**. Hopefully that will clear things up. -ut

**Comment by tvvbbb** [comment]
Thanks.It is my fault.
