### ISSUE TITLE
how to execSQL like update T set column='value' where..

### ISSUE THREAD

**Issue by gosttusng** [greenrobot/greenDAO#684]
I want to update a  column in a table ;
I can't find APIS about this.
Or how to get greendao's db to excute a sql like update t_student set name = 'Jams' where id = '001';
Plz,thanks.

**Comment by greenrobot-team** [comment]
greenDAO maps your SQLite database to Java classes (entities) so you can work with Java objects instead. So query for the entity you are looking for, change the properties on the entity class, then update the database using its DAO class.

A quick example:
```java
// query for entities
List<User> users = userDao.queryBuilder()
        .where(UserDao.Properties.IsAdmin.eq(1))
        .list();
// change desired entitiy
User user = users.get(0);
user.setFirstname("New First Name");
// update database
userDao.update(user);
```
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
