### ISSUE TITLE
There are internal classes in the entity class

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [greenrobot/greenDAO#685]
There are internal classes in the entity class，How to deal with this situation?
![tim 20170522155748](https://cloud.githubusercontent.com/assets/15881869/26297887/876e8640-3f07-11e7-9726-f5266f52ace9.png)

**Comment by greenrobot-team** [comment]
This is not supported. You have to move the `Data` class to its own file and make it an upper class. -ut
