### ISSUE TITLE
Entity generator is not 1:1 with the old Dao classes

### ISSUE THREAD

**Issue by slott** [greenrobot/greenDAO#686]
With the good old generator script I would get this

        public final static Property Local_id = new Property(0, Long.class, "local_id", true, "LOCAL_ID");

with the new gradle generator I get this

        public final static Property Local_id = new Property(0, Long.class, "local_id", true, "_id");

Since we have a bit of hardcoded SQL to help speed things up they kinda blew up since the local_id is now named _id.

Not sure if this is what you intended - but in my book it feels a bit off.

**Comment by greenrobot-team** [comment]
Yes, the default is to name the column for the property annotated with `@Id` as `_id`. This helps ensure the database may be used with a `ContentProvider`. However, you can define your own column name by adding the `@Property` annotation:

```
@Id
@Property(nameInDb = "LOCAL_ID")
private Long local_id;
```
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
