### ISSUE TITLE
Issue with relations.

### ISSUE THREAD

**Issue by pedrovic90** [greenrobot/greenDAO#688]
Are the relations for any use? For what I've seen as far, the @ToOne relationship does nothing on insert so it also does nothing on loadAll

**Comment by ouyangzn** [comment]
When you insert, you should insert 2 data, just like:
```java
class A {
  @ToOne class B;
  ...
}
class B {
   ...
}

insert A;
insert B;
```

**Comment by pedrovic90** [comment]
but will the getAll A retrieve the Bs inside?

2017-05-25 6:26 GMT-03:00 ouyangzn <notifications@github.com>:

**Comment by ouyangzn** [comment]
[documents](http://greenrobot.org/greendao/documentation/relations/)
Use _loadDeep()_ or _queryDeep()_ to load B immediately, otherwise B will be loaded lazy when you call _getB()_.
You can have a look at the method getB() generated by greenDao.

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
