### ISSUE TITLE
Gradle sync failed by use  apply plugin: 'org.greenrobot.greendao'

### ISSUE THREAD

**Issue by krmao** [greenrobot/greenDAO#689]
```
classpath 'com.android.tools.build:gradle:2.2.3'
classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
```
Gradle sync failed: Cause: org.gradle.api.tasks.TaskInputs.file(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskInputFilePropertyBuilder;

Error:Unable to find method 'org.gradle.api.tasks.TaskInputs.file(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskInputFilePropertyBuilder;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by greenrobot-team** [comment]
Please update your Android Gradle Plugin to 2.3.2 (`com.android.tools.build:gradle:2.3.2`). Version 2.2.x is not supported. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
