### ISSUE TITLE
How to Export and Import the data using GreenDAO?

### ISSUE THREAD

**Issue by BharathirajaPerumal** [greenrobot/greenDAO#690]
I want to export the database and data. Then I want import the data I exported. How to perform export and import data (Backup and Restore) using Greendao?

**Comment by greenrobot-team** [comment]
greenDAO has no built-in support for this, it is just a layer on top of your SQLite database. It is up to you how to do this (like export to a JSON model). -ut

**Comment by hasnain-ahmad** [comment]
@greenrobot-team Please provide/suggest/guide some solution for backup and restore the database. 
It will be very helpful if you add the said functionality in the library.

**Comment by lzyang187** [comment]
Hello, how do you implement backup and restore?

**Comment by hasnain-ahmad** [comment]
@greenrobot-team @greenrobot  any update regarding adding the functionality ( Import/Export
of the database)?

**Comment by hasnain-ahmad** [comment]
> greenDAO has no built-in support for this, it is just a layer on top of your SQLite database. It is up to you how to do this (like export to a JSON model). -ut

Dear Team [ActiveAndroid](https://github.com/pardom-zz/ActiveAndroid/wiki/Pre-populated-databases) provide this functionality. It is humble request please also add this functionality in your library.
