### ISSUE TITLE
create a new table

### ISSUE THREAD

**Issue by lujianzhao** [greenrobot/greenDAO#691]
how do I dynamically create a new table during the APP operation?
The same entity creates multiple tables with different table names

**Comment by greenrobot-team** [comment]
This is not supported by greenDAO. Your `@Entity` classes are each mapped to one table at compile time. If you want to add additional tables at runtime you have to use plain SQL commands.

To add additional tables when first setting up your database, override the `onCreate()` method on your `DaoMaster.OpenHelper` implementation. See the Android docs on [using a SQL Helper](https://developer.android.com/training/basics/data-storage/databases.html#DbHelper).
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
