### ISSUE TITLE
Something wrong about @ToMany

### ISSUE THREAD

**Issue by tvvbbb** [greenrobot/greenDAO#695]
```
@Entity
public class Customer {
    @Id private Long id;
 
    @ToMany(referencedJoinProperty = "customerId")
    @OrderBy("date ASC")
    private List<Order> orders;
}
 
@Entity
public class Order {
    @Id private Long id;
    private Date date;
    private long customerId;
}
```

I follow official code to write @ToMany.But when I insert Customer, Order can not insert.Table order is nothing.

**Comment by greenrobot-team** [comment]
You have to insert your orders manually. Have a look at the topic [Resolving and Updating To-Many Relations](http://greenrobot.org/greendao/documentation/relations/#Resolving_and_Updating_To-Many_Relations). -ut

**Comment by tvvbbb** [comment]
Why not do this auto?

**Comment by greenrobot-team** [comment]
This allows you more freedom in deciding what data to update. For example, if you just want to change the name of your `Customer` you would have to load and save all the related orders each time. This is a lot of unnecessary overhead. So greenDAO leaves it to you to decide what and how much to do.

There are also [some good notes on this here](https://developer.android.com/topic/libraries/architecture/room.html#no-object-references).

So closing this then.
-ut

**Comment by tvvbbb** [comment]
Thanks a lot .
