### ISSUE TITLE
anbout encrypt and no-encryption

### ISSUE THREAD

**Issue by chenfgit** [greenrobot/greenDAO#697]
Excuse me,
 when use greenDAO, I  want some import tables to encrypt and the other  no-encryption for high performance,how do I do?

**Comment by greenrobot-team** [comment]
If you do not mind sharing the database schema, this might be possible using a separate database (file) and two separate sessions. A regular and another encrypted one. Though I have never tried this and some internal greenDAO stuff might prevent it.

```java
Database db = dbHelper.getWritableDb();
daoSession = new DaoMaster(db).newSession();
Database dbEncr = dbHelperEncr.getEncryptedWritableDb("password");
daoSessionEncr = new DaoMaster(dbEncr).newSession();
```
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
