### ISSUE TITLE
@JoinEntity Goes Wrong Due to Package Issue

### ISSUE THREAD

**Issue by hwding** [greenrobot/greenDAO#698]
`@JoinEntity` gives an error during compiling when the joined entity class is not under the same package with presnet entity class.
```java
@NotNull
@ToMany
@JoinEntity(
    entity = UserToOrderMapper.class,
    sourceProperty = "userId",
    targetProperty = "orderId"
)
private List<Order> orders;
```
When `User` is in package `model` while `UserToOrderMapper` is in package `mapper`:

```
Error:(...) error: package UserToOrderMapperDao.Properties does not exist
```
The interesting thing is that the built file which gives the error can be fixed simply by importing the relevant package.

When `UserToOrderMapper` is in the same package as `User`, everything is OK.

**Comment by greenrobot-team** [comment]
Currently greenDAO requires you to have all your `@Entity` classes in the same package. This includes the join entities. -ut
