### ISSUE TITLE
AbstractDao does not honor the unique constraint in IdentityScope cache

### ISSUE THREAD

**Issue by eastwindDC** [greenrobot/greenDAO#699]
When i set a unique constraint to a column which is not a primary key.Then i perform abstractDao insertOrReplace method with a identical entity.The entity's primary key id is autoincrement,so the entity' id is not same. The entity in identityScope will not be replaced which is not right for i set the unique

**Comment by greenrobot-team** [comment]
@eastwindDC Not sure I understand correctly. But if you make sure that the primary key/id remains the same, the entity should be correctly replaced in the database and the identity scope.

So check that the primary key/id is not `null` before calling `insertOrReplace()`. -ut
