### ISSUE TITLE
Database.isOpen()

### ISSUE THREAD

**Issue by cherrydev** [greenrobot/greenDAO#700]
It would be great if the Database interface exposed the `.isOpen()` method of the delegate. I'm dealing with an app that uses AccountManager and has separate databases for each user. When an account is deleted, a callback deletes the underlying database, but if the app is still running, when my Activity resumes it needs to check if the database is still open. I can do it by getting the raw database and then casting it (to one of two implementation classes, depending on if it's encrypted or not) but it seems like adding `.isOpen()` to the interface should be straightforward.
I'd be happy to submit a pull request for it if the idea is approved. Thanks.

**Comment by greenrobot-team** [comment]
@cherrydev The built-in `StandardDatabase` and `EncryptedDatabase` always return a `SQLiteDatabase`. So you should be safe to cast `Database#getRawDatabase` to `SQLiteDatabase` and call `isOpen()` on it. -ut

**Comment by cherrydev** [comment]
There are two SQLiteDatabase classes in two different packages, one for the standard, one for the encrypted.  There is no common interface or subclass for these two SQLiteDatabase classes. Therefore a single call to isOpen() requires code for two `instanceof` expressions and two casts. The `Database` interface has a `close()` method on it. Why not `isOpen()`?

**Comment by greenrobot-team** [comment]
Sorry, I missed the different package for `SQLiteDatabase`. Suggested a change. Thanks! -ut

**Comment by cherrydev** [comment]
Thanks!

**Comment by greenrobot-team** [comment]
`3.3.0` has been released which includes the above change.
https://greenrobot.org/greendao/changelog/
