### ISSUE TITLE
how to custom DaoMaster and other generated classes

### ISSUE THREAD

**Issue by sevenshal** [greenrobot/greenDAO#705]
I'm using greendao-gradle-plugin to generate classes now. I want to change the generated classes using some custom import. For example i want to use my.own.wrap.database.SQLiteDatabase instead of android.database.sqlite.SQLiteDatabase in class DaoMaster. How cat i do that.
I want to fork the source of greendao-gradle-plugin, but not found of it.

**Comment by greenrobot-team** [comment]
You can construct `DaoMaster` with `DaoMaster(Database db)`. As long as it implements [`Database`](https://github.com/greenrobot/greenDAO/blob/master/DaoCore/src/main/java/org/greenrobot/greendao/database/Database.java) you can pass any database you want. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
