### ISSUE TITLE
List of a entity class as property in another entity class

### ISSUE THREAD

**Issue by ShrikantBadwaik-007** [greenrobot/greenDAO#706]
I have a entitiy class Ticket and I want a List<Ticket> tickets as a Proerty in another entity class card. How can do this operation?
Card:

@Entity
public class Card {
    @Id
    @JsonProperty("id")
    private long id;
    @Property
    @JsonProperty("alias")
    private String aliasName;
    @Property
    @JsonProperty("card_number")
    private String cardNo;
    @Property
    @JsonProperty("expiry")
    @JsonDeserialize(using = DateUtil.CardDateDeserializer.class)
    private Date expiryDate;
    @Property
    @JsonProperty("type")
    private String cardType;

    **I WANT ticketlist AS A PROPERTY IN CARD**
    private List<Ticket> ticketList;
}

Ticket:

@Entity
public class Ticket {
    @Id
    @JsonProperty("id")
    private long id;
    @Property
    @JsonProperty("seller_name")
    private String sellerName;
    @Property
    @JsonProperty("description")
    private String description;
    @Property
    @JsonProperty("seating_class")
    private String seatingClass;
    @Property
    @JsonProperty("type")
    private String type;
    @Property
    @JsonProperty("seasonal_pass")
    private String seasonalPass;
    @Property
    @JsonProperty("expiry")
    @JsonDeserialize(using = DateUtil.TicketDateDeserializer.class)
    private Date expiryDate;
    @Property
    @JsonProperty("theater_group")
    private String theaterGroup;
    @Property
    @JsonProperty("head_count")
    private int headCount;
    @Property
    @JsonProperty("last_used")
    @JsonDeserialize(using = DateUtil.TicketDateDeserializer.class)
    private Date lastUsedDate;
    @Property
    @JsonProperty("status")
    private String status;
    @Property
    @JsonProperty("block_count")
    private int blockCount;
    private boolean isDescriptionVisible;
    @Property
    @JsonProperty("card_id")
    private long cardId;
    @Property
    @JsonProperty("pack_count")
    private int packCount;
    @Property
    @JsonProperty("pack_used")
    private int packUsed;
    @Property
    @JsonProperty("ticket_bought")
    @JsonDeserialize(using = DateUtil.TicketBoughtDateDeserializer.class)
    private Date ticketBoughtDate;
}

**Comment by greenrobot-team** [comment]
This is done using relations in relational databases, which greenDAO can help you with. Have a look at [the Relations documentation](http://greenrobot.org/greendao/documentation/relations/). -ut
