### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by tututututututu** [greenrobot/greenDAO#709]
I get db in this way:
Database db = helper.getWritableDb();

but sametimes when i install apk to sunsumg phone
crashed  and log show 
attempt to write a readonly database

i never call readabledb

**Comment by greenrobot-team** [comment]
If it does not occur on other devices, this sounds like an issue with the firmware of that Samsung device? Try to gather additional information (add logging, or similar) and/or try to handle the exception and show an error message to the user asking to report details about the issue.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by tututututututu** [comment]
07-31 09:43:21.170 29268 29268 W System.err: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
--
2407-31 09:43:21.170 29268 29268 W System.err: at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
2507-31 09:43:21.170 29268 29268 W System.err: at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
2607-31 09:43:21.170 29268 29268 W System.err: at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
2707-31 09:43:21.170 29268 29268 W System.err: at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
2807-31 09:43:21.170 29268 29268 W System.err: at org.a.a.a.executeInsertInTx(AbstractDao.java)
2907-31 09:43:21.170 29268 29268 W System.err: at org.a.a.a.insertOrReplaceInTx(AbstractDao.java)
3007-31 09:43:21.170 29268 29268 W System.err: at org.a.a.a.insertOrReplaceInTx(AbstractDao.java)

**Comment by tututututututu** [comment]
the crash msg

**Comment by tututututututu** [comment]
not must crash but the conditon I can not find out

**Comment by greenrobot-team** [comment]
Sorry, I am not familiar with this issue. I found a [possibly related Android issue](https://issuetracker.google.com/issues/37047677). Most often the issue seems to be that the database file is modified. Your best bet is searching Google. -ut

**Comment by bxjxxyy** [comment]
I got this error too.On my XiaoMi phone.Have  u solved this problem yet?
