### ISSUE TITLE
 Could not find class 'xxx.DaoMaster$DevOpenHelper', referenced from method xxx.db.GreenDaoManager.

### ISSUE THREAD

**Issue by KevinDestinydoor** [greenrobot/greenDAO#711]
could not find class 'com.xx.DaoMaster$DevOpenHelper', referenced from method com.xx.db.GreenDaoManager.<init>
04-19 07:10:15.021 24631-24631/com.xx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.NoClassDefFoundError: com.xx.DaoMaster$DevOpenHelper

**Comment by KevinDestinydoor** [comment]
It  has no  error  on  API 25  but  It  show this  message  Under 25

**Comment by greenrobot-team** [comment]
See [my comment here](https://github.com/greenrobot/greenDAO/issues/681#issuecomment-310967828). In any case this is likely an issue with your build setup, so not sure how much I can help. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
