### ISSUE TITLE
how  to  set  composite primary key？

### ISSUE THREAD

**Issue by wxy520ll** [greenrobot/greenDAO#712]
I have to set  composite primary key. how to do  it?  set tow @Id on fileds?

**Comment by greenrobot-team** [comment]
Keep the regular `@Id Long id`. But [define a unique index over the properties](http://greenrobot.org/greendao/documentation/modelling-entities/#Primary_key_restrictions) that you want to use as the actual identifier:

```java
@Entity(      
        // Define indexes spanning multiple columns here.
        indexes = {
                @Index(value = "prop1 DESC, prop2 DESC", unique = true)
        }
)
public class YourEntity {
    @Id Long id;
    Integer prop1;
    Long prop2;
  ...
}
```

**Comment by greenrobot-team** [comment]
Thumbs up, so closing. -ut
