### ISSUE TITLE
New Table Generation Issue

### ISSUE THREAD

**Issue by Grk26** [greenrobot/greenDAO#713]
Earlier I am using greendao with 5 tables with library 'org.greenrobot:greendao:3.2.0' now due to some changes i am using 7 tables so if i install fresh app these two new tables are generated and working properly if i upgrade older apk then it generates this Error:

E/SQLiteLog: (1) no such table:

**Comment by greenrobot-team** [comment]
You need to make sure your `OpenHelper` implements the `onUpgrade()` method and adds the missing tables. Also ensure to increase your schema version (= database version, you can get it from `DaoMaster.SCHEMA_VERSION`).

This is not really specific to greenDAO, but rather SQLite on Android. I found [an example using SQLiteOpenHelper here](https://thebhwgroup.com/blog/how-android-sqlite-onupgrade). -ut

**Comment by Grk26** [comment]
but i change schema version it clears all previous data but i want to retain by data should i write my own migration code ??

**Comment by greenrobot-team** [comment]
Make sure you are not using the `DaoMaster.DevOpenHelper`. Its `onUpgrade()` method clears all data when the database/schema version changes. Implement your own open helper by subclassing `DaoMaster.OpenHelper`. -ut

**Comment by Grk26** [comment]
Done, Thanks



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=grk4675@gmail.com&idSignature=22>

Regards

Gourav Mehta
9024685946
7014269983
