### ISSUE TITLE
 “@Unique”   dosen't    work

### ISSUE THREAD

**Issue by wxy520ll** [greenrobot/greenDAO#716]
`@Entity(createInDb = false,active = true,indexes = {@Index(value = "KH", unique = true)})
public class FZHB implements Serializable{
@Id
	private Long id;

@Unique
	private String KH;//
}`

please tell me the reason for the mistake

**Comment by wxy520ll** [comment]
1

**Comment by greenrobot-team** [comment]
I suppose you already read [the documentation about this for `@Unique`](https://github.com/greenrobot/greenDAO/blob/V3.2.2/greendao-api/src/main/java/org/greenrobot/greendao/annotation/Unique.java#L17-L18). -ut
