### ISSUE TITLE
Can I use the date query?

### ISSUE THREAD

**Issue by momoc** [greenrobot/greenDAO#718]
Can I use the date query?

**Comment by chun19921004** [comment]
hi

**Comment by greenrobot-team** [comment]
Not sure what you mean. Do you have an example? You might want to have a look at [the Queries documentation](http://greenrobot.org/greendao/documentation/queries/). -ut

**Comment by momoc** [comment]
Sorry, query according to date type when querying……
![image](https://user-images.githubusercontent.com/8325226/27783042-41045830-6007-11e7-9938-e549443fad75.png)
For example, I would like to inquire about the birthday is 1990, the query conditions how to write?

**Comment by greenrobot-team** [comment]
As I said you can use [the Queries API](http://greenrobot.org/greendao/documentation/queries/). A simple example:
```java
long currentTime = System.currentTimeMillis();
Date aDayAgo = new Date(currentTime - DateUtils.DAY_IN_MILLIS);
Date inADay = new Date(currentTime + DateUtils.DAY_IN_MILLIS);
List<Note> results = noteDao.queryBuilder()
        .where(NoteDao.Properties.Date.gt(aDayAgo), NoteDao.Properties.Date.lt(inADay))
        .build()
        .list();
```
-ut

**Comment by momoc** [comment]
If I just want to check my birthday in July……
for example：
birthday：1980-07-20 15:20:20
query criteria（SQL）：like %-07-% （Just want to check the month）
the query conditions how to write?

**Comment by greenrobot-team** [comment]
greenDAO stores `Date` as a millisecond value. The above is not possible. Use the Query API. -ut

**Comment by momoc** [comment]
Oh, thank you......
