### ISSUE TITLE
Get Property metadata by name (instead of Dao.Properties.name)

### ISSUE THREAD

**Issue by zhuxiaogit** [greenrobot/greenDAO#720]
can u add "extra method" what obtain Property by appointed field name  ?

**Comment by greenrobot-team** [comment]
I'm not sure what you mean. Do you have an example? -ut

**Comment by zhuxiaogit** [comment]
i just save named EventDTO entity to sqliteDb,it contain id and other fields.
so existed EventDTODao, and can get EventDTODao.Properties.Id.
finally,i hope get it by this formart EventDTODao.getProperty("id"). can u?

**Comment by greenrobot-team** [comment]
This is not possible as the properties are not iterable right now. Though you might create a `Map<String,Property>` yourself and simply insert all properties of a DAO. -ut
