### ISSUE TITLE
Problem build app in windows and mac

### ISSUE THREAD

**Issue by emanuellopes** [greenrobot/greenDAO#726]
Hi, i just develop my app in linux, but i move to Mac Book Computer. I tried to compile my app in mac but greenDao not generate the main class of BD. but this also affect Windows.
All entity
```
import pt.ipleiria.estg.dei.mobilis.data.entity.DaoSession; //problem build that class
import pt.ipleiria.estg.dei.mobilis.data.entity.LineEntity;
import pt.ipleiria.estg.dei.mobilis.data.entity.LineStopEntity;


public class CacheMobilisDataStore implements MobilisDataStore {
    private DaoSession daoSession; //problem here

    public CacheDataStore(DaoSession daoSession) {
        this.daoSession = daoSession;
    }
```

Other class Entity is build correctly, i do not why this happens

cumps

**Comment by greenrobot-team** [comment]
How do you compile? If you are using Android Studio try to click "Rebuild project" in the "Build" menu.

Also check that you are using the [latest versions of the library and Gradle plugin](https://github.com/greenrobot/greenDAO#add-greendao-to-your-project). -ut

**Comment by emanuellopes** [comment]
the issue just happened, because i have two packages with Entitys, in linux my DaoMaster and DaoSession is builded in main folder, but in mac and windows is builded in my subpackage. that's the problem.  like main folder ->entity1.java, entity2.java and subpackage test->Entity3.java.
thank's for helping

**Comment by greenrobot-team** [comment]
Assuming you are using the Gradle plugin: check if you have set a value for `targetGenDir` in your Gradle build config and that it points to the correct directory. Even if it is not set, you can try to set it to force generation to the correct directory. See [the schema documentation](http://greenrobot.org/greendao/documentation/modelling-entities/#Schema) for details.

Note that [with the new Gradle plugin it is recommended](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#Step_2_Use_entity_annotations) to not set this property and not check in the `DaoMaster` and `DaoSession` files. Instead use the files generated to the build folder when building the project. -ut

**Comment by greenrobot-team** [comment]
No response. Closing.

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
