### ISSUE TITLE
Can't set custom collation with QueryBuilder.stringOrderCollation and SQLCipher

### ISSUE THREAD

**Issue by dvolodin** [greenrobot/greenDAO#727]
I've created (https://sqlite.org/c3ref/create_collation.html) and successfully registered a new collation algorithm, but [this check](https://github.com/greenrobot/greenDAO/blob/master/DaoCore/src/main/java/org/greenrobot/greendao/query/QueryBuilder.java#L126) prevents creation of queries that use it or any other collation but the default. Judging by [this comment](https://github.com/greenrobot/greenDAO/blob/master/DaoCore/src/main/java/org/greenrobot/greendao/query/QueryBuilder.java#L125) this seems intended only for [preferLocalizedStringOrder](https://github.com/greenrobot/greenDAO/blob/master/DaoCore/src/main/java/org/greenrobot/greendao/query/QueryBuilder.java#L110).

**Comment by greenrobot-team** [comment]
Thanks for reporting this. I submitted a patch (#730) to allow setting collations even if SQLCipher is used. -ut

**Comment by greenrobot-team** [comment]
`3.3.0` has been released which includes the above change.
https://greenrobot.org/greendao/changelog/
