### ISSUE TITLE
multi thread ,query data is use cache，doesn't update

### ISSUE THREAD

**Issue by lzhAndroid** [greenrobot/greenDAO#729]
when I update the data on io thread and use forCurrentThread().list() requery it on main thread,the data doesn't change.I think it maybe use the cache with main thread,but what can i do,the data will be update?

**Comment by greenrobot-team** [comment]
You may try to clear the session cache after updating the data. See the [documentation on clearing the identity scope in Sessions](http://greenrobot.org/greendao/documentation/sessions/#Clear_the_identity_scope). -ut

**Comment by lzhAndroid** [comment]
thx.
