### ISSUE TITLE
how to use greendao in library?

### ISSUE THREAD

**Issue by suikatomoki** [greenrobot/greenDAO#733]
in library, i can not found some class like 'DaoMaster' 'DaoSession'...
![qq 20170721160326](https://user-images.githubusercontent.com/10336224/28454531-3196013e-6e2e-11e7-975a-2fb287eeab2e.png)
![qq 20170721160342](https://user-images.githubusercontent.com/10336224/28454532-319cf782-6e2e-11e7-899f-5865972a06ce.png)

**Comment by greenrobot-team** [comment]
[I just tried this](https://github.com/greenrobot-team/greenrobot-examples/tree/master/greendao-library) and it works fine. Did you make sure to [add the greenDAO Gradle plugin to your root `build.gradle` file](http://greenrobot.org/greendao/documentation/introduction/)? -ut

**Comment by suikatomoki** [comment]
@greenrobot-team 
thx , it's work now , just my mistakes
