### ISSUE TITLE
To develop third lib,but use GreenDao ,should i let the my developers to compile the GreenDao?

### ISSUE THREAD

**Issue by BeautyKael** [greenrobot/greenDAO#734]
To develop third lib,but use GreenDao ,should i let my developers compile the GreenDao?
I think this is not a good dael!!
is there any better ideal?  or jar the source to my lib by changing the package name?

**Comment by greenrobot-team** [comment]
Currently the greenDAO plugin can only access entity classes in the module it is applied to. So by default you can only have your entities inside of that module.

You should be able to provide an Android AAR library (`apply plugin: 'com.android.library'`) that contains your greenDAO entities and has the greenDAO plugin applied. So your developers would use the DAO classes of your library.
-ut

**Comment by BeautyKael** [comment]
@greenrobot-team  is that mean my developers who use my AAR library also need apply GreenDao?
ex. if Google Map SDK has used GreenDao, they support the SDK to me,my project should apply two SDKs(G.Map.SDK and GreenDao ),the middle SDK who use third SDK may not look like very well!

**Comment by greenrobot-team** [comment]
In that case no. The plugin should only have to be applied inside your library. I suggest you make a small example library and simply try it out. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
