### ISSUE TITLE
database upgrade from unencrypted version to encrypted one

### ISSUE THREAD

**Issue by maydayaaa** [greenrobot/greenDAO#735]
I have came up with a problem while upgrading database from unencrypted version to encrypted one using greendao3.0. Since in greendao's official website there is only a few infomation about how to encrypt the database.

DaoMaster.DevOpenHelper a = new DaoMaster.DevOpenHelper(this,"database_name",null); daoSession = new DaoMaster(a.getEncryptedWritableDb(MY_PWD)).newSession();

And When I tried to upgrade my database to encrypted version, I used the method getEncryptedWritableDB(password) directly to get the database then the app crashed since there's already a unenctypted version in local memory.

The error was showed below.

net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;

My database's name is "user-db" which does not end up with the suffix ".db",and as I have examined that there is no need to strickly follow that rule.It maked no difference.This error still exists.I wish anyone smart can help me solve this problem!!!Thanks a lot!!!

**Comment by greenrobot-team** [comment]
greenDAO can not automatically convert your non-encrypted to an encrypted database or vice versa. You will have to do this yourself. The [SQLcipher project has an example of how to encrypt a plain text database](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/ImportUnencryptedDatabaseTest.java). -ut

**Comment by iielse** [comment]
`https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/ImportUnencryptedDatabaseTest.java`

link 404

**Comment by greenrobot-team** [comment]
@iielse You can easily search a repository using the **Find file** button (to the top right).

In this case: go to https://github.com/sqlcipher/sqlcipher-android-tests, then click **Find file** (or press `t`), paste `ImportUnencryptedDatabaseTest`. Then you will find:

https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/ImportUnencryptedDatabaseTest.java

Happy coding!
-ut

**Comment by ULooper** [comment]
How to encrypt an existing sqlite database?  I should follow https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/ImportUnencryptedDatabaseTest.java this? I can't understand!!!
