### ISSUE TITLE
How to  encrypt an existing sqlite database?

### ISSUE THREAD

**Issue by q960757274** [greenrobot/greenDAO#736]
When I used fllowing API

DevOpenHelper helper = new DevOpenHelper(this, "notes-db-encrypted.db");
Database db = helper.getEncryptedWritableDb("<your-secret-password>");

throwing an Exception:

net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;

How to solve？？？

**Comment by greenrobot-team** [comment]
You have to decide when creating the database whether it will be encrypted or not. You can not change this after creating it.

As for the `file is encrypted or is not a database` error you should [look at the SQLcipher issues and ask there for help](https://github.com/sqlcipher/android-database-sqlcipher/issues?utf8=%E2%9C%93&q=is%3Aissue%20file%20is%20encrypted%20or%20is%20not%20a%20database).
-ut

**Comment by greenrobot-team** [comment]
To clarify: greenDAO can not automatically convert your non-encrypted to an encrypted database or vice versa. You will have to do this yourself. The [SQLcipher project has an example of how to encrypt a plain text database](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/ImportUnencryptedDatabaseTest.java). -ut

**Comment by q960757274** [comment]
thx
