### ISSUE TITLE
orderAsc() doesn't know about german Umlauts

### ISSUE THREAD

**Issue by szsoftware** [greenrobot/greenDAO#742]
`List<Product> productList = productDao.queryBuilder()
.where(ProductDao.Properties.CategoryId.eq(c.getId())).orderAsc(ProductDao.Properties.Name).build().list();`

Sorting of
["Pfirsiche","Äpfel","Bananen"]
results in 
["Bananen", "Pfirsiche","Äpfel"]
instead of
["Äpfel", "Bananen","Pfirsiche"]

Because "Ä" has the highest ASCII number of the three? How to solve?

**Comment by greenrobot-team** [comment]
If you are on Android and you are not using an encrypted database, you should be able to call `builder.preferLocalizedStringOrder()`. This uses Android's `COLLATE LOCALIZED` sort order. -ut

**Comment by szsoftware** [comment]
That quick support is just great!

**Comment by greenrobot-team** [comment]
Closing this then. -ut
