### ISSUE TITLE
How can i get weekly and monthly data

### ISSUE THREAD

**Issue by aabello7** [greenrobot/greenDAO#743]
I am new to greenDao. please i want to find out the query to use to filter the above subject

**Comment by greenrobot-team** [comment]
greenDAO has no specific support for this. It can just help you build standard SQL queries easier [with its Query API](http://greenrobot.org/greendao/documentation/queries/). You should probably[ read up on using SQL](https://www.w3schools.com/sql/default.asp) to query for data. -ut
