### ISSUE TITLE
what is session exactly?

### ISSUE THREAD

**Issue by BigGitWorld** [greenrobot/greenDAO#746]
what is session concept exactly and what do it for us?
In the past, I used sqlite directly in android and know CRUD operations very well. but I did not see session at all!
please notify me...

**Comment by greenrobot-team** [comment]
Have a look at [the Sessions documentation](http://greenrobot.org/greendao/documentation/sessions/). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
