### ISSUE TITLE
convertToEntityProperty not triggered

### ISSUE THREAD

**Issue by gcobc12677** [greenrobot/greenDAO#747]
I have an entity like this ( `Car` is my custom Object )

```
@Entity(nameInDb = "me")
public class Me {
    @Id
    @Property(nameInDb = "id")
    public long id = -1;

    @Property(nameInDb = "accessToken")
    public String accessToken = null;

    @Property(nameInDb = "email")
    public String email = null;

    @Property(nameInDb = "name")
    public String name = null;

    @Convert(converter = CarsConverter.class, columnType = String.class)
    @Property(nameInDb = "cars")
    public ArrayList<Car> cars = null;

    // ...

    public static class CarsConverter implements PropertyConverter<ArrayList<Car>, String> {
        @Override
        public ArrayList<Car> convertToEntityProperty(String databaseValue) {
            Log.d(getClass().getSimpleName(), "convertToEntityProperty");
            ArrayList<Car> cars = new ArrayList<>();

            return cars;
        }

        @Override
        public String convertToDatabaseValue(ArrayList<Car> entityProperty) {
            Log.d(getClass().getSimpleName(), "convertToDatabaseValue");
            return "[{ \"name\": \"test\" }]";
        }
    }
}
```

When I insert entity, `convertToDatabaseValue` is triggered and everything is okay.
Then I get entity by

```
daoSession.getMeDao().loadAll();
```

`convertToEntityProperty` is not triggered and I get `cars` that size is 0.
Is there something wrong?

**Comment by gcobc12677** [comment]
I found that if I did

```
daoSession = new DaoMaster(db).newSession();
```

before

```
daoSession.getMeDao().loadAll();
```

`convertToEntityProperty` is triggered and the result is like what I expect
but why should I need to get new session?

**Comment by greenrobot-team** [comment]
This is because greenDAO [uses caching](http://greenrobot.org/greendao/documentation/sessions/).

After you insert the entity it is cached. If you call `.loadAll()` the cached entity is immediately returned without querying the database.

To force greenDAO to query the database you can [clear the session cache](http://greenrobot.org/greendao/documentation/sessions/#Clear_the_identity_scope) before executing the query.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
