### ISSUE TITLE
ContentProviders and encrypted Database

### ISSUE THREAD

**Issue by naitbrahim** [greenrobot/greenDAO#749]
Hi everybody,
I have a problem with content providers generated with greendaogenerator when using encrypted database, have I missed something or may not configured greendao very well ?

the database used if encrypted version has not the methods insert,delete... so the contentprovider is show me errors.

How can I fix it please ? thanks in advance

**Comment by greenrobot-team** [comment]
Content provider generation is experimental. You are better off writing your own content provider.

Note: you can call `daoSession.getDatabase().getRawDatabase()` and cast the result to `net.sqlcipher.database.SQLiteDatabase`.
-ut

**Comment by naitbrahim** [comment]
Many thanks for your answer.
Keep up the good work.
