### ISSUE TITLE
Greendao multi-table associated data query why sometimes child objects have Sometimes no data

### ISSUE THREAD

**Issue by Johnjson** [greenrobot/greenDAO#751]
Greendao multi-table query associated child object is a data But the query Sometimes there are data Sometimes there are no data

**Comment by greenrobot-team** [comment]
I am not sure what the problem is exactly, but maybe this is due to to-many relations being resolved lazily. See the Relations documentation about [resolving and updating to-many relations](http://greenrobot.org/greendao/documentation/relations/#Resolving_and_Updating_To-Many_Relations). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
