### ISSUE TITLE
Failure when use allatori

### ISSUE THREAD

**Issue by beigirad** [greenrobot/greenDAO#753]
Hey guys.
I'm using [Allatory Java Obfuscator](http://www.allatori.com/)  in my project.
but when run helper.getWritableDb() in Application class , app crashes with this message 

`Could not init DAOConfig`

```
DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, ENCRYPTED Constant.DB_NAME_ENCRYPTED : Constant.DB_NAME);
Database db = ENCRYPTED ? helper.getEncryptedWritableDb("Farhad") : helper.getWritableDb();
daoSession = new DaoMaster(db).newSession();
```

must remember that proguard-rules are correct and app runs correctly when I disabled Allatori

**Comment by greenrobot-team** [comment]
So this is an Allatori issue then? Not sure I can help then. Check that it does not obfuscate anything that greenDAO might require, notably the `TABLENAME` constants in the generated DAO classes. -ut
