### ISSUE TITLE
@ToMany on List<Custom Object> drops data from GreenDAOv3 database when i restart the app

### ISSUE THREAD

**Issue by JBrannennMobileDev** [greenrobot/greenDAO#754]
Everything works fine until i close and reopen the app. Then all of the @tomany fields are dropped from the db. This is what my entity looks like. What am i doing wrong? is it because the the @Id of Lead is named lead_id and the reference parameter of the custom object also named lead_id?

```java
@entity
public class Lead implements Comparable{
@tomany(referencedJoinProperty = "lead_id") private List leadStages;
}
```

and

```java
@entity
public class LeadStage {
@NotNull private long lead_id;
@id private Long lead_stage_id;

@Generated(hash = 1589227946)
public LeadStage(long lead_id, Long lead_stage_id) {
    this.lead_id = lead_id;
    this.lead_stage_id = lead_stage_id;
}

@Generated(hash = 166566870)
public LeadStage() {
}
```

**Comment by greenrobot-team** [comment]
Is it possible that you did not insert the `LeadStage` objects before adding them to the `leadStages` list? Read [how to update to-many relations](http://greenrobot.org/greendao/documentation/relations/#Resolving_and_Updating_To-Many_Relations). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
