### ISSUE TITLE
Get Multiple table column Using Join

### ISSUE THREAD

**Issue by straltest15** [greenrobot/greenDAO#758]
Not able to get multiple entity detail in result list using join query as below
```java
@Entity
public class Person {
    @Id
    private Long id;
 
    private String firstName;
    private String lastName;
 
    @Property(nameInDb = "BIRTH_YEAR")
    @NotNull
    private int yearOfBirth;
    
    @Transient
    private Integer age;
 
    @ToMany(referencedJoinProperty = "contactId")
    private List<PhoneNumber> numbers;
}
```

```java
@Entity
public class PhoneNumber {
    @Id
    private Long id;
 
    @NotNull
    @Index(name = "NUMBER_IDX")
    private String number;
 
    @NotNull
    private Long contactId;
}
```

```java
 QueryBuilder<Person> queryBuilder = mDaoSession.getPersonDao().queryBuilder();
                    queryBuilder.join(PhoneNumber.class, PhoneNumberDao.Properties.ContactId);
                    List<Person> joined = queryBuilder.list();
```
               

In above example I do not able to get phone number of person. below link of represent same issue which I face.

https://stackoverflow.com/questions/38315642/how-to-use-join-query-for-displaying-data-from-multiple-tables-in-greendao

**Comment by greenrobot-team** [comment]
If you already added a relation, there is no need to do a join if you do not want to filter the related objects (in your case the phone numbers). Just query for the `Person` objects you want, then calling `getNumbers()` should query the related `PhoneNumber´ objects:

```java
List<Person> persons = mDaoSession.getPersonDao().queryBuilder().list();
List<PhoneNumber> numbers = persons.get(1).getNumbers();
```
 -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by himanshu1706** [comment]
@greenrobot-team Hello I am using the same code but result is not joined. I am using below code

`` public synchronized List<DevicesEntity> fetchGatewayDevices(){
        return NeroApp.getDaoSession()
                .getDevicesEntityDao().queryBuilder().list();
    }

I am creating relation like below:-

```
@Entity
public class DevicesEntity {

    @ToMany(referencedJoinProperty = "device_id")
    @SerializedName("entities")
    public List<Entities> entities;
}

@Entity
public class Entities{

    @SerializedName("device_id")
    public String device_id;
}
```
