### ISSUE TITLE
support only update specific column???

### ISSUE THREAD

**Issue by wybilold1999** [greenrobot/greenDAO#761]
support only update specific column???

**Comment by greenrobot-team** [comment]
As [greenDAO maps your database tables to objects](http://greenrobot.org/greendao/) you can only interact with the whole object. Typically this is fast enough for most use cases.

If you need to update single columns use raw SQL. You can get the underlying database using 
`(SQLiteDatabase) daoSession.getRawDatabase()`.
-ut
