### ISSUE TITLE
Upsert Using GreenDao

### ISSUE THREAD

**Issue by Xaus** [greenrobot/greenDAO#762]
Hi I Want to Upsert my table using greenDao
i know insertorreplace() function but i want to do something like this : 
```
INSERT OR REPLACE INTO Employee (id, name, role) 
  VALUES (  1, 
            'Susan Bar',
            COALESCE((SELECT role FROM Employee WHERE id = 1), 'Benchwarmer')
          );

```
for upserting my table with an entity  object

**Comment by greenrobot-team** [comment]
Nobody is stopping you from using plain SQL to interact with the underlying SQLite database. greenDAO by choice uses a simple object-based API to make common operations easier, at the price that some advanced SQL features are not possible.

As for `dao.insertOrReplace` you can see the exact statement used in the [TableStatements](https://github.com/greenrobot/greenDAO/blob/59c66587bbf996bc2baddd0e7dee4dee87931a84/DaoCore/src/main/java/org/greenrobot/greendao/internal/TableStatements.java#L67) class.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
