### ISSUE TITLE
How do I set the size limit for the cache 

### ISSUE THREAD

**Issue by vivekwolf123** [greenrobot/greenDAO#764]
Currently I am using this code to read from the db - 

public List<MyEntity> readMyDetails() {

        if (daoSession != null) {
            return daoSession.getMyEntityDao().queryBuilder().list();
        }
        return null;
    }

I want to implement a strategy where the size limit of list when it reaches 50 for example should have first in last out for the item in the list. How do I do this? 

Is there anything rotating policy or something which I can use.. Thanks in advance.

**Comment by greenrobot-team** [comment]
Not sure what exactly you are trying to do, but you may be successful [using limits and offsets](http://greenrobot.org/greendao/documentation/queries/#Limit_Offset_and_Pagination). -ut

**Comment by vivekwolf123** [comment]
I want to limit my database size to 50, I mean only 50 elements can be written to it. An attempt to write 51st element should follow FIFO (First In First Out) policy. How can I achieve this

**Comment by greenrobot-team** [comment]
greenDAO does not have this functionality, you will have to add your own code to handle this. -ut
