### ISSUE TITLE
getWritableDb returns null on some android devices

### ISSUE THREAD

**Issue by SICS-projects** [greenrobot/greenDAO#765]
DBHelper helper = new DBHelper(context, "dbfile.db");
db = helper.getWritableDb();

This lines return null on some Android 5, 6 and 7 Devics

I use Greendao 3.2.0

**Comment by greenrobot-team** [comment]
[This is Android API](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html), this is not a problem with greenDAO. I am not aware of any case where `getWritableDb()` returns null. However, [it may throw some exceptions](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html#getWritableDatabase()).
-ut
