### ISSUE TITLE
Log SQL queries in greenDao 3.x

### ISSUE THREAD

**Issue by KhalidElSayed** [greenrobot/greenDAO#768]
When I use greenDao 2.2 I can log the SQL queries using : `myDao.queryBuilder().LOG_SQL = true;`
for the new version (greenDao 3.2.2 specifically) it doesn't work.

BTW I also try using the `LOG_VALUES = true` it doesn't work either.

**Comment by greenrobot-team** [comment]
Works fine for me using the latest version. Try:
```java
QueryBuilder.LOG_SQL = true;
QueryBuilder.LOG_VALUES = true;
```
Then look for the log tag `greenDAO` in Logcat.
-ut

**Comment by KhalidElSayed** [comment]
I tried what you suggested so far and it still didn't work!
I put the log code after getting the session like this:

```
DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(App.getContext(), "book-db");
SQLiteDatabase db = helper.getWritableDatabase();
DaoMaster daoMaster = new DaoMaster(db);
DaoSession daoSession = daoMaster.newSession();

// enable debug for SQL Queries
QueryBuilder.LOG_SQL = true;
QueryBuilder.LOG_VALUES = true;
``` 

Is that correct?

**Comment by greenrobot-team** [comment]
It does not matter as these are static constants that are valid for the lifetime of your app. Note that this will only log queries you build using `QueryBuilder` and nothing else. How do you inspect Logcat output? Using Android Studio?
-ut

**Comment by KhalidElSayed** [comment]
Ok i got it, It will just work to log queries that built using `QueryBuilder` and their values. So what about logging other SQL statement like insert, insertOrReplace and save, How can I log them? Is there a way to achieve that? or Should I do it on my own?

**Comment by greenrobot-team** [comment]
greenDAO has no built-in logging for those, you will have to do this yourself. For example by writing your own SQLiteOpenHelper. -ut

**Comment by chnouman** [comment]
@greenrobot-team  it is only showing logs for SELECT query not for insertion and others.
