### ISSUE TITLE
unique() returning null while object exists in Database

### ISSUE THREAD

**Issue by trignodev-manish** [greenrobot/greenDAO#770]
Hi Greendao team, i have a case some times i get a strange behaviour when i query the table using querybuilder and pass the primary key of a row to fetch that row using unique() method and it returns me null however that key exists in table (i checked this by calling loadAll() in debugger of android studio).
I am not sure what is possible reason of it, can you please help.

**Comment by greenrobot-team** [comment]
This might be related to #702. Though in your case both `.unique()` and `.loadAll()` should use the session cache. Try to [clear the session cache](http://greenrobot.org/greendao/documentation/sessions/#Clear_the_identity_scope) before fetching the entity.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
