### ISSUE TITLE
greendao used in Library module and project problem

### ISSUE THREAD

**Issue by maozonghong** [greenrobot/greenDAO#772]
in my library module I need to use greenDao ，it  generate DaoMaster,DaoSession,DownloadInfoDao,
see the below picture:
![ry t1v i xhyk alae](https://user-images.githubusercontent.com/27840912/31482264-33b99832-af5a-11e7-8eef-d99f05411851.png)
here is my build.gradle(my library)

```
apply plugin: 'com.android.library'
apply plugin: 'org.greenrobot.greendao' // apply plugin

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2' // add plugin
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

android {

    compileSdkVersion 25
    buildToolsVersion "25.0.1"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            java.srcDirs = ['src/main/java', 'src/main/java-gen']
        }
    }

    greendao{
        schemaVersion 2
        targetGenDir 'src/main/java-gen'
        daoPackage 'com.mao.greendao.gen'
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/ASL2.0'
    }

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    ........

    compile 'org.greenrobot:greendao:3.2.2' // add library
..................

}
```

in my app project refered on my library module. it hava a DownloadInfo2 Entity class  add annotation as @Entity, when i build the project it  also generate DaoMaster,DaoSession,it confused me,did it not generate in the same folder?   how do i solve the problem ? i only want it to generate one DaoMaster,DaoSession.
![h9uwj75sxx hvud 8 90](https://user-images.githubusercontent.com/27840912/31482610-8c20907e-af5b-11e7-889a-125ea0114bb3.png)

**Comment by greenrobot-team** [comment]
The greenDAO plugin generates DAO classes for each module separately. The plugin does not pick up entities from other modules.

Two options:
- Keep as is, use the separate DAO classes and treat them as two separate databases. Like [the example here](https://github.com/greenrobot-team/greenrobot-examples/tree/master/greendao-library).
- Move all your entities to the same module (app or library).
-ut

**Comment by maozonghong** [comment]
when i init the DaoSession in separate did i can use the same database name?
like below:
 MySQLiteOpenHelper helper = new MySQLiteOpenHelper(this, getDB_NAME(), null);
        DaoMaster daoMaster = new DaoMaster(helper.getWritableDatabase());
        daoSession = daoMaster.newSession();

**Comment by greenrobot-team** [comment]
Technically there should not be a reason why not. You just have to be careful that you create all required tables in your `MySQLiteOpenHelper`. -ut
