### ISSUE TITLE
ToOne,ToMany

### ISSUE THREAD

**Issue by Reginer** [greenrobot/greenDAO#773]
![主表](https://user-images.githubusercontent.com/12568257/31931984-8e604ec6-b8d7-11e7-8c2c-2205b445d7ad.png)

The main table is SearchEntity，PageInfoEntity、StateEntity、DataEntity is child table .
How do I use SearchEntityDao to save all of the data ?

[Sample is here](https://github.com/Reginer/Dao/blob/master/app/src/main/java/win/reginer/dao/MainActivity.java)

**Comment by greenrobot-team** [comment]
Basically this works like plain SQL. You will have to insert each object (if it is not inserted already). Make sure that the foreign key/join property of each related entity is set to the ID of your `SearchEntity` before. (If you do not know the ID, you will have to insert your `SearchEntity` first.).

Also see [Resolving and Updating To-Many Relations](http://greenrobot.org/greendao/documentation/relations/#Resolving_and_Updating_To-Many_Relations).
-ut

**Comment by Reginer** [comment]
For example   ?

```    SearchEntity searchEntity = new Gson().fromJson(Content.DATA, SearchEntity.class);
        SearchEntityDao mSearchEntityDao = DatabaseManager.getInstance().getDao().getSearchEntityDao();
        searchEntity.setPageId((long) 1);
        searchEntity.setStateId((long) 1);
        mSearchEntityDao.insertOrReplaceInTx(searchEntity);
        PageInfoEntity  pageInfoEntity = searchEntity.getPageInfo();
        DatabaseManager.getInstance().getDao().getPageInfoEntityDao().insertInTx(pageInfoEntity);
        List<DataEntity> dataEntityList = searchEntity.getData();
        for (int i = 0; i <dataEntityList.size() ; i++) {
            dataEntityList.get(i).setDateId((long)i);
        }
        DatabaseManager.getInstance().getDao().getDataEntityDao().insertInTx(dataEntityList);
```

**Comment by greenrobot-team** [comment]
Looks reasonable. If in doubt you should get a better understanding how relations work in SQL/SQLite. -ut

**Comment by Reginer** [comment]
o

**Comment by softboy99** [comment]
So, It means, greendao cannot help insert child entity to database automatically even we have designed the relations in the parent entity. But your generator generated code for the child entity like searchEntity.getPageInfo() will throw exception before we can insert it manually.
