### ISSUE TITLE
Why is my data updated automatically without calling the update function?

### ISSUE THREAD

**Issue by alberthugo** [greenrobot/greenDAO#776]
Version 3.2.2

Example:

 Quotation quotation = data.getQuotation();
 quotation.setId(null);  //updated automatically
 quotation.setNewClient(true);  //updated automatically

How did you disable it?

Thank you

**Comment by greenrobot-team** [comment]
greenDAO cashes your objects to avoid fetching them from the database. This way it might appear that the database was updated, where it actually is not. You can verify this by [clearing the cache using `daoSession.clear()`](http://greenrobot.org/greendao/documentation/sessions/#Clear_the_identity_scope) before executing your query.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
