### ISSUE TITLE
DevOpenHelper returns null in greendao

### ISSUE THREAD

**Issue by vinodkumarnalla** [greenrobot/greenDAO#781]
```
if (sDevOpenHelper == null) {
sDevOpenHelper = new DaoMaster.DevOpenHelper(ctx, database_name, null);
}
```

I am using this code to get the DaoMaster instance but some times its returns null

**Comment by greenrobot-team** [comment]
`new DaoMaster.DevOpenHelper()` can never return null. Do you mean `sDevOpenHelper` is sometimes `null`? If yes, this is an issue with your code and has nothing to do with greenDAO. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
