### ISSUE TITLE
Pb(572) List is a raw type.

### ISSUE THREAD

**Issue by nordanfors** [greenrobot/greenDAO#782]
I am using Flexible Adapter(https://github.com/davideas/FlexibleAdapter) in my project to simplify development. However I have come across a problem with one of its methods that causes greendao fail at build.

Here is the error message:
Error:Execution failed for task ':app:greendao'.
> Found 1 problem(s) parsing 
  Pb(572) List is a raw type. References to generic type List<E> should be parameterized (16777788 at line 250).

Line 250 in my class is this method which is part of the FA library:
public void bindViewHolder(FlexibleAdapter adapter, MyViewHolder holder, int position,
                               List payloads) {...}

It seems Greendao is no accepting the List item to be typeless. I have not been able to find a solution or workaround so any help I can get is much appreciated.

**Comment by greenrobot-team** [comment]
Not sure I understand this correctly, but why don't you move your entity class out of the list adapter class? -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
