### ISSUE TITLE
please publish the list of available dependencies for build.gradle files.

### ISSUE THREAD

**Issue by rschilling** [greenrobot/greenDAO#785]
I'm trying to decide if I can update my gradle project to use the latest version of the dependencies for greendao-generator. But I can find nothing that lets me know what versions are available.

Can you please publish a list of values that can be used in the 'compile' command of the dependencies block? Thanks.

Here is what I have in my project right now:

dependencies {
    compile 'de.greenrobot:greendao-generator:2.0.0'
}

**Comment by greenrobot-team** [comment]
If you can, you should [upgrade to greenDAO 3](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/) and no longer use the generator.

Anyhow, the last version of greenDAO 2 was `2.2.1`. You can browse this repositories tags to [look at the README at that time](https://github.com/greenrobot/greenDAO/tree/V2.2.1).
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
