### ISSUE TITLE
Migration bug v2 => v3: initial values of custom fields get lost

### ISSUE THREAD

**Issue by MFlisar** [greenrobot/greenDAO#786]
If I migrate a project from v2 to v3, all custom fields lose their initial values.

For example this

    // KEEP FIELDS - put your custom fields here
    private List<WLap> pRemovedLaps = new ArrayList<WLap>();
    private List<WTargetLap> pRemovedTargetLaps = new ArrayList<WTargetLap>();
    // KEEP FIELDS END

Is converted to this:

     @Transient
    private List pRemovedLaps;
    @Transient
    private List pRemovedTargetLaps;

Not a big issue, but this should be documented at least

**Comment by greenrobot-team** [comment]
Thanks for reporting. I added an additional [note about this conversion to the Migration documentation](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#Step_2_Use_entity_annotations). -ut
