### ISSUE TITLE
one-to-many over a table

### ISSUE THREAD

**Issue by BigGitWorld** [greenrobot/greenDAO#787]
Hi
I have a class like as below:
```java
public class Human{
    private Long id;
    ...
   private List<Human> children;
}
```

How can I implement one-to-many relation over itself by greendao?

**Comment by greenrobot-team** [comment]
There is a similar [example using a tree](http://greenrobot.org/greendao/documentation/relations/#Example_Modelling_Tree_Relations) at the bottom of the Relations documentation. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
