### ISSUE TITLE
Allow to use same names for database query generation.

### ISSUE THREAD

**Issue by hurelhuyag** [greenrobot/greenDAO#793]
Maybe some case upper case is useful. But in my case property name same named in database is required because of simplicity. as well as table name same as entity class name.

**Comment by greenrobot-team** [comment]
I am not sure what you need, can you give an example?

The following should work fine, even if I do not recommend it:
```java
@Entity
public class Note {
    ...
    private Date DATE;
    ...
}
```
-ut

**Comment by hurelhuyag** [comment]
GreenDao generating create sql with UPPERCASED_NAMES. I don't know what is advantage of uppercased names. 

I need this create query.
```
@Entity
public class Note {
    ...
    @Id
    private Long id;
    private String name;
    ...
}
```

```
create table Note (
    _id INTEGER,
    name TEXT,
)
```

**Comment by hurelhuyag** [comment]
`DaoUtil.dbName` naming conversion valueless. I need this simple dbName method.

    ```
    public static String dbName(String javaName) {
        return javaName;
    }
```

**Comment by greenrobot-team** [comment]
You can use `@Entity(nameInDb = "note")` and `@Property(nameInDb = "name")`. -ut
