### ISSUE TITLE
Load entities in depth for multiple one-to-many relationships

### ISSUE THREAD

**Issue by FelipeBerrios** [greenrobot/greenDAO#794]
I have a main entity that has multiple one-to-many relationships, then these entities also have one-to-many relationships. My question is, what is the best way to load all the relationships in depth?
I also need to load the relationships one by one, that is, all the entities must be left with their one-to-one and one-to-many relationships loaded into memory.

Thank you

**Comment by greenrobot-team** [comment]
Please read the [Relations documentation](http://greenrobot.org/greendao/documentation/relations/) about what is possible. Especially the note about how to eagerly load to-one relations. -ut
