### ISSUE TITLE
Many-to-many relations with JoinEntity using field another than id

### ISSUE THREAD

**Issue by Bringoff** [greenrobot/greenDAO#796]
Asked on SO as well https://stackoverflow.com/questions/47569609/how-to-make-many-to-many-relation-query-in-greendao-with-source-property-other-t
I have following entities:
Item:
```
class Item {
...
    @Index(unique=true)
    private String guid;
...
    @ToMany
    @JoinEntity(entity = JoinItemsWithTags.class, sourceProperty = "itemGuid", targetProperty = "tagName")
    private List<Tag> tagsWithThisItem;
    ...
}
```

Tag:
```
class Tag {
    @Id
    private Long localId;
    @Index(unique = true)
    private String name;
    ...
}
```

and I need to join them. Here is my join entity class:
```
@Entity(nameInDb = "item_tag_relations")
class JoinItemsWithTags {
    @Id
    private Long id;
    private String itemGuid;
    private String tagName;
    ...
}
```
Tag name is unique, and app should work offline so I want to use tag name as a join property instead of Long id, because it's easier to support consistency when syncing with server.
But generated `List<Tag> _queryItem_TagsWithThisItem(String itemGuid)` method implicitly uses tag id to make a join:
```
// primary key is passed as source property inside this join method
queryBuilder.join(JoinItemsWithTags.class, JoinItemsWithTagsDao.Properties.TagName)
                    .where(JoinItemsWithTagsDao.Properties.ItemGuid.eq(itemGuid));
```
Correct approach is this case should be following, I suppose:
```
// source property is passed explicitly
queryBuilder.join(TagDao.Properties.Name, JoinItemsWithTags.class, JoinItemsWithTagsDao.Properties.TagName)
                    .where(JoinItemsWithTagsDao.Properties.ItemGuid.eq(itemGuid));
```
But this code is in generated dao, and I don't know how to do anything with it. Is there any way to workaround this?

**Comment by greenrobot-team** [comment]
Please read the docs about [Joins](http://greenrobot.org/greendao/documentation/joins/). If this is then still an issue feel free to re-open. -ut
