### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by imzhq** [greenrobot/greenDAO#797]
i want to implements the sql blow with greendao,but i dont konw how
        sql += " SELECT";
        sql += "    b. *";
        sql += " FROM";
        sql += "    food_item a";
        sql += " INNER JOIN item_info b ON a.shop_id = b.shop_id";
        sql += " AND a.branch_id = b.branch_id";
        sql += " AND a.pos_no = b.pos_no";
        sql += " AND a.item_id = b.item_id";
        sql += " WHERE";
        sql += "    a.shop_id = ";
        sql += " ? ";
        sql += " AND a.branch_id = ";
        sql += " ? ";
        sql += " AND a.pos_no = ";
        sql += " ? ";
        sql += " AND food_category_id IN(";
        sql += " ? ";

**Comment by umair-tp** [comment]
You can do something like this and write your raw SQL query in String.

List<Item> Items = itemDao.queryBuilder().where(
        new WhereCondition.StringCondition("" +
        " T.QUESTION_ID IN (SELECT QUESTION_ID FROM ANSWER A" +
                                " INNER JOIN SELECTED_ANSWER S ON T.ID = S.ITEM_ID" +
                                " WHERE A.IS_CORRECT = 0" +
                                "   AND S.ANSWER_ID = A.ID)")).list();

**Comment by imzhq** [comment]
thank you your answer very helpfull to me , i already try ,thank you again
