### ISSUE TITLE
couldn't generate XyzDao when set XyzEntity "generateGettersSetters" to false

### ISSUE THREAD

**Issue by xiaoc024** [greenrobot/greenDAO#798]
After I set XyzEntitiy generateGettersSetters to false,and rebuild my project, GreedDao couldn't generate XyzDao class because of there are not the methods such as entity.getId();entity.getX(); So how does the "generateGettersSetters" work rightly?

**Comment by greenrobot-team** [comment]
You always need getters for your entity properties. Settings `generateGettersSetters` to false only prevents greenDAO from overwriting any custom getters you might have written. -ut
