### ISSUE TITLE
how to insert a custom class collection

### ISSUE THREAD

**Issue by DCZLQR** [greenrobot/greenDAO#799]
![c943b31e8b8ba6a3c1529919a8204f70](https://user-images.githubusercontent.com/32856687/33746490-9feac75e-dbf8-11e7-934a-8e71436f37dc.png)I try insert List《Bluetooth》 like List《String》,but List《Bluetooth》 has to custom static,greenDAO support insert custom class?Thanks

**Comment by greenrobot-team** [comment]
You can use [relations](http://greenrobot.org/greendao/documentation/relations/) or a [custom type](http://greenrobot.org/greendao/documentation/custom-types/). -ut
