### ISSUE TITLE
on Bitrise - Build failed with an exception 

### ISSUE THREAD

**Issue by ChristopheWeMa** [greenrobot/greenDAO#804]
the project can build locally  but fail on https://www.bitrise.io/

I get this message from bitrise
----------------------------------
:app:compileEpStagingS3StagingDebugJavaWithJavac/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:98: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        auditReportDao = new AuditReportDao(auditReportDaoConfig, this);
                                                                  ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:99: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        contractTermsDao = new ContractTermsDao(contractTermsDaoConfig, this);
                                                                        ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:100: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        documentAttachmentDao = new DocumentAttachmentDao(documentAttachmentDaoConfig, this);
                                                                                       ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:101: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        elevatorBrandDao = new ElevatorBrandDao(elevatorBrandDaoConfig, this);
                                                                        ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:102: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);
                                                         ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:103: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        scheduleActivityReportDao = new ScheduleActivityReportDao(scheduleActivityReportDaoConfig, this);
                                                                                                   ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:104: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        scheduleElevatorDao = new ScheduleElevatorDao(scheduleElevatorDaoConfig, this);
                                                                                 ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:105: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        taskDao = new TaskDao(taskDaoConfig, this);
                                             ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:106: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        sosAnalyticsDao = new SosAnalyticsDao(sosAnalyticsDaoConfig, this);
                                                                     ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/database/DaoSession.java:107: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
        sosContactsDao = new SosContactsDao(sosContactsDaoConfig, this);
                                                                  ^
/bitrise/src/WeMaintain/app/src/main/java/com/mechanic/wemaintain/task/TaskDataSyncService.java:200: error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession
                                Schedule.clearLocalData(daoSession, scheduleId);
                                                        ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
11 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileEpStagingS3StagingDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

----------------------------------

here my gradle file
apply plugin: 'org.greenrobot.greendao' is before apply plugin: 'com.android.application'
and targetGenDir 'src/main/java' solved the issue cannot find symbol DaoSession, but now i have 
"cannot be converted to" in the generated class ; this message pop only when i try to build on bitrise, when i build on my PC it works.

------------------------------------

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
        classpath 'com.google.gms:google-services:3.1.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}
ext {
    supportLibrary = "25.3.1"
    firebase="11.4.2"
}
task clean(type: Delete) {
    delete rootProject.buildDir
}

apply plugin: 'org.greenrobot.greendao'
apply plugin: 'com.android.application'

repositories {
    mavenCentral()
    google()
}
android {
    compileSdkVersion 25
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "com.mechanic.wemaintain"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 76
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        manifestPlaceholders = [HOCKEYAPP_APP_ID: "d195c3b895714f478f64f6180fb21b4c"]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    //flavors based on both endpoint and s3 buckets
    flavorDimensions "endpoint", "awsconfig"
    productFlavors {
        epFiftyeight {
            dimension "endpoint"
            buildConfigField "String", "BASE_URL", '"http://172.52.110.21:8080/wemaintain-web/"'
            // swati http://172.52.110.21:8080/wemaintain-web/rest/
            // manasi http://172.52.100.25:8080/wemaintain-web/
        }
        epStaging {
            dimension "endpoint"
            buildConfigField "String", "BASE_URL", '"https://api.staging.wemaintain.io/wemaintain-web/"'
        }
        epProd {
            dimension "endpoint"
            buildConfigField "String", "BASE_URL", '"https://api.wemaintain.io/wemaintain-web/"'
        }
        epUat {
            dimension "endpoint"
            buildConfigField "String", "BASE_URL", '"http://52.209.184.4:8080/wemaintain-web/"'
        }
        s3Prod {
            dimension "awsconfig"
            buildConfigField "String", "S3_BUCKET_NAME", '"wemaintain-data-prod"'
            buildConfigField "String", "S3_IDENTITY_POOL_ID", '"eu-west-1:47d2cf4f-3bf4-4bb3-a895-c5d3817204cf"'
        }
        s3Staging {
            dimension "awsconfig"
            buildConfigField "String", "S3_BUCKET_NAME", '"wemaintain-data-staging"'
            buildConfigField "String", "S3_IDENTITY_POOL_ID", '"eu-west-1:e6e66c61-1ab0-431c-9098-eadddbca8832 "'
        }
        s3Uat {
            dimension "awsconfig"
            buildConfigField "String", "S3_BUCKET_NAME", '"uatwemaintaindata"'
            buildConfigField "String", "S3_IDENTITY_POOL_ID", '"eu-west-1:e8005c91-6ba6-4fb6-846f-93ee7eed085e"'
        }
    }
}

greendao {
    schemaVersion 1012
    targetGenDir 'src/main/java'
}

dependencies {
    compile fileTree(include: ["*.jar"], dir: "libs")
    androidTestCompile("com.android.support.test.espresso:espresso-core:2.2.2", {
        exclude group: "com.android.support", module: "support-annotations"
    })
    compile("com.pnikosis:materialish-progress:1.5") { transitive = false }
    compile project(":bottomnavigation")
    compile 'net.hockeyapp.android:HockeySDK:5.0.3'

    implementation "de.hdodenhof:circleimageview:2.1.0"
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibrary}"
    implementation "com.android.support:mediarouter-v7:${rootProject.ext.supportLibrary}"
    implementation "com.jakewharton:butterknife:8.6.0"
    implementation "com.android.support:recyclerview-v7:${rootProject.ext.supportLibrary}"
    implementation "com.squareup.retrofit2:retrofit:2.3.0"
    implementation "com.squareup.retrofit2:converter-gson:2.3.0"
    implementation "com.squareup.okhttp3:logging-interceptor:3.9.0"
    implementation "com.squareup.okhttp3:okhttp:3.9.0"
    implementation "com.github.bumptech.glide:glide:3.8.0"
    implementation "joda-time:joda-time:2.9.9"
    implementation "com.android.support:cardview-v7:${rootProject.ext.supportLibrary}"
    implementation "com.android.support:design:${rootProject.ext.supportLibrary}"
    implementation "com.android.support:support-v4:${rootProject.ext.supportLibrary}"
    implementation "com.amazonaws:aws-android-sdk-s3:2.6.2"
    implementation "com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.6.2"
    implementation "com.google.firebase:firebase-core:${rootProject.ext.firebase}"
    implementation "com.google.firebase:firebase-messaging:${rootProject.ext.firebase}"
    compile "org.parceler:parceler-api:1.1.6"
    implementation "com.android.support.constraint:constraint-layout:1.0.2"
    compile "org.greenrobot:greendao:3.2.2"
    implementation "com.google.android.gms:play-services-location:${rootProject.ext.firebase}"
    testCompile "junit:junit:4.12"
    annotationProcessor "org.parceler:parceler:1.1.6"
    annotationProcessor "com.jakewharton:butterknife-compiler:8.6.0"
    compile 'com.prolificinteractive:material-calendarview:1.4.3'
}

apply plugin: "com.google.gms.google-services"

**Comment by greenrobot-team** [comment]
I can't give support on your build setup. But I suggest looking at the error message:
`error: incompatible types: com.mechanic.wemaintain.database.DaoSession cannot be converted to com.mechanic.wemaintain.sos.model.DaoSession`

Looks like there is a type conflict.
-ut
