### ISSUE TITLE
在for循环里执行查询语句报错？

### ISSUE THREAD

**Issue by cdcdec** [greenrobot/greenDAO#807]
1.在for循环里面执行语句： QueryBuilder<T> where(WhereCondition cond, WhereCondition... condMore) {
        whereCollector.add(cond, condMore);报错？2.如何打印sql语句

**Comment by greenrobot-team** [comment]
If I understand correctly, you can enable [query debug logging](http://greenrobot.org/greendao/documentation/queries/#Troubleshooting_queries):
```
QueryBuilder.LOG_SQL = true;
QueryBuilder.LOG_VALUES = true;
```

Otherwise, please post an English question.
-ut

**Comment by greenrobot-team** [comment]
No response, closing. Please re-open with more details or submit a new issue. -ut
