### ISSUE TITLE
master，dao等自动代码已经生成，需要去除generator？里面有freemarker还有其他等占体积的包

### ISSUE THREAD

**Issue by wangyuan0217** [greenrobot/greenDAO#811]

**Comment by greenrobot-team** [comment]
I'm not sure what you mean. Please post your question in English.

If you are talking about migrating to greenDAO v3, please have a look at http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations
-ut

**Comment by wangyuan0217** [comment]
I’ not that mean.I'm not sure if I can remove the generator after used,because it contains unused soursea and that will increase the size of my apk.

**Comment by greenrobot-team** [comment]
Once code is generated you can remove the generator. But a better solution is to use ProGuard. See details on how to [Shrink Your Code and Resources](https://developer.android.com/studio/build/shrink-code.html). -ut
