### ISSUE TITLE
A exception:no such table

### ISSUE THREAD

**Issue by pphdsny** [greenrobot/greenDAO#813]
Exception:
android.database.sqlite.SQLiteException: no such table: EVENT_ID_NAME_MAP (code 1): , while compiling: SELECT T."ID",T."NAME" FROM "EVENT_ID_NAME_MAP" T WHERE T."ID"=? LIMIT ?

I use greenDAO in an Application and the Library.The Library is referenced by maven to compile.After I upgraded from the old version happen this problem.

EVENT_ID_NAME_MAP is in application.

use in Application:
```
//db version:1
        DaoMaster.DevOpenHelper openHelper = new DaoMaster.DevOpenHelper(DocRabApp.getInstance(), "app_db");
        SQLiteDatabase db = openHelper.getWritableDatabase();
        DaoMaster daoMaster = new DaoMaster(db);
        DaoSession daoSession = daoMaster.newSession();
```

use inLibrary:
```
//db version:1
        DaoMaster.DevOpenHelper openHelper = new DaoMaster.DevOpenHelper(DocRabApp.getInstance(), "ubt_db");
        SQLiteDatabase db = openHelper.getWritableDatabase();
        DaoMaster daoMaster = new DaoMaster(db);
        DaoSession daoSession = daoMaster.newSession();
```

**Comment by greenrobot-team** [comment]
So where does this exception occur? If `EVENT_ID_NAME_MAP` does not exist in the library it makes sense that it will break when trying to query using the application DAO session. Make sure to use the correct DAO session. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
