### ISSUE TITLE
Do I need to remove 'greendao-2.1.0.jar' in order to update to 3.2.2?

### ISSUE THREAD

**Issue by daybson** [greenrobot/greenDAO#815]
And is still necessary to keep another module to SchemaGenerator or can I drop it out?

**Comment by greenrobot-team** [comment]
As per the instructions on [Updating to greenDAO 3](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/): yes, you should remove the dependency on the old version of the greendao library.

And if you have switched to the Gradle plugin (you are using `apply plugin: 'org.greenrobot.greendao'`) then yes, you can remove your generator.

Again, for further details please read [Updating to greenDAO 3](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/).
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
