### ISSUE TITLE
Are insertions thread safe? In UI thread? In AsyncTaskLoader thread?

### ISSUE THREAD

**Issue by AlanCPSC** [greenrobot/greenDAO#816]
## Question

Hello, thanks for the great library.

I have a question. I know that `Query<T>` is not thread safe in greenDao ([https://github.com/greenrobot/greenDAO/issues/131](url)) - and thus requires some extra work to get the mechanism right. But what about plain insertions?

## Details

Consider the following code.

```
// performing database init
greenDaoHelper      = new DaoMaster.DevOpenHelper(context, localDatabase);
greenDaoDatabase    = greenDaoHelper.getWritableDb();
greenDaoSession     = new DaoMaster(greenDaoDatabase).newSession();

userProfileModelDao = greenDaoSession.getUserProfileModelDao();
```

I then use the resulting `userProfileModelDao` to save either 1 or many objects into the database in either the UI Thread or some AsyncTaskLoader Thread.

```
public void saveUserProfileModel(UserProfileModel userProfileModel)
{
    userProfileModelDao.insertOrReplaceInTx(userProfileModel);
}
```

But due to the Android lifecycle - it is possible that multiple AsyncTaskLoaders will make the call to `userProfileModelDao.insertOrReplaceInTx(userProfileModel);` at the same time - with different data.

## Summary

Is the operation thread safe? In other words can I assume

* no matter how many simultaneous calls to `insert` only **the last** 1 will persist and there is no risk of data corruption.

e.x. while `Thread 1` is already in the process of inserting a large number of items `{x1,x2,x3,...}`, I make another call in `Thread 2` to insert items `{y1,y2,y3,...}`. Once both threads are done, am I guaranteed the database contains **the last call** `{y1,y2,y3,...}` and not corrupted `{x1,y2,x3,...}`?

Or failing that, can I at least assume that

* no matter how many simultaneous calls to `insert` only 1 will persist and there is no risk of data corruption.

e.x. while `Thread 1` is already in the process of inserting a large number of items `{x1,x2,x3,...}`, I make another call in `Thread 2` to insert items `{y1,y2,y3,...}`. Once both threads are done, am I guaranteed the database contains `{x1,x2,x3,...}` or `{y1,y2,y3,...}` and not corrupted `{x1,y2,x3,...}`?

Thank you for any help.

**Comment by greenrobot-team** [comment]
You can see the [`AbstractDao`](https://github.com/greenrobot/greenDAO/blob/master/DaoCore/src/main/java/org/greenrobot/greendao/AbstractDao.java#L271-L311) code yourself. Each insert is done using its own database transaction, so inserts can be considered thread-safe. -ut
