### ISSUE TITLE
MultiDexApplication ,do not generate greendao 

### ISSUE THREAD

**Issue by SageLu** [greenrobot/greenDAO#818]
compile 'org.greenrobot:greendao:3.2.2' // add library
![default](https://user-images.githubusercontent.com/17927694/35379286-9593d82c-01f0-11e8-81f9-3ae59535ba3f.png)
![default](https://user-images.githubusercontent.com/17927694/35379316-a3391730-01f0-11e8-89f6-f654c9ee9830.png)

what  should  I  can  do?

**Comment by greenrobot-team** [comment]
Are you sure there is a field named `daoSession` inside of your `App` class?

Check out [an example](https://github.com/greenrobot-team/greenrobot-examples/blob/master/greendao/app/src/main/java/com/example/greendao/ExampleApp.java).
-ut

**Comment by SageLu** [comment]
Then I recompiled the project .  It's working.   But I met a problem that  GreenDAO dont support  rxjava2 ,
what I  should do ?  how do it? thanks.

**Comment by greenrobot-team** [comment]
You can currently not use greenDAO with RxJava 2, see #520.

I suggest you take a look at https://github.com/objectbox/objectbox-java or another solution if it is a requirement. -ut
