### ISSUE TITLE
Occurs when data is inserted cyclically

### ISSUE THREAD

**Issue by 15629061018** [greenrobot/greenDAO#819]
This is what causes?
E/SQLiteLog: (13) statement aborts at 19: [INSERT OR REPLACE INTO "LIST_BEAN" ("PUBLISH_TIME","NEWS_ID","VISIT_COUNT","PUBLISH_USER","TITLE","INFOSOURCE","TYPE") VALUES (?,?,?,?,?,?,?)] 
 E/SQLiteLog: (1) statement aborts at 2: [ROLLBACK;] cannot rollback - no transaction is active

**Comment by greenrobot-team** [comment]
Sorry, I can't help you without an example of what you are trying to do. -ut
