### ISSUE TITLE
convert error

### ISSUE THREAD

**Issue by zuiaikulapika** [greenrobot/greenDAO#821]
@Convert(converter = DataConvert.class,columnType = Date.class)
    private Date  publishDate;

    public static class  DataConvert implements PropertyConverter<Date,String>{
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        @Override
        public Date convertToEntityProperty(String databaseValue) {
            try {
                return  formatter.parse(databaseValue);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            return new Date(0);
        }
        @Override
        public String convertToDatabaseValue(Date entityProperty) {

            return formatter.format(entityProperty);
        }
    }

Error:(91, 86) 错误: 找不到符号
符号:   方法 getTime()
位置: 类 String
Error:(118, 86) 错误: 找不到符号
符号:   方法 getTime()
位置: 类 String
 Date无法转换为String
Error:(157, 111) 错误: 不兼容的类型: Date无法转换为String

**Comment by greenrobot-team** [comment]
Change
```java
@Convert(converter = DataConvert.class,columnType = Date.class)
private Date  publishDate;
```

to
```java
@Convert(converter = DataConvert.class, columnType = String.class)
private Date  publishDate;
```

Also read the [Custom Types documentation](http://greenrobot.org/greendao/documentation/custom-types/). -ut
