### ISSUE TITLE
Can an entity class have a parent class？

### ISSUE THREAD

**Issue by jingzhanwu** [greenrobot/greenDAO#824]
1. Can the entity class of the database table be able to extends another class?
2. Can no Long type Id be specified in the entity class?

**Comment by IncredibleKenny** [comment]
why not have a try?

**Comment by greenrobot-team** [comment]
greenDAO does not support inheritance.

[Regarding primary keys (IDs), see the documentation.](http://greenrobot.org/greendao/documentation/modelling-entities/#Primary_key_restrictions)
-ut
