### ISSUE TITLE
How to compare Dates in greenDAO ?

### ISSUE THREAD

**Issue by behiunforgiven** [greenrobot/greenDAO#825]
I have a class named Attendants with these properties: 

```java
public Date EntranceDate;
public Date ExitDate;
```

I want to get today attendant by this code:

```java
QueryBuilder<Attendants> queryBuilder = attendantsDao.queryBuilder();
queryBuilder.or(AttendantsDao.Properties.EntranceDate.between(startDate,endDate),
AttendantsDao.Properties.ExitDate.between(startDate,endDate));
Attendants attendant = queryBuilder.unique();
```

that startDate and endDate are variables of `Date` type.

but this code does not works.

How can I work with Dates and compare them in greenDAO?

**Comment by greenrobot-team** [comment]
The `between()` API should recognize `Date`. Your SQL query seems wrong, it has no where statement. Wrap your OR condition inside a WHERE clause: `where(or(condA, condB))`.

Check the [Javadocs for tips about using the query API](http://greenrobot.org/files/greendao/javadoc/current/org/greenrobot/greendao/query/QueryBuilder.html#or-org.greenrobot.greendao.query.WhereCondition-org.greenrobot.greendao.query.WhereCondition-org.greenrobot.greendao.query.WhereCondition...-). -ut

**Comment by longtaoge** [comment]
That 's OK

**Comment by greenrobot-team** [comment]
Alright, closing then. -ut
