### ISSUE TITLE
android.database.sqlite.SQLiteException:Failed to change locale for db

### ISSUE THREAD

**Issue by darrenyu** [greenrobot/greenDAO#826]
1 android.database.sqlite.SQLiteException:Failed to change locale for db '/data/user/0/com.xingin.xhs/databases/capa.db' to 'zh_CN'.
--
2 android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:391)
3 ......
4 Caused by:
5 android.database.sqlite.SQLiteFullException:database or disk is full (code 13)
6 android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
7 android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:553)
8 android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:369)
9 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:216)
10 android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
11 android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
12 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
13 android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
14 android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
15 android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
16 android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
17 android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:594)
18 android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:280)
19 android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
20 android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
21 org.greenrobot.greendao.a.b.a(SourceFile:59)
22 com.xingin.capa.lib.manager.DBManager$Companion$init$1.a(SourceFile:20)

**Two Solution:** 
1. SQLiteOpenHelper.getDatabaseLocked(): 

db = SQLiteDatabase.openDatabase(path, mFactory,
                                SQLiteDatabase.OPEN_READONLY, mErrorHandler);

-> 

db = SQLiteDatabase.openDatabase(path, mFactory,
                                SQLiteDatabase.OPEN_READONLY | SQLiteDatabase.NO_LOCALIZED_COLLATORS, mErrorHandler);

2. Add function to DatabaseOpenHelper:

public Database getNoLocalizedReadableDb() {
        return this.wrap(this.getLocalizedReadableDatabase());
    }
  
the impletation of getNoLocalizedReadableDatabase in 1

**Comment by greenrobot-team** [comment]
Check your stack trace, here is the actual error:
```
4 Caused by:
5 android.database.sqlite.SQLiteFullException:database or disk is full (code 13)
```
-ut
