### ISSUE TITLE
java.lang.NoClassDefFoundError: org/greenrobot/greendao/generator/Schema

### ISSUE THREAD

**Issue by As-k** [greenrobot/greenDAO#828]
Here, I am getting exception.
Please suggest me!
Exception in thread "main" java.lang.NoClassDefFoundError: org/greenrobot/greendao/generator/Schema
![exception](https://user-images.githubusercontent.com/24474092/36091107-a6864b8a-1008-11e8-8e75-a70122f2c931.PNG)

Thanks

**Comment by greenrobot-team** [comment]
Check the note in the [trigger generation docs](http://greenrobot.org/greendao/documentation/generator/#Triggering_generation) with the generator. -ut
