### ISSUE TITLE
Generating duplicate entity method

### ISSUE THREAD

**Issue by dreadful44** [greenrobot/greenDAO#829]
Hi. I implement library like in instruction. I don't have problem with implementation. But greenDao plugin generate duplicate getter/setter method in my entity. But I think understand, only duplicate @Id annotation property's getter setter method. Is there any but with "checkMethod" algorithm ?

<img width="489" alt="issue" src="https://user-images.githubusercontent.com/8416271/36151212-77d22ece-10d7-11e8-8e03-537598abdebc.png">

**Comment by greenrobot-team** [comment]
That is odd, the plugin should detect existing getter/setter methods. Is there anything special about this entity? If you remove both index setters/getters are two generated?

Do you have some special setup, like plugins?

In any case, a small example project to reproduce this would help.
 -ut

**Comment by dreadful44** [comment]
I'm sorry. I give up to use greenDAO. Because for that i dont give more information.

**Comment by sckn** [comment]
I can give more information. What is your need?
