### ISSUE TITLE
GreenDao entity cannot be converted completely with gson in release package?

### ISSUE THREAD

**Issue by sheaye** [greenrobot/greenDAO#831]
I have an entity like this:
```
    @Entity
    public class Version {
        @Id
        private Long id;
        private String name;
        private int version;
        //...
    }
```
When I used it for response bean in debug apk, it is normal. However, when I assemble a release apk, the result bean is not correct. for example, with greendao entity I get the result  : “{id:1, name:null, version:2}” ，but in fact, the name is not null.

**Comment by greenrobot-team** [comment]
Check if there are differences in your release build on how entities are inserted. Otherwise, without an example project reproducing this issue I can not help much. -ut
