### ISSUE TITLE
Multiple level fetching is not working with loadDeep() or queryDeep().

### ISSUE THREAD

**Issue by pavan-nw** [greenrobot/greenDAO#835]
When I have entity A having list of entity B and B has list of entity C then calling loadDeep on ADao object is not giving me C objects it only gives  A --> B.

**Comment by greenrobot-team** [comment]
That only one level is fetched is by design. You have to get the related entity and load its relations again. This is to avoid performance issues with relations that nest very deep (like a tree structure) and gives you control over how deep to resolve relations. -ut
