### ISSUE TITLE
How can i set DatabaseErrorHandler?

### ISSUE THREAD

**Issue by Sejen27** [greenrobot/greenDAO#839]
The OpenHelper which extends DatabaseOpenHelper can't set DatabaseErrorHandler

**Comment by greenrobot-team** [comment]
The OpenHelper in `DaoMaster` is for testing purposes only. You should write your own open helper extending from `DatabaseOpenHelper`. -ut

**Comment by greenrobot-team** [comment]
`3.3.0` has been released which makes this possible.
https://greenrobot.org/greendao/changelog/
