### ISSUE TITLE
Why DatabaseOpenHelper not override SQLiteOpenHelper(Context context, String name, CursorFactory factory, int version, DatabaseErrorHandler errorHandler)

### ISSUE THREAD

**Issue by Sejen27** [greenrobot/greenDAO#841]
Why DatabaseOpenHelper not override SQLiteOpenHelper(Context context, String name, CursorFactory factory, int version, DatabaseErrorHandler errorHandler)

**Comment by greenrobot-team** [comment]
Why should it?

Note: You can also do it yourself.
-ut

**Comment by Sejen27** [comment]
I want to set errorHandler, but when OpenHelper extends DatabaseOpenHelper，it can not access constructor below：

public SQLiteOpenHelper(Context context, String name, CursorFactory factory, int version,
DatabaseErrorHandler errorHandler)

**Comment by greenrobot-team** [comment]
Just noticed this is a duplicate of https://github.com/greenrobot/greenDAO/issues/839.
