### ISSUE TITLE
@Generated annotation is always imported even if generateConstructors is false

### ISSUE THREAD

**Issue by titanseason** [greenrobot/greenDAO#843]
I'm using GreenDao 3, and have an entity:
```
@Entity(generateConstructors = false)
public class User {
   // fields
}
```
but, the @ Generated annotation is always imported,but in fact the  @ Generated is not used

Can you modify the generator, and do not import @ Generated if I set `generateConstructors = false`

**Comment by greenrobot-team** [comment]
Duplicate of #481 -ut
