### ISSUE TITLE
In Gradle 3.1.0 can not work! 

### ISSUE THREAD

**Issue by JanesenHeart** [greenrobot/greenDAO#846]
Failed to resolve: greendao！

**Comment by favsol26** [comment]
it's true, the problem that it's shows is:

 Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018

Failed to resolve: greendao

**Comment by KyungminCho** [comment]
Same here!!!

**Comment by caprice** [comment]
encountered the same issue.

**Comment by MuQi-Jason** [comment]
greendao {
        schemaVersion x 
        daoPackage 'xxx' 
        targetGenDir 'xxx
    }
put it in android {} replace in sourceSets{}

**Comment by greenrobot-team** [comment]
In your app modules `build.gradle` file try to change
`compile 'org.greenrobot:greendao:3.2.2'`
to
`implementation 'org.greenrobot:greendao:3.2.2'`
-ut

**Comment by greenrobot-team** [comment]
Closing due to missing details. Please re-open if you can share a small example project that reproduces this issue. -ut
