### ISSUE TITLE
Error in resource file if I use "  classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'"

### ISSUE THREAD

**Issue by kanshenmekan** [greenrobot/greenDAO#850]
classpath 'com.android.tools.build:gradle:3.1.0'
 classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
If I use this plugin
![9efe3e2b-4ad5-4362-87be-725cfd8b6f6c](https://user-images.githubusercontent.com/26561615/38543674-c4c54c1c-3cd7-11e8-9d77-ecaf3c5fb8e0.png)
![908fe2e2-b2a9-4835-8327-050c17f678b3](https://user-images.githubusercontent.com/26561615/38543675-c5bb0bb6-3cd7-11e8-9619-5bf13591b653.png)
![01e9b768-c383-4462-8ff6-a6951bdcf965](https://user-images.githubusercontent.com/26561615/38543679-c766caae-3cd7-11e8-9804-61f6887d1201.png)
It does not affect program or build。。

**Comment by kanshenmekan** [comment]
and implementation 'com.android.support:appcompat-v7:26.1.0'

**Comment by greenrobot-team** [comment]
This should not be related to greenDAO. Try to rebuild your project.

If you still believe this is caused by the greenDAO plugin, please provide a small example project so we can reproduce (feel free to re-open).
-ut
