### ISSUE TITLE
Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/sqlcipher/database/SQLiteOpenHelper

### ISSUE THREAD

**Issue by ZQiang94** [greenrobot/greenDAO#851]
Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/sqlcipher/database/SQLiteOpenHelper

**Comment by greenrobot-team** [comment]
See #428. Please re-open with steps how to reproduce if that does not solve your problem. -ut
