### ISSUE TITLE
How to update schema version and add column in existing table

### ISSUE THREAD

**Issue by vigneshhR** [greenrobot/greenDAO#854]
Schema schema = new Schema(1,"greendao");

        Entity UserDetails = schema.addEntity("UserDetails");
        UserDetails.addIntProperty("UserId");
        UserDetails.addStringProperty("Name");
        UserDetails.addIntProperty("Age");
        UserDetails.addStringProperty("Gender");

        DaoGenerator daoGenerator = new DaoGenerator();
        daoGenerator.generateAll(schema,args[0]);

How to add more columns in that table using generator class and its changes reflects on auto generated class or not?

**Comment by greenrobot-team** [comment]
Make your changes and increase the schema version, then run the generator again.

We recommend using the Gradle plugin to generate code instead.
-ut
