### ISSUE TITLE
getId() return null

### ISSUE THREAD

**Issue by LordSuricato** [greenrobot/greenDAO#856]
Every time I call objectFromDb.getId() its value is null.

My generator:

`  
        Entity messagesPush = schema.addEntity("MessagePush");
        messagesPush.addIdProperty().autoincrement().primaryKey().unique();
        messagesPush.addIntProperty("itemId");
`

GreenDao v3.2.2

**Comment by greenrobot-team** [comment]
Closing due to missing details. Please re-open if you can share a small example project that reproduces this issue. -ut
