### ISSUE TITLE
How to build greenDao before source code in android studio

### ISSUE THREAD

**Issue by pardeep632** [greenrobot/greenDAO#857]
Just to clarify , its not an issue . I need some suggestion on usage of greendao for my problem defined below.

I am working on an android application which uses GreenDao (ORM) for Object Relation mapping . I have defined entity classes in my code. When i build the code , greendao generates Dao classes corresponding to the entities.

It also generates DaoMaster and DaoSession classes. So using DaoSession and Dao classes i start coding and implemented by logic. Now when i commit to github , i do not want to push the generated files. Since my code is dependant on generated files, when someone takes my code from github , he does not get the generated file (because i did not push them). So he gets build errors that some classes are not there like DaoMaster and DaoSession etc.

To overcome this , he has to comment all the code which uses these generated files and build it. Now build succeeds and DaoMaster and DaoSession gets generated. Now he has to uncomment the previously commented code . Because now the classes are generated.

But this approach seems very tedious because there can be a lot of code. So i was thinking may be if there is a way to generate the Dao files first before the source code is built. I mean when i start the build command , is there a way to specify that first build this , then this . So that first the greenDao library gets built and DaoMaster , DaoSession and Daos are generated and then source code gets built and since now Dao files are available it will succeed.

Or may be there is some other way to do this. I tried to find options for first approach , but could not find much help .Please suggest how to tackle this .

**Comment by greenrobot-team** [comment]
When opening a new project in Android Studio (3.1.2) it is automatically built, which also generates greenDAO classes. I just verified this using our example project.
If a build is not triggered automatically, use `Build > Make Project`.
-ut

**Comment by keyescgm** [comment]
how generate entity & days by annotations ,thanks~

**Comment by keyescgm** [comment]
How generate entities & daos by annotations ,thanks!

**Comment by keyescgm** [comment]
I needs principle

**Comment by greenrobot-team** [comment]
http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/
http://greenrobot.org/greendao/documentation/introduction/
http://greenrobot.org/greendao/documentation/modelling-entities/
