### ISSUE TITLE
Cannot resolve symbol 'Theme'

### ISSUE THREAD

**Issue by qq596670409** [greenrobot/greenDAO#859]
After sync greenDao,Theme change to red,the information is : Cannot resolve symbol 'Theme'
What's wrong?

**Comment by qq596670409** [comment]
<style name="AppTheme" parent="Theme(Here!Become Red).AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

**Comment by greenrobot-team** [comment]
This is unlikely a greenDAO issue. Check your dependencies.

Closing. Please re-open if you can share a small project reproducing this issue.
-ut
