### ISSUE TITLE
make greendao work with databases created by other libraries...?

### ISSUE THREAD

**Issue by deostroll** [greenrobot/greenDAO#861]
Hi,

Firstly, love this framework. It really increases my productivity when working with databases on android. 

Now there is a particular requirement I am hoping to get help with. For e.g. logback-android (a logging framework for android) has an option to store logs into sqlite tables. The framework internally manages all the database/tables creation necessary for this.

How can you make greendao work with that database?

**Comment by greenrobot-team** [comment]
And closing as this is a programming question. -ut
