### ISSUE TITLE
Multiple threads simultaneously operate on different tables

### ISSUE THREAD

**Issue by wuxinxi** [greenrobot/greenDAO#862]
Multi-threaded operation of different tables at the same time, how to deal with each other will not have their own impact, that is, work at the same time，thanks！

**Comment by greenrobot-team** [comment]
SQLite on Android and greenDAO on top should be thread-safe in general or behave as expected.

To re-use a `Query` in another thread [there is `forCurrentThread()`](http://greenrobot.org/greendao/documentation/queries/#Executing_queries_in_multiple_threads).

You also might want to look at the [Sessions](http://greenrobot.org/greendao/documentation/sessions/) documentation which talks about object caching.
-ut
