### ISSUE TITLE
fastJSON  greenDAO  clash

### ISSUE THREAD

**Issue by dahai2070** [greenrobot/greenDAO#863]
greenDao override some  get***() which use  @ToMany(referencedJoinProperty = "***"),
but fastJson need standard get method when serialize，so they are clash...
I don't know there hava any api can specify the get*** method name .....

**Comment by greenrobot-team** [comment]
You could try `@Entity(generateGettersSetters = false)`. But not sure if that works with `@ToMany`.

Closing. Please re-open if your question was not answered.
-ut
