### ISSUE TITLE
Multi Module Project Sync failed on Android

### ISSUE THREAD

**Issue by milan400** [greenrobot/greenDAO#864]
**app2**
``[apply plugin: 'com.android.application'
android {
    compileSdkVersion 24
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "com.example.kiran.chatapp"
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:cardview-v7:24.0.0'
    implementation 'com.android.support:recyclerview-v7:24.0.0'
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:24.0.0'
    implementation 'com.google.firebase:firebase-database:9.2.0'
    implementation 'com.google.firebase:firebase-crash:9.2.0'
    implementation 'com.google.firebase:firebase-auth:9.2.0'
    implementation 'com.firebase:firebase-client-android:2.3.1'
    implementation 'com.google.firebase:firebase-messaging:9.2.0'
    implementation 'com.firebaseui:firebase-ui-database:0.4.2'
    implementation 'com.firebaseui:firebase-ui:0.4.2'
    implementation 'com.google.firebase:firebase-storage:9.2.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.google.android.gms:play-services-auth:9.2.0'
    implementation project(':app')
}
apply plugin: 'com.google.gms.google-services'](url)`

**Log Message**

[]( Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Unable to resolve dependency for ':app2@debug/compileClasspath': Could not resolve project :app.
Open File
Show Details

Unable to resolve dependency for ':app2@debugAndroidTest/compileClasspath': Could not resolve project :app.
Open File
Show Details

Unable to resolve dependency for ':app2@debugUnitTest/compileClasspath': Could not resolve project :app.
Open File
Show Details

Unable to resolve dependency for ':app2@release/compileClasspath': Could not resolve project :app.
Open File
Show Details

Unable to resolve dependency for ':app2@releaseUnitTest/compileClasspath': Could not resolve project :app.
Open File
Show Details)

`

**Comment by milan400** [comment]
Element: class org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl because: different providers: SingleRootFileViewProvider{myVirtualFile=file:///media/milan/data drive/english/Blog/ChatApp/settings.gradle, content=VirtualFileContent{size=17}}(3bcf70e6); SingleRootFileViewProvider{myVirtualFile=file:///media/milan/data drive/english/Blog/ChatApp/settings.gradle, content=VirtualFileContent{size=17}}(4aad9227)

**Comment by greenrobot-team** [comment]
You are not even using greenDAO in your dependencies. Also the error is `Could not resolve project :app.`. I'm not sure how we can help here. -ut
