### ISSUE TITLE
the DaoMaster.OpenHelper only get database once?if  init with error and return a onlyreadable database?

### ISSUE THREAD

**Issue by icemanstudy** [greenrobot/greenDAO#865]
I noticed that getdatabase just called once:
DevOpenHelper helper = new DevOpenHelper(this, "notes-db");
Database db = helper.getWritableDb();     //line 2
daoSession = new DaoMaster(db).newSession();

Note the line2. Whether getWritableDb or getReadableDb,there maybe have some anomalies that result in just a read-only database().For example, disk problems or permissions issues.

After that, if you try to write database(just like insert/delete), you will get a SQLiteReadOnlyDatabaseException.

I did not find any place to reacquire the database.
So,how to avoid this situation?

**Comment by liruidong183** [comment]
I got the same question. Do you have any ways to solve this problem? Thx.

**Comment by greenrobot-team** [comment]
Note that `DevOpenHelper` is just a [`SQLiteOpenHelper`](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper). You should try searching for issues regarding `SQLiteOpenHelper getWritableDatabase` returning a non-writable database.

I am not aware of issues regarding that so have no workarounds, sorry.
-ut
