### ISSUE TITLE
Building Project creates a different DaoSession and DaoMaster on Windows vs Mac

### ISSUE THREAD

**Issue by bschnack** [greenrobot/greenDAO#869]
Every time a mac builds our project, the DaoSession and DaoMaster gets created with what seems like a random order of variables. On windows however, it appears to be sorting the variables in alphabetical order. Is there a way to make this so that the files don't change based on what OS checked in last? It is making it so that our git shows changes that are not intentional.

**Comment by wurensen** [comment]
orz...

**Comment by wurensen** [comment]
@bschnack I develop a plugin resolved the problem.Just use it to replace the 'greendao-gradle-plugin'. [https://github.com/wurensen/Greendao3GradlePlugin](url)

**Comment by greenrobot-team** [comment]
This was diagnosed pretty well by @wurensen in #880. Though I can't promise a timely fix. -ut
