### ISSUE TITLE
How to use "join"?

### ISSUE THREAD

**Issue by Caeson** [greenrobot/greenDAO#871]
Suppose that I have two class: `User` and `Book`. The details are shown as follows.

```
@Entity
public class User {

    @Id(autoincrement = true)
    private Long id;

    private String name;

    private int age;

    private int sex;
}

@Entity
public class Book {

    @Id(autoincrement = true)
    private Long id;

    private String name;

    private Long userId;
}
```

If I want to execute the raw sql `select * from USER inner join BOOK on USER._id = BOOK.USER_ID`, what should I do in GreenDao?

Or I can only just use Sqlite native api like:

```
Cursor cursor = db.rawQuery("select * from USER inner join BOOK on USER._id = BOOK.USER_ID", null);
```

Thanks very much!

**Comment by Caeson** [comment]
Must I use the annotation `@ToMany`?

**Comment by greenrobot-team** [comment]
If you do not add a `@ToMany` the returned `User` objects will not have data from the related `Book` classes. Otherwise this should work, did you try?

Closing because this issue is old. Please re-open if you have more to say.
-ut

**Comment by Caeson** [comment]
Thanks very much! Now I'm using `@ToMany`.
