### ISSUE TITLE
How share database based on GreenDAO in app in another App ?

### ISSUE THREAD

**Issue by dononcharles** [greenrobot/greenDAO#872]
Hi, 
I would appreciate if anyone can help communicate with GreenDAO database in another application.
Tks

**Comment by greenrobot-team** [comment]
Do you mean across (app) processes? On Android this is typically solved [using a ContentProvider](https://developer.android.com/reference/android/content/ContentProvider).

SQLite (what greenDAO is based on) does not support inter-process communication.

Closing. Please re-open if your question was not answered.
-ut
