### ISSUE TITLE
error: cannot find symbol class DaoSession

### ISSUE THREAD

**Issue by lsaulcastro** [greenrobot/greenDAO#874]
I need help, Greendao is generating DaoSession and DaoMaster but it is generating it in a package that should not be done, someone some suggestion for me to tell you where I generate these classes
Greendao version 3.2.2

**Comment by greenrobot-team** [comment]
greenDAO automatically chooses a package based on where your entities are stored.

You can try to [set the daoPackage property](http://greenrobot.org/greendao/documentation/modelling-entities/#Schema) in the greendao closure:
```
greendao {
    schemaVersion 6
    daoPackage "com.example.model"
}
```
Though note that all generated classes will then be created in that package.

Closing. Please re-open if your question was not answered.
-ut

**Comment by tennkou** [comment]
not work for me
