### ISSUE TITLE
How can I modify the encryptedDb's password?

### ISSUE THREAD

**Issue by CaptainJno** [greenrobot/greenDAO#875]
I set up a password(ex. 111)  when I create a EncryptedWritableDb. Now , I want modify the password to a new one(ex. 222). 
How can I do?  I can't find proper api. Please help me.
@greenrobot @greenrobot-team

**Comment by greenrobot-team** [comment]
greenDAO does not handle encryption, SQLCipher does. Check their docs on [how to change the encryption key](https://www.zetetic.net/sqlcipher/sqlcipher-api/#rekey).

Closing. Please re-open if your question was not answered.
-ut
