### ISSUE TITLE
I want insertOrReplace where something ,what should I do

### ISSUE THREAD

**Issue by HappyJie135588** [greenrobot/greenDAO#876]
I want insertOrReplace where something ,what should I do

**Comment by greenrobot-team** [comment]
Your Dao classes should have `insertOrReplace()` methods. Here is a [link to the online javadoc](http://greenrobot.org/files/greendao/javadoc/current/org/greenrobot/greendao/AbstractDao.html#insertOrReplace-T-).

Closing. Please re-open if your question was not answered.
-ut
