### ISSUE TITLE
Building Project creates a different DaoSession and DaoMaster on Windows vs Mac

### ISSUE THREAD

**Issue by JeckChou** [greenrobot/greenDAO#880]
when I compile my project , the files that DaoMaster and DaoSession will be changed even I have to do nothing with it.  I`m puzzled by this change when I track them with git version control. what should I do to avoid it ? 
any one can help me ? thanks

**Comment by wurensen** [comment]
The same to me.Compile on Mac.

**Comment by wurensen** [comment]
I decompile plugin classes, find that the reason of wrong sort is  "Java File.class" creating File(is a directory) object depends on the PC Operate System. On windows, children of the  directory File Object are sorted by dictionary, e.g A.java, B.java, C.java, etc.But on my macOS(version 10.13.5), there are B.java, C.java. A.java.
So I hope the greenDAO plugin can resort the java source files list before executing DetectEntityCandidatesTask.

**Comment by wurensen** [comment]
@JeckChou I develop a plugin resolved the problem.Just use it to replace the 'greendao-gradle-plugin'. [https://github.com/wurensen/Greendao3GradlePlugin](url)

**Comment by MappApp** [comment]
@wurensen thank you for your reply. you solve my problem. I`m develop on mac too. but from my partner, he is also face to the same problem with window system. it is strange

**Comment by JeckChou** [comment]
@wurensen thanks for your help

**Comment by wurensen** [comment]
@MappApp Let your partner use my plugin and run the gradle task 'greendaoGenerate'

**Comment by greenrobot-team** [comment]
As a workaround you can try to [set the daoPackage property](http://greenrobot.org/greendao/documentation/modelling-entities/#Schema) in the greendao closure:
```
greendao {
    schemaVersion 6
    daoPackage "com.example.model"
}
```
This way greenDAO won't choose a package automatically.
-ut

**Comment by wurensen** [comment]
@greenrobot-team It doesn't work.At first my team set 'daoPackage'.

**Comment by greenrobot-team** [comment]
@wurensen What does not work? Are the generated classes still in another package? -ut

**Comment by wurensen** [comment]
I mean the contents of 'DaoMaster.java' aren't sorted by dictionary.

**Comment by manisoft83** [comment]
If we use 'daoPackage "com.example.model"' than it is ignoring all subfolders.
e.g.,  Ignoring sub folder when we have entity under "com.example.model.test.TestModel", TestModelDAO is getting created under "com.example.model".

**Comment by greenrobot-team** [comment]
This issue was fixed internally (imports are now always sorted) and will be available with the next update.

Note: Anyhow I recommend generating the greenDAO classes on-demand into the build folder and removing them from source control. E.g. remove `targetGenDir` from the `greendao` options in `build.gradle`.

**Comment by greenrobot-team** [comment]
`3.3.0` has been released which should fix this issue.
https://greenrobot.org/greendao/changelog/
