### ISSUE TITLE
QUESTION: create entity from third party api on greendao

### ISSUE THREAD

**Issue by bolds07** [greenrobot/greenDAO#881]
I want to use greendao as persistence framework for my Android App.

I'm using a third party api to fecth data from a backend (i've no access to the api code)

I want to persist one of the api entities in my app using greendao, how can i do that?

On hibernate I could achieve it by extending the class, overriding the get methods and using @Access(AccessType.PROPERTY) and adding the extra fields that i need

is there a similar way to do without recreating the whole entity class?

**Comment by greenrobot-team** [comment]
This will not work as greenDAO [does not support entity inheritance](https://github.com/greenrobot/greenDAO/issues/362). You likely will have to re-create the model with greenDAO and copy data from the entities you receive from your backend.

Closing. Please re-open if your question was not answered.
-ut
