### ISSUE TITLE
Relations @toMany with standard type

### ISSUE THREAD

**Issue by bolds07** [greenrobot/greenDAO#882]
Is there any way to have an entity with a one to many relationship with an standard type?

something like

```
class A {
...
private List<Integer> ids;
...
}
```

**Comment by greenrobot-team** [comment]
No, [relations](http://greenrobot.org/greendao/documentation/relations/) can only be between entities. If you want to store a plain list of things, [use a converter](http://greenrobot.org/greendao/documentation/custom-types/).

Closing. Please re-open if your question was not answered.
-ut
