### ISSUE TITLE
Where is NoteDao located?

### ISSUE THREAD

**Issue by sh3r1** [greenrobot/greenDAO#883]
When reviewing the example codes. I found that you declared ***NoteDao*** 

```
public class NoteActivity extends AppCompatActivity {

    private EditText editText;
    private View addNoteButton;

    private NoteDao noteDao;
    private Query<Note> notesQuery;
    private NotesAdapter notesAdapter;
```

**Comment by greenrobot-team** [comment]
This class is generated when building the project for the first time. There is some background info on this [in the documentation](http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/#greenDAO_3_Gradle_Plugin). But generally do not worry about this and just (re-)build your project and those classes will be generated for you by the plugin.

Closing. Please re-open if your question was not answered.
-ut
