### ISSUE TITLE
Plugin with id 'org.greenrobot.greendao' not found.

### ISSUE THREAD

**Issue by shijia109** [greenrobot/greenDAO#884]
Why I cant depend GreenDao although I totally following the document?

**Comment by greenrobot-team** [comment]
Compare your setup [with my example](https://github.com/greenrobot-team/greenrobot-examples/tree/master/greendao).

Also check if you are using a proxy or your network blocks access to https://repo1.maven.org/maven2/org/greenrobot/greendao/3.2.2/

Closing. Please re-open if your question was not answered.
-ut
