### ISSUE TITLE
> Constructor generated code is not the same with others

### ISSUE THREAD

**Issue by caizhibiao** [greenrobot/greenDAO#885]
> Constructor (see XXbeanClass:XX) has been changed after generation.
Please either mark it with @Keep annotation instead of @Generated to keep it untouched,
or use @Generated (without hash) to allow to replace it.

**Comment by greenrobot-team** [comment]
By default greenDAO does not allow you to modify the generated constructors of an entity.

If you still want to modify the constructor, replace the `@Generated` annotation with a `@Keep` annotation:
```java
@Keep
public BeanClass() {
    ...
}
```

[See the documentation for details](http://greenrobot.org/greendao/documentation/modelling-entities/#Modifying_generated_code).

Closing. Please re-open if your question was not answered.
-ut

**Comment by nicanorgarcia** [comment]
Hello,

We are having this problem after uploading to github and one of my team members is trying to Build on his local version.

Any help would be greatly appreciated.

Thank you
