### ISSUE TITLE
Currently only single FK columns are supported: ToOne 'dpObjectsDB' from DpPointsListDB to DpObjectsDB

### ISSUE THREAD

**Issue by ShakeelAhmed210** [greenrobot/greenDAO#886]
Hi GreenDAO Team.  
I am working on a project and I have used greenDAO library. I am able to add @ToMany  relations successfully. But I am unable to add @ToOne relation. I have read the official document and tried the same but no success.  
here are my classes.

```
@Entity
public class DpPointsListDB {

    @Id
    private long id;

    public long getId() {
        return this.id;
    }
 @ToOne
    private DpObjectsDB dpObjectsDB;

    public DpObjectsDB getDp() {
        return this.dpObjectsDB;
    }

    public void setDp(DpObjectsDB dp) {
        this.dpObjectsDB = dp;
    }

}

////////// second class DpObjectsDB
@Entity
public class DpObjectsDB {

private int someId;

    public int getSomeId() {
        return this.someId;
    }

    public void setSomeId(int someId) {
        this.someId = someId;
    }
}
```

**Comment by greenrobot-team** [comment]
Your `DpObjectsDB` class is missing an `@Id` property.

The [documentation has an example](http://greenrobot.org/greendao/documentation/relations/). You can also [check out my greenDAO example](https://github.com/greenrobot-team/greenrobot-examples/tree/master/greendao), look for the `Order` and `Customer` classes.

Closing. Please re-open if your question was not answered.
-ut
