### ISSUE TITLE
Green dao changing generated code indentation after each build

### ISSUE THREAD

**Issue by LoudMurmur** [greenrobot/greenDAO#892]
Hi,
Each time I build some of my entities indentation in the generated code changes : 

if I commit this : 
![image](https://user-images.githubusercontent.com/1658755/43828815-d6c705b6-9afd-11e8-95a2-2a1cf9b26a57.png)

the the next build it will revert it to this : 
![image](https://user-images.githubusercontent.com/1658755/43828879-f61fcbbe-9afd-11e8-9be8-397246b93d04.png)

I'm using this version : 'org.greenrobot:greendao:3.2.0'

Thanks.

**Comment by greenrobot-team** [comment]
The greenDAO generator will update your entity classes on each build and uses default code formatting. This is working as intended.

You should commit the generated version with the standard-size indents.
-ut
