### ISSUE TITLE
sqllite表名、表字段为中文时映射出来的实体类，自动生成dao、master等代码时出现乱码

### ISSUE THREAD

**Issue by 13871591944** [greenrobot/greenDAO#895]
如题，请大佬赐教如何解决

**Comment by ljk761626336** [comment]
解决了吗？

**Comment by ljk761626336** [comment]
谢谢 我也试试

**Comment by greenrobot-team** [comment]
Please write in English if you post to this issue tracker so others can understand.

I suspect the issue was that Gradle or your IDE did not use UTF-8 file encoding. Adding
`-Dfile.encoding=UTF-8`
to your `gradle.properties` file at least tells Gradle to use UTF-8.

Closing then as resolved.
-ut
