### ISSUE TITLE
maybe a bug about cache?

### ISSUE THREAD

**Issue by shinerdeng** [greenrobot/greenDAO#90]
I did not find anywhere to update the identityScopeLong cache, so if i had called loadCurrent(Cursor cursor, int offset, boolean lock) method,then cached entities,when i execute update the entities and call loadCurrent again, i will get the cached entities, it has not been updated.

**Comment by fabioranieri** [comment]
Hi, I have a similar problem. In my project i have Entity with inner entity when update data the inner entity not refresh data. If i close application and clear session or refresh entity with Dao.refresh() method all is OK.

**Comment by CarlosPampin** [comment]
When creating the session use:
`new DaoMaster(db).newSession(IdentityScopeType.None); `

instead of:
`new DaoMaster(db).newSession();`
