### ISSUE TITLE
Reencrypt the existing database

### ISSUE THREAD

**Issue by iNomaD** [greenrobot/greenDAO#900]
I already have a database created in my application like
```
DevOpenHelper helper = new DevOpenHelper(this, "notes-db-encrypted.db");
Database db = helper.getEncryptedWritableDb("<your-secret-password>");
```
Is it possible to change the "secret-password" without loosing data?

**Comment by greenrobot-team** [comment]
See my comment at https://github.com/greenrobot/greenDAO/issues/875#issuecomment-414642345
-ut
