### ISSUE TITLE
Allow to pass custom table name to AbstractDao.createTable ?

### ISSUE THREAD

**Issue by vostreltsov** [greenrobot/greenDAO#902]
It would be nice to have the ability to pass custom table name to createTable.

It would be even better to have a separate static method returning the `create table` statement as string.

Example use case: I am writing a migration, and because sqlite has terrible support of `alter table`, I create a new table, insert previous data, delete the old table, rename the new table. And I would *love* to have an auto-generated create table statement.

**Comment by greenrobot-team** [comment]
Then I would argue it is much safer to write the statement on your own. What if your schema changes again? Then the create table statement would be different and potentially break your old migration code.

Side note: you can define the name of the table entity data is stored in [using the `@Entity` annotation](http://greenrobot.org/greendao/documentation/modelling-entities/#The_Entity_Annotation).
-ut

**Comment by vostreltsov** [comment]
No, dao classes are up-to-date, as well as the "create table" statement. At the moment I need to copy-paste it to the migration.

**Comment by vostreltsov** [comment]
Alright, better late than never. At last, I've got what you meant by "potentially break your old migration code."
Indeed, the issue can be closed.
