### ISSUE TITLE
How to Read Existing data from SQLCipher Password Protected Db?

### ISSUE THREAD

**Issue by chnouman** [greenrobot/greenDAO#904]
I'm following the way you mentioned in example to attach sqlcipher db with greendao. It is working perfectly in all ways but in daoSession object their is no record found.

I have follow this code:
```
        // regular SQLite database
        DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, "notes-db");
        Database db = helper.getWritableDb();

        // encrypted SQLCipher database
        // note: you need to add SQLCipher to your dependencies, check the build.gradle file
        // DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, "notes-db-encrypted");
        // Database db = helper.getEncryptedReadableDb("123456");

        daoSession = new DaoMaster(db).newSession();
```

Please Help me to read the data.

**Comment by chnouman** [comment]
@greenrobot-team

**Comment by greenrobot-team** [comment]
You need to actually comment out the code for the encrypted database:

```
// encrypted SQLCipher database
// note: you need to add SQLCipher to your dependencies, check the build.gradle file
DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, "notes-db-encrypted");
Database db = helper.getEncryptedReadableDb("123456");

daoSession = new DaoMaster(db).newSession();
```
Closing. Please re-open if your question was not answered.
-ut

**Comment by chnouman** [comment]
@greenrobot-team  i already have commented the unnecassery code i also have sqLcipher dependency the issue is i get the daoSession object with all dao objects but i have no data avaialble allt he daoPerson.queryBuilder().list() return me 0.
