### ISSUE TITLE
tomany relationship lost after restart application

### ISSUE THREAD

**Issue by namdk89** [greenrobot/greenDAO#91]
I have a db create by generator:

Entity album = schema.addEntity("Album");
        album.addIdProperty();
        album.addLongProperty("albumId").unique();
        album.addStringProperty("title");
        album.addLongProperty("coverObjId");
        album.addLongProperty("previewObjId");
        album.addLongProperty("createDate");
        album.addLongProperty("lastModify");

```
    Entity obj = schema.addEntity("Obj");
    obj.addIdProperty();
    Property objId = obj.addLongProperty("objId").unique().getProperty();
    obj.addLongProperty("createDate");
    obj.addStringProperty("imageLink");

    Property albumOwner = obj.addLongProperty("albumRowId").notNull().getProperty();
    obj.addToOne(album, albumOwner);
```

First time, when db create, everything work cool. But after that, i force stop app and  start again then album always get obj list is empty.

**Comment by JBrannennMobileDev** [comment]
I am having a similar issue using greenDAO v3. Everything works fine until i close and reopen the app. Then all of the @ToMany fields are dropped from the db.  This is what my entity looks like. 

@Entity
public class Lead implements Comparable<Lead>{
     @ToMany(referencedJoinProperty = "lead_id") private List<LeadStage> leadStages;
}

and 

@Entity
public class LeadStage {
    @NotNull private long lead_id;
    @Id private Long lead_stage_id;
    
    @Generated(hash = 1589227946)
    public LeadStage(long lead_id, Long lead_stage_id) {
        this.lead_id = lead_id;
        this.lead_stage_id = lead_stage_id;
    }

    @Generated(hash = 166566870)
    public LeadStage() {
    }
