### ISSUE TITLE
A bug on greendao-gradle-plugin when parallel execution task :app:greendao

### ISSUE THREAD

**Issue by zhenian** [greenrobot/greenDAO#922]
I have no right to reopen  #914 . So I add  this new issue reference to  #914 

NOTE: I had add a demo to replay the bug  #914  which was described at (https://github.com/greenrobot/greenDAO/issues/914#issuecomment-436301034)

**Comment by greenrobot-team** [comment]
Thanks, I saw your comment and will reopen the issue. -ut
