### ISSUE TITLE
How to query the data of the specified column, and the result returns a list

### ISSUE THREAD

**Issue by DearDaXiong** [greenrobot/greenDAO#923]
for example, if i have a table what is people,and its column name hava name, age ,sex ,address.
Then, i want to query the data of the specified column what is name from table. 
its sql statement is "select name from people".
Then How can I use Greendao to execute this sql statement?

**Comment by greenrobot-team** [comment]
You can not. greenDAO explicitly maps your table rows to a whole object. The data to object mapping is the whole point of using greenDAO. If that is not what you need, greenDAO is not what you need.
-ut
