### ISSUE TITLE
Dao Models returning null

### ISSUE THREAD

**Issue by SamerDiab** [greenrobot/greenDAO#926]
Hello, i have everything configured to run with DAO3 and is properly functioning. Until i add a field to my model and update schema from gradle.  Then i start getting null on every session call outside insertion activity.
For example, i insert data, i can retrieve it on insertion thread, but after i go to another thread and recreate session, it returns null. 
Note that initially everything worked ok, data was persisting, but after updating the db this happens. 
And i have a feild of custom type in which i annotated @Transient, i tried to see if that might be the issue, but i guess not.
I tried to uninstall app and reinstall. Tried dropping all tables, still same error persists.

**Comment by greenrobot-team** [comment]
Sorry, I can't help much without an example project to reproduce this.

Did you make sure to write your own class extending `org.greenrobot.greendao.example.DaoMaster.OpenHelper` and implementing `onUpgrade()` to add the new column for your additional field?

Note that the default `DevOpenHelper` will drop all tables on upgrading.
-ut

**Comment by SamerDiab** [comment]
Thank you for your reply, and yes i made sure of that, the error got so hectic i decided to put it aside and move on, and maybe come back to it later; Other than that, great job with the library, i love it!
