### ISSUE TITLE
!!! Only static classes are supported if converters or custom types (@Convert)...

### ISSUE THREAD

**Issue by barnett-yuxiang** [greenrobot/greenDAO#928]
Hi Owner:
    I define entity ChannelEntity.java

```java

@Entity
public class ChannelEntity {
    ....
    @Convert(converter = ChannelBizDataConverter.class, columnType = String.class)
    private Object mBizData;
    ...
}

```

sync project and i got error message:
    "Caused by: java.lang.IllegalArgumentException: Inner class com.uc.ark.data.biz.ChannelEntity.Object in ChannelEntity has to be static. Only static classes are supported if converters or custom types (@Convert) are defined as inner classes."

Object is very common usage, it is forbiden in greeDao?

**Comment by greenrobot-team** [comment]
Yes, using `Object` is not supported.

-- [Check out ObjectBox](https://objectbox.io), our new fast, easy to use database!
