### ISSUE TITLE
Generating duplicate entity method Please help me!

### ISSUE THREAD

**Issue by unalzafer** [greenrobot/greenDAO#929]
![ekran alintisi](https://user-images.githubusercontent.com/25821719/49995803-47d72d80-ff9e-11e8-8973-8cf208c34b9e.JPG)

Your own example. Automatic method. This is Problem.

classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
apply plugin: 'com.android.application'
implementation 'org.greenrobot:greendao:3.2.2'

**Comment by greenrobot-team** [comment]
Works fine for me. Try to delete the duplicate methods and then rebuild your project.

**Comment by mustafaynk** [comment]
I have a same problem. Could anyone help me?
