### ISSUE TITLE
a column‘s type is byte[] ，Property.eq(Object value) throw a DaoException。

### ISSUE THREAD

**Issue by Jamie-gilbert** [greenrobot/greenDAO#930]
In my database ,a cloumn's type is byte[] . When I use the method that  eq(Object value) of Property class,it can throw a DaoException . When I check the code ,I find  " if (value != null && value.getClass().isArray()) {
                throw new DaoException("Illegal value: found array, but simple object required");
            }‘’. So how to do query with  compare to byte array.

thanks for your reply.

**Comment by greenrobot-team** [comment]
This has been answered at https://stackoverflow.com/questions/19157821/greendao-on-android-byte-array-as-primary-key-building-query-containing-where

-- [Check out ObjectBox](https://objectbox.io), our new fast, easy to use database!
