### ISSUE TITLE
Unused Import

### ISSUE THREAD

**Issue by crearo** [greenrobot/greenDAO#932]
My PMD fails because greendao imports `import org.greenrobot.greendao.annotation.Generated;` by default. My model looks like this:

    @Entity(
            generateGettersSetters = false,
            generateConstructors = false
    )
    @Getter
    @Setter
    @AllArgsConstructor
    @SuppressWarnings("PMD.UnusedImports")
    public class ActionRecord {

        @Id
        private Long id;
        @Convert(converter = CommandConverter.class, columnType = Integer.class)
        private com.tonbo.streamer.core.Id.Command command;
        private long timestamp;
        private int sessionId;

        public ActionRecord() {
        }
    }

Can this please be addressed in the next version? 
Also, a side note, for some reason, PMD's `UnusedImports` is still being triggered even after I set the `SuppressWarnings`.

**Comment by greenrobot-team** [comment]
See https://github.com/greenrobot/greenDAO/issues/481

-- [Check out ObjectBox](https://objectbox.io), our new fast, easy to use database!
