### ISSUE TITLE
When inserting 40,000 pieces of data, the query is 36570 pieces of data.

### ISSUE THREAD

**Issue by small-tree** [greenrobot/greenDAO#933]
Why is my "22222222222222221" only 10 sub-data?

<img width="741" alt="wechatimg17293" src="https://user-images.githubusercontent.com/9458238/50502667-f2ba1200-0a9b-11e9-9fd7-84a5b2676709.png">
<img width="1035" alt="wechatimg17294" src="https://user-images.githubusercontent.com/9458238/50502668-f483d580-0a9b-11e9-9bae-54d51a3230aa.png">
<img width="940" alt="wechatimg17295" src="https://user-images.githubusercontent.com/9458238/50502671-f64d9900-0a9b-11e9-8b9e-187cc3d3d650.png">

**Comment by megatronst** [comment]
老铁这个问题解决没有啊

**Comment by small-tree** [comment]
for 循环拼接字符串有重复的  ，结果没问题。 生成的字符串数量是对的
