### ISSUE TITLE
can not access to org.greenrobot.greendao.AbstractDaoSession

### ISSUE THREAD

**Issue by xielihuang** [greenrobot/greenDAO#934]
i have a new project, and import greendao3.2.0,   i use greendao by singleton, the code like this:

```
package com.xlh;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import com.xlh.generate.DaoMaster;
import com.xlh.generate.DaoSession;

/**
 * 数据库管理类,连接数据库;
 */
public class DBManager {

    private DBManager() {
    }

    private static class DBHolder {
        static DBManager manager = new DBManager();
    }

    public static DBManager getInstance() {
        return DBHolder.manager;
    }

    private DaoMaster daoMaster;
    private DaoSession daoSession;
    private DBHelper dbHelper;

    public DaoSession getDaoSession() {
        if(daoSession != null)
            return daoSession;
        return null;
    }

    /**
     * 打开数据库连接
     *
     * @param context
     */
    public void connectDB(Context context) {
        dbHelper = new DBHelper(context, "electric.db");
        SQLiteDatabase database = dbHelper.getWritableDatabase();
        daoMaster = new DaoMaster(database);
        daoSession = daoMaster.newSession();
    }


    /**
     * 关闭数据库连接
     */
    public void disConnectDB() {
        if (dbHelper != null) {
            dbHelper.close();
            dbHelper = null;
        }
        if (daoMaster != null)
            daoMaster = null;
        if (daoSession != null)
            daoSession.clear();
        daoSession = null;
    }
}
```

when i use this singleton, the AS tell me, cannot acess to  org.greenrobot.greendao.AbstractDaoSession;
![image](https://user-images.githubusercontent.com/20060515/50571181-7c404b80-0dde-11e9-9538-f08e6feb378a.png); 
![image](https://user-images.githubusercontent.com/20060515/50571187-ab56bd00-0dde-11e9-9f7e-1193b87e3155.png)
i use DBManger to get DaoSession,but no method such as insert,update,query,delete and so on... i can not know why, please help

**Comment by greenrobot-team** [comment]
Sorry, this is an issue with your project or with Android Studio/IntelliJ IDEA. We can't help here.

**Comment by LouisRenWeiWei** [comment]
I also have this problem, can any one tell me why ? first time meet this

**Comment by xielihuang** [comment]
hello , i had met this problem when i had created a app module and a library module;
the app module depend on the library , and greendao lib was imported in library module;
and now, i resolve this problem; the reason that greendao must be imported in app module, if you not,you can see error such as i met;

**Comment by LouisRenWeiWei** [comment]
@xielihuang  , you method is ok , i don't understanc

**Comment by SimonRepo** [comment]
api 'org.greenrobot:greendao:3.2.2' 
If your greendao is in the library ，you must use api or compile ,do not use implementation.

**Comment by xielihuang** [comment]
thanks.




------------------ 原始邮件 ------------------
发件人: "Simon"<notifications@github.com>; 
发送时间: 2019年7月5日(星期五) 中午11:24
收件人: "greenrobot/greenDAO"<greenDAO@noreply.github.com>; 
抄送: "谢立煌"<1517076156@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [greenrobot/greenDAO] can not access toorg.greenrobot.greendao.AbstractDaoSession (#934)




api 'org.greenrobot:greendao:3.2.2'
 If your greendao is in the library ，you must use api or compile ,do not use implementation.

**Comment by xielihuang** [comment]
if you use greendao plugin , and android studio gradle plugin version > 3.4.+ , the greendao plugin was outdated , and greendao website is stoped to update greendao plugin... 
when you build or run , android stuido will show warn info... it means gradle plugin will abandoned some api in 2020...(greendao plugin use some api was outdated...);
hope to know...  




------------------ 原始邮件 ------------------
发件人: "Simon"<notifications@github.com>; 
发送时间: 2019年7月5日(星期五) 中午11:24
收件人: "greenrobot/greenDAO"<greenDAO@noreply.github.com>; 
抄送: "谢立煌"<1517076156@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [greenrobot/greenDAO] can not access toorg.greenrobot.greendao.AbstractDaoSession (#934)




api 'org.greenrobot:greendao:3.2.2'
 If your greendao is in the library ，you must use api or compile ,do not use implementation.

**Comment by jiangdongguo** [comment]
> api 'org.greenrobot:greendao:3.2.2'
> If your greendao is in the library ，you must use api or compile ,do not use implementation.

it worked!Tks!

**Comment by xielihuang** [comment]
thanks~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "蒋东国"<notifications@github.com&gt;; 
发送时间: 2019年12月16日(星期一) 上午10:50
收件人: "greenrobot/greenDAO"<greenDAO@noreply.github.com&gt;; 
抄送: "谢立煌"<1517076156@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [greenrobot/greenDAO] can not access to org.greenrobot.greendao.AbstractDaoSession (#934)



 
api 'org.greenrobot:greendao:3.2.2'
 If your greendao is in the library ，you must use api or compile ,do not use implementation.
  
it worked!Tks!
