### ISSUE TITLE
update encrypted database crash

### ISSUE THREAD

**Issue by koukoucai** [greenrobot/greenDAO#935]
I use greendao-encryption:2.2.0 and android-database-sqlcipher:3.5.9 to make an encrypted database.
Then I update greendao to3.2.2  and sqlcipher to 4.0.0  to open the encrypted database.
There is some exception 

> net.sqlcipher.database.SQLException: file is not a database;

How can I resolve this problem.

**Comment by koukoucai** [comment]
@greenrobot

**Comment by koukoucai** [comment]
I get the reason from
[https://github.com/sqlcipher/android-database-sqlcipher/issues/410](url)
there is no question

**Comment by TerryCheng1978** [comment]
I think that , the OpenHelper class of the DaoMaster should add a new SQLiteDatabaseHook parameter, so that we can fixe this issue.

new SQLiteDatabaseHook() {
                @Override
                public void preKey(net.sqlcipher.database.SQLiteDatabase database) {
                }

                @Override
                public void postKey(net.sqlcipher.database.SQLiteDatabase database) {
                    database.execSQL("PRAGMA cipher_page_size = 1024");
                    database.execSQL("PRAGMA kdf_iter = 64000");
                    database.execSQL("PRAGMA cipher_hmac_algorithm = HMAC_SHA1");
                    database.execSQL("PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1");
                }
            }
