### ISSUE TITLE
doesn't work for accessing existing database on android 9.0 

### ISSUE THREAD

**Issue by cnqdbt** [greenrobot/greenDAO#937]
In my app,  db is copied from android raw folder to phone storage. Then the db is accessed by Greendao. It works well until android 9.0. On android 9.0 devices, it reports "no such table" exception.

**Comment by mahong125** [comment]
Hello, I have encountered the same problem now. Can you solve it here?

**Comment by cnqdbt** [comment]
> Hello, I have encountered the same problem now. Can you solve it here?

it's not a bug of Greendao. after copying the db from assets to phone storage, don't forget to close it. In previous android versions, it doesn't matter. But in 9.0 it matters.
