### ISSUE TITLE
Instant app support 

### ISSUE THREAD

**Issue by peter1492** [greenrobot/greenDAO#940]
i tried to follow the #771 issue, but it seem to not working ::
my files are as below ; 

//Top-level build file
repositories {
       ...
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.3-instant-app-SNAPSHOT'
    }
}

//build.g
apply plugin: 'com.android.feature'
apply plugin: 'org.greenrobot.greendao'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    baseFeature true

    defaultConfig {
        ....

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
       ....
    }

    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }

}

greendao {
    schemaVersion 1
}

dependencies {

 ....
implementation "org.greenrobot:greendao:3.2.2

}

can you help with the same ???

**Comment by greenrobot-team** [comment]
See https://github.com/greenrobot/greenDAO/issues/771
