### ISSUE TITLE
Use new Android Gradle Plugin 3.3+ APIs: WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'

### ISSUE THREAD

**Issue by sjindong** [greenrobot/greenDAO#942]
when i compile the version  with  'org.greenrobot:greendao-gradle-plugin:3.2.2' ，i get an error ：
 `WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: app`

and i try execute a command，**gradlew -Pandroid.debug.obsoleteApi=true**， i get ： 
`>gradlew -Pandroid.debug.obsoleteApi=true

> Configure project :app
WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: It is currently called from the following trace:
java.lang.Thread.getStackTrace(Thread.java:1552)
com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:79)
com.android.build.gradle.internal.api.BaseVariantImpl.getJavaCompiler(BaseVariantImpl.java:447)
com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getJavaCompiler(null:-1)
org.greenrobot.greendao.gradle.AndroidPluginSourceProvider.addGeneratorTask(SourceProvider.kt:62)
org.greenrobot.greendao.gradle.AndroidPluginSourceProvider$addGeneratorTask$1.execute(SourceProvider.kt:46)
org.greenrobot.greendao.gradle.AndroidPluginSourceProvider$addGeneratorTask$1.execute(SourceProvider.kt:27)
org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
org.greenrobot.greendao.gradle.AndroidPluginSourceProvider.addGeneratorTask(SourceProvider.kt:45)
org.greenrobot.greendao.gradle.Greendao3GradlePlugin$apply$1.execute(Greendao3GradlePlugin.kt:50)
org.greenrobot.greendao.gradle.Greendao3GradlePlugin$apply$1.execute(Greendao3GradlePlugin.kt:14)
org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1$1.run(DefaultListenerBuildOperationDecorator.java:155)
... ...
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
java.lang.Thread.run(Thread.java:745)

WARNING: Debugging obsolete API calls can take time during configuration. It's recommended to not keep it on at all times.`

Although this problem will break out in 2020, I hope to solve it in the next version as soon as possible.

**Comment by sjindong** [comment]
I also posted this question on stackoverflow.com . [This Problem](https://stackoverflow.com/questions/54395328/i-use-greendao-3-2-2-and-get-an-error-warning-api-variant-getjavacompiler)

**Comment by greenrobot-team** [comment]
Thanks for reporting. This is due to an API change in Android Gradle Plugin 3.3.0.

However, for now everything should work fine. This is just a warning.

Task: support Android Gradle Plugin 3.3.0 API changes.
-ut

**Comment by wutong751** [comment]
I had the same problem

**Comment by LuigiMaestrelli** [comment]
So, you will wait until the build breaks to fix it?

**Comment by liaopen123** [comment]
how do you fixed it?

**Comment by wzp09tjlg** [comment]
I had the same problem,how do you fixed it?

**Comment by LLLiuWeiJian** [comment]
+11111111111111

**Comment by sjindong** [comment]
@wutong751  @LuigiMaestrelli  @liaopen123  @wzp09tjlg @LLLiuWeiJian 
行了 直接说中文吧，  除了等官方更新，不然怎么办。最起码今年年底前 这个问题毫无影响，除了有个warning

Yes，just wait，At least until the end of 19 years, this is just a warning and does not affect compilation.

**Comment by lizhw123** [comment]
@greenrobot-team When do you plan to solve this problem?

**Comment by wutong751** [comment]
> @wutong751 @LuigiMaestrelli @liaopen123 @wzp09tjlg @LLLiuWeiJian
> 行了 直接说中文吧， 除了等官方更新，不然怎么办。最起码今年年底前 这个问题毫无影响，除了有个warning
> 
> Yes，just wait，At least until the end of 19 years, this is just a warning and does not affect compilation.

好吧

**Comment by TYUpya** [comment]
中文：我也遇到了同样的问题，请问什么时候能解决？
English：I have the same problem. When can I solve it?

**Comment by greenrobot-team** [comment]
> When do you plan to solve this problem?

I can't promise anything, but hopefully when we have time.

**Comment by sjindong** [comment]
@greenrobot-team  so, can i help your team ?  just the part of gradle. if yes, i will  start action

**Comment by WindRush** [comment]
it make my layout resources shows error 
![86480819-B75F-4D55-AF87-381DD74CCBCE](https://user-images.githubusercontent.com/12183976/57860078-c1fa2f80-7826-11e9-9d5f-8ba3de5b8ab0.png)

so when do you plan to solve this

**Comment by WindRush** [comment]
my layout resources cant not preview because this warning

**Comment by heinzan** [comment]
I had the same problem.When time fix?

**Comment by zytq** [comment]
I had the same problem.When time fix?

**Comment by mesterj** [comment]
+1

**Comment by xiaoyifan6** [comment]
+1

**Comment by yeleibo** [comment]
这个有解决方式吗

**Comment by hookbin** [comment]
+1

**Comment by greenrobot-team** [comment]
Update: you can work around the warning by removing the `targetGenDir` property from the `greendao` configuration in your `build.gradle` file.
```
greendao {
    schemaVersion 2
    targetGenDir "some.value" <-- Remove this.
}
```

This will generate greenDAO files into the build folder instead of a custom directory when building the project.
http://greenrobot.org/greendao/documentation/modelling-entities/#Schema

**Comment by LiLustre** [comment]
When will it be updated?

**Comment by lizhen0211** [comment]
When is it updated? I'm in hurry.

**Comment by checkming** [comment]
> @ wutong751 @LuigiMaestrelli @ liaopen123 @ wzp09tjlg @LLLiuWeiJian
> 行了直接说中文吧，除了等官方更新，不然怎么办。最起码今年年底前这个问题毫无影响，除了有个警告
> 
> 是的，等一下，至少到19年底，这只是一个警告，不会影响编译。

哈哈哈 兄弟耿直啊

**Comment by chengfan2017** [comment]
国内的开发风气都已经这样了吗？别人开源项目 不是为了你们对他们指手画脚，源码都给你们不会自己改吗？

**Comment by chengfan2017** [comment]
什么时候都养成一堆臭毛病

**Comment by yalamo** [comment]
Now It will be removed in few days,  what shoud i do?

**Comment by cf-wu** [comment]
(variant.getJavaCompiler() ) Now It will be removed in few days, what shoud i do?

**Comment by cf-wu** [comment]
(variant.getJavaCompiler() ) Now It will be removed in one day, what shoud i do?

**Comment by yalamo** [comment]
> (variant.getJavaCompiler() ) Now It will be removed in one day, what shoud i do?

you are so small, as me hum-hum

**Comment by linford1012** [comment]
> Update: you can work around the warning by removing the `targetGenDir` property from the `greendao` configuration in your `build.gradle` file.
> 
> ```
> greendao {
>     schemaVersion 2
>     targetGenDir "/my/special/directory" <-- Remove this.
> }
> ```
> 
> This will **generate greenDAO files into the build folder** instead of a custom directory when building the project. So make sure to delete the duplicate files from your old targetGenDir.
> http://greenrobot.org/greendao/documentation/modelling-entities/#Schema
> 
> Anyhow, this issue was **fixed internally** and will be available with the **next update**.

not works with this answers for now
