### ISSUE TITLE
doesn't work for accessing existing database on android 9.0

### ISSUE THREAD

**Issue by mahong125** [greenrobot/greenDAO#943]
In my app, db is copied from android raw folder to phone storage. Then the db is accessed by Greendao. It works well until android 9.0. On android 9.0 devices, it reports "no such table" exception.

**Comment by yinbao** [comment]
+1

**Comment by yinbao** [comment]
我貌似是找到问题所在了，在android 9，复制新的数据库进去的时候需要删除旧是数据库信息，包含.db,.db-shm,.db-wal等文件

**Comment by yuwoquan** [comment]
在9.0使用会报错怎么解决啊

**Comment by greenrobot-team** [comment]
https://stackoverflow.com/questions/50476782/android-p-sqlite-no-such-table-error-after-copying-database-from-assets seems to have info on potential issues.

This is a SQLite/Android issue, not a greenDAO issue. So closing.
