### ISSUE TITLE
Failed to change locale for db '/data/data/xxxx/databases/ksdb' to 'zh_CN'

### ISSUE THREAD

**Issue by didixyy** [greenrobot/greenDAO#945]
i have this problem like this
![image](https://user-images.githubusercontent.com/17633836/52777974-e9066100-307f-11e9-8a43-19a14d3df8e1.png)
and  when it find bug int System ，It seems to have something to do with the language environment.
![image](https://user-images.githubusercontent.com/17633836/52778169-55816000-3080-11e9-9836-f2947df04e71.png)
and also have some have this problem
https://stackoverflow.com/questions/21155598/android-sqlite-failed-to-change-locale-for-db-to-zh-cn/21155951 how can i fix it in greenDao

**Comment by greenrobot-team** [comment]
https://stackoverflow.com/questions/21155598/android-sqlite-failed-to-change-locale-for-db-to-zh-cn/21155951 has the answer on how to create your database. Then just use that `SQLiteDatabase` to create `DaoMaster`.
http://greenrobot.org/greendao/documentation/how-to-get-started/#Setting_up_the_database
