### ISSUE TITLE
org.greenrobot.greendao.rx.RxQuery$3: can't find superclass or interface rx.Observable$OnSubscribe

### ISSUE THREAD

**Issue by BryantKawhi** [greenrobot/greenDAO#950]
org.greenrobot.greendao.rx.RxQuery$3: can't find superclass or interface rx.Observable$OnSubscribe
org.greenrobot.greendao.rx.RxUtils$1: can't find superclass or interface rx.functions.Func0
org.greenrobot.greendao.AbstractDao: can't find referenced class rx.schedulers.Schedulers
org.greenrobot.greendao.AbstractDaoSession: can't find referenced class rx.schedulers.Schedulers

org.greenrobot.greendao.query.Query: can't find referenced class rx.schedulers.Schedulers |  
-- | --
org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Scheduler |  
org.greenrobot.greendao.rx.RxBase: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Scheduler |  
org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxDao: can't find referenced class rx.Scheduler |  
org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable$OnSubscribe |  
org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Scheduler |  
org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxQuery: can't find referenced class rx.Scheduler |  
org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber |  
org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.exceptions.Exceptions |  
org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber |  
org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Observable$OnSubscribe |  
org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.exceptions.Exceptions |  
org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Subscriber |  
org.greenrobot.greendao.rx.RxQuery$3: can't find referenced class rx.Observable$OnSubscribe |  
org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Scheduler |  
org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxTransaction: can't find referenced class rx.Scheduler |  
org.greenrobot.greendao.rx.RxUtils: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.functions.Func0 |  
org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.Observable |  
org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.functions.Func0 |  
org.greenrobot.greendao.rx.RxUtils$1: can't find referenced class rx.Observable |  
there were 120 unresolved references to classes or interfaces. |  
Exception while processing task java.io.IOException: Please correct the above warnings first. |

**Comment by greenrobot-team** [comment]
Add the ProGuard rules from http://greenrobot.org/greendao/documentation/technical-faq/

-Uwe

-- [Check out ObjectBox](https://objectbox.io), our new fast, easy to use database!
