### ISSUE TITLE
Android 9.0 Greendao test build failed.

### ISSUE THREAD

**Issue by CooperCao** [greenrobot/greenDAO#953]
DbTest.java 
import android.test.AndroidTestCase;

[https://developer.android.com/reference/android/test/AndroidTestCase](url)
This class was deprecated in API level 24.
Use InstrumentationRegistry instead. New tests should be written using the Android Testing Support Library.

**Comment by greenrobot-team** [comment]
Duplicate of https://github.com/greenrobot/greenDAO/issues/936
