### ISSUE TITLE
Can't downgrade database from version 14 to 13

### ISSUE THREAD

**Issue by AlexQcs** [greenrobot/greenDAO#955]
This problem occurred while upgrading the database and only a few devices showed this proplem.
My application greendao schemaVersion is '14' now.

**Comment by greenrobot-team** [comment]
Check your database helper class if you correctly implemented the `onUpgrade()` method.
http://greenrobot.org/greendao/documentation/how-to-get-started/#Setting_up_the_database

-ut

**Comment by AlexQcs** [comment]
I've already done that.

private void setupDatabase() {
       
        DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(this, "drive.db", null);
      
        SQLiteDatabase db = helper.getWritableDatabase();
       
        DaoMaster daoMaster = new DaoMaster(db);
        
        daoSession = daoMaster.newSession();
    }
