### ISSUE TITLE
Can't find inc_name in OutC for @ToOne relation

### ISSUE THREAD

**Issue by lvi166** [greenrobot/greenDAO#958]
I use `@ToOne`  between Two entity classes  when i make project and show the error
`Can't find inc_name in OutC for @ToOne relation`
how to fix it ,thanks

Android studio version : 3.3.2
gradle :`com.android.tools.build:gradle:3.3.2`
greenDAO version : `implementation 'org.greenrobot:greendao:3.2.2'`

```
package com.inchat.db.entity;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;
@Entity
public class Inc {
    @Id(autoincrement = true)
    private Long id;
    @Property(nameInDb = "inc_name")
    private String name;

}
```
```
package com.inchat.db.entity;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.ToOne;

@Entity
public class OutC {
    @Id(autoincrement = true)
    private Long id;
    @ToOne(joinProperty = "inc_name")
    private Inc inc;
}
```

**Comment by greenrobot-team** [comment]
You are using `@ToOne(joinProperty = "inc_name")` incorrectly. Read up on our website.
http://greenrobot.org/greendao/documentation/relations/

- Uwe
-- [Check out ObjectBox](https://objectbox.io), our new fast, easy to use database!

**Comment by lvi166** [comment]
> You are using `@ToOne(joinProperty = "inc_name")` incorrectly. Read up on our website.
> http://greenrobot.org/greendao/documentation/relations/
> 
> -Uwe
> -- [Check out ObjectBox](https://objectbox.io), our new fast, easy to use database!

Thanks for your help! i resolve the problem
