### ISSUE TITLE
Failed to change locale for db '/data/data/xxxx/databases/ksdb' to 'zh_CN'

### ISSUE THREAD

**Issue by xadlovezy** [greenrobot/greenDAO#967]
Failed to change locale for db '/data/data/xxxx/databases/ksdb' to 'zh_CN'

**Comment by greenrobot-team** [comment]
Sorry, this is a SQLite database error and has nothing to do with greenDAO. See https://github.com/greenrobot/greenDAO/issues/945 for a solution.
-Uwe
