### ISSUE TITLE
when I use 'greendao-gradle-plugin:3.2.2', it warns me that:

### ISSUE THREAD

**Issue by nuli1228588792** [greenrobot/greenDAO#970]
WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

**Comment by greenrobot-team** [comment]
See #942
