### ISSUE TITLE
greendao issue

### ISSUE THREAD

**Issue by xingjianlong** [greenrobot/greenDAO#974]
java.lang.RuntimeException: Unable to create application xxxxx: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/xxxx/databases/xxx.db' to 'zh_CN'. at android.app.ActivityThread.handleBindApplication

**Comment by greenrobot-team** [comment]
See https://github.com/greenrobot/greenDAO/issues/945 for a solution.
