### ISSUE TITLE
Update proguard keep rules

### ISSUE THREAD

**Issue by ricowind** [greenrobot/greenDAO#975]
The current set of keep rules suggested is:
### greenDAO 3
-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
public static java.lang.String TABLENAME;
}
-keep class **$Properties

That does not imply that all of the actual static fields are kept on the **$Properties classes.
That means that the array generated in:
https://github.com/greenrobot/greenDAO/blob/72cad8c9d5bf25d6ed3bdad493cee0aee5af8a70/DaoCore/src/main/java/org/greenrobot/greendao/internal/DaoConfig.java#L98
will have index out of bounds exception since the ordinal value is still the same (assume we have two fields, and remove the first. Now we will index into the array at index 1, but the size of the array is only 1!

You can fix this by doing:
-keepclassmembers class **$Properties { public static <fields>;  }

The problem shows up when using R8 (new shrinker in android studio, default in studio 3.4)
Corresponding R8 bug:
https://issuetracker.google.com/135667509

**Comment by greenrobot-team** [comment]
Thanks for reporting this.

I always thought a keep class rule would keep all of the class.

Can you verify if instead of adding the keepclassmembers rule updating the class rule works:
```
// Replace:
-keep class **$Properties
// With:
-keep class **$Properties {*;}
```

**Comment by greenrobot-team** [comment]
@ricowind Sorry, after reading I'm aware you are not the original reporter. Will try to test this ourselves.

**Comment by greenrobot-team** [comment]
Works, updated rules.

**Comment by justcla** [comment]
@greenrobot-team:
Where are the keep rules updated? Have the new rules been incorporated in to the GreenDAO library?

I see the comment "Works, updated rules.", but I don't see any commits in the repo since 12-Mar-2019.

**Comment by topnax** [comment]
I can confirm that the rules are not updated.

**Comment by greenrobot-team** [comment]
@justcla You can find the latest rules at https://github.com/greenrobot/greenDAO#r8-proguard.
