### ISSUE TITLE
API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'. It will be removed at the end of 2019.

### ISSUE THREAD

**Issue by hantao1024** [greenrobot/greenDAO#979]
API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.

**Comment by adityacp** [comment]
I am also getting the same warning.

**Comment by isudev** [comment]
API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
Please fix this issue.

**Comment by greenrobot-team** [comment]
Thanks for reporting. For now you can continue to use greenDAO, this is just a warning. See #942.
