### ISSUE TITLE
Add Proguard/R8 keep rules to GreenDAO library

### ISSUE THREAD

**Issue by justcla** [greenrobot/greenDAO#982]
So that users don't need to search for and add GreenDAO keep rules to their projects, it would be helpful if known, stable, minimal keep rules could be bundled with the GreenDAO library.

**Comment by greenrobot-team** [comment]
greenDAO is currently not built as an AAR (Android library), so embedding ProGuard rules is not possible.

The rules are linked from the README and can be found in the technical FAQ.
http://greenrobot.org/greendao/documentation/technical-faq/

**Comment by justcla** [comment]
Ahh. My bad. Sorry.

Thanks for posting the rules on the FAQ!
