### ISSUE TITLE
Still receiving proguard warnings after using proguard rules mentioned by site.

### ISSUE THREAD

**Issue by surapuramakhil** [greenrobot/greenDAO#984]
Hie,
I am using proguard rules mentioned from technical documentation
http://greenrobot.org/greendao/documentation/technical-faq/

but still, I am receiving these warnings

Warning: org.greenrobot.greendao.database.DatabaseOpenHelper: can't find referenced method 'net.sqlcipher.database.SQLiteDatabase getReadableDatabase(java.lang.String)' in program class org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper
Warning: org.greenrobot.greendao.database.DatabaseOpenHelper: can't find referenced method 'net.sqlcipher.database.SQLiteDatabase getWritableDatabase(char[])' in program class org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper
Warning: org.greenrobot.greendao.database.DatabaseOpenHelper: can't find referenced method 'net.sqlcipher.database.SQLiteDatabase getReadableDatabase(char[])' in program class org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper

**Comment by surapuramakhil** [comment]
before that, there may geeendao warning after adding rules most of those went off but sill these 3 aren't got fixed by adding pro guard rules

**Comment by greenrobot-team** [comment]
It would help if you shared your ProGuard rules. Did you include
`-dontwarn net.sqlcipher.database.**`
?

Otherwise maybe `-dontwarn org.greenrobot.greendao.database.DatabaseOpenHelper` works?

-- [Check out ObjectBox](https://objectbox.io), our new fast, easy to use database!

**Comment by VishalAr1996** [comment]
hey how can i write progurad rules for greendao with sqlcipher

**Comment by greenrobot-team** [comment]
See the README: https://github.com/greenrobot/greenDAO#r8-proguard

Closing this as no response from original author.
