### ISSUE TITLE
Insert a lot of data

### ISSUE THREAD

**Issue by gxh-apologize** [greenrobot/greenDAO#985]
Hi,  I need to insert a lot of data，like 1000 records.   I need to new 1000 entiy ? Doing so can have an impact on memory.  I was going to reuse it but failed.

Looking forward to reply.Sorry for my poor English.

**Comment by greenrobot-team** [comment]
greenDAO maps SQLite tables to objects, so if you want to use the greenDAO API, then yes, you need to create an entity instance for each new entity to insert.
Note: you can use `dao.insertInTx(entities)` to speed up inserting.

If memory usage is a concern, try to batch insert only a small set of entities.

**Comment by gxh-apologize** [comment]
@greenrobot-team ok , thank you
