### ISSUE TITLE
How can I use loadDeep in toMany relationship?

### ISSUE THREAD

**Issue by luao419** [greenrobot/greenDAO#987]
I want get a List field from one obj,but when I used loadAll,it returned a null value.
I wanted use Gson to convert this obj to a json String ,but it given me a null list in the obj

**Comment by AncientTree** [comment]
Same here

**Comment by greenrobot-team** [comment]
Ah, sorry. This is not documented well, but `loadDeep` [only works for To-One relations](https://greenrobot.org/greendao/documentation/relations/#:~:text=To%20eagerly%20load%20to%2Done%20relations%20use%20loadDeep()%20and%20queryDeep()%20of%20the%20entity%20DAO%20class.).
