### ISSUE TITLE
variant.getJavaCompiler()

### ISSUE THREAD

**Issue by androiddk1** [greenrobot/greenDAO#991]
WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

**Comment by greenrobot-team** [comment]
@androiddk1 See https://github.com/greenrobot/greenDAO/issues/942#issuecomment-511774178.

**Comment by androiddk1** [comment]
Ok,thanks very much!
